/* PromptRunic — cat-es.js: Spanish category name map */
window.PROMPTS_CAT_ES = {
  "3D Modeling": "Modelado 3D",
  "3D Printing": "Impresión 3D",
  "3D Printing Art": "Arte de impresión 3D",
  "A/B Testing": "Pruebas A/B",
  "AI & Machine Learning": "IA y aprendizaje automático",
  "AI Agents": "Agentes de IA",
  "AI Art Tools": "Herramientas de arte con IA",
  "AI Basics": "Fundamentos de IA",
  "AI Chatbots": "Chatbots de IA",
  "AI Code Assistants": "Asistentes de código con IA",
  "AI Ethics": "Ética de la IA",
  "AI Music": "Música con IA",
  "AI Video": "Video con IA",
  "AI Writing Tools": "Herramientas de escritura con IA",
  "AI for Kids": "IA para niños",
  "APIs": "APIs",
  "AR Development": "Desarrollo de RA",
  "ASP.NET": "ASP.NET",
  "AWS Certification": "Certificación AWS",
  "Abstract Art": "Arte abstracto",
  "Academic Coaching": "Coaching académico",
  "Academic Writing": "Escritura académica",
  "Accessibility": "Accesibilidad",
  "Account Management": "Gestión de cuentas",
  "Account-Based Marketing": "Marketing basado en cuentas",
  "Acrylic Painting": "Pintura acrílica",
  "Active Listening": "Escucha activa",
  "Actuarial Science": "Ciencia actuarial",
  "Acupressure": "Acupresión",
  "Adaptability": "Adaptabilidad",
  "Addiction Recovery": "Recuperación de adicciones",
  "Administrative Law": "Derecho administrativo",
  "Adoption": "Adopción",
  "Adult Education": "Educación de adultos",
  "Aerospace Engineering": "Ingeniería aeroespacial",
  "Affiliate Marketing": "Marketing de afiliados",
  "Affiliate Strategy": "Estrategia de afiliados",
  "Africa Travel": "Viajes por África",
  "African Cuisine": "Cocina africana",
  "Agency Building": "Construcción de agencia",
  "Agile": "Ágil",
  "Agile Management": "Gestión ágil",
  "Aging Gracefully": "Envejecer con gracia",
  "Aging Parents": "Padres ancianos",
  "Aging Well": "Envejecimiento saludable",
  "AgriTech": "Tecnología agrícola",
  "Agricultural Science": "Ciencia agrícola",
  "Air Fryer Cooking": "Cocción en freidora de aire",
  "Air Pollution": "Contaminación del aire",
  "Air Quality": "Calidad del aire",
  "Air Travel": "Viajes aéreos",
  "Algebra": "Álgebra",
  "Algorithm Design": "Diseño de algoritmos",
  "Allergy Management": "Manejo de alergias",
  "Alternative Medicine": "Medicina alternativa",
  "Alzheimer's Care": "Cuidado del Alzheimer",
  "Amazon Selling": "Venta en Amazon",
  "Analytical Chemistry": "Química analítica",
  "Ancient History": "Historia antigua",
  "Android Development": "Desarrollo Android",
  "Angel Investing": "Inversión ángel",
  "Anger Management": "Manejo de la ira",
  "Angular": "Angular",
  "Animation": "Animación",
  "Animation 2D": "Animación 2D",
  "Animation 3D": "Animación 3D",
  "Animation for Kids": "Animación para niños",
  "Anti-Aging": "Antienvejecimiento",
  "Antique Restoration": "Restauración de antigüedades",
  "Antiques": "Antigüedades",
  "Anxiety": "Ansiedad",
  "Anxiety Management": "Manejo de la ansiedad",
  "Apartment Living": "Vida en apartamento",
  "Apologizing": "Disculparse",
  "Apology Letters": "Cartas de disculpa",
  "App Monetization": "Monetización de aplicaciones",
  "Appetizers": "Aperitivos",
  "Aquaponics": "Acuaponía",
  "Aquarium": "Acuario",
  "Aquarium Fish": "Peces de acuario",
  "Aquatic Therapy": "Terapia acuática",
  "Archery": "Tiro con arco",
  "Architecture Design": "Diseño arquitectónico",
  "Arduino": "Arduino",
  "Aromatherapy": "Aromaterapia",
  "Art Direction": "Dirección de arte",
  "Art Galleries": "Galerías de arte",
  "Art History": "Historia del arte",
  "Art Portfolio": "Portafolio de arte",
  "Art for Seniors": "Arte para adultos mayores",
  "Asia Travel": "Viajes por Asia",
  "Asian Cuisine": "Cocina asiática",
  "Asset Management": "Gestión de activos",
  "Astrology": "Astrología",
  "Astronomy": "Astronomía",
  "Astrophotography": "Astrofotografía",
  "Astrophysics": "Astrofísica",
  "Asylum Law": "Derecho de asilo",
  "Asynchronous Work": "Trabajo asíncrono",
  "Atmospheric Science": "Ciencia atmosférica",
  "Audio Engineering": "Ingeniería de audio",
  "Audiobook Narration": "Narración de audiolibros",
  "Augmented Reality": "Realidad aumentada",
  "AutoCAD": "AutoCAD",
  "Autoimmune Disorders": "Trastornos autoinmunitarios",
  "Automation": "Automatización",
  "Automation Testing": "Pruebas de automatización",
  "Autonomous Driving": "Conducción autónoma",
  "Autonomous Vehicles": "Vehículos autónomos",
  "Ayurveda": "Ayurveda",
  "Azure": "Azure",
  "B2B Sales": "Ventas B2B",
  "B2C Marketing": "Marketing B2C",
  "BBQ & Grilling": "Barbacoa y parrilla",
  "BMX": "BMX",
  "Baby Care": "Cuidado del bebé",
  "Back Pain": "Dolor de espalda",
  "Backend Development": "Desarrollo backend",
  "Backpacking": "Mochileo",
  "Badminton": "Bádminton",
  "Baking": "Horneado",
  "Balcony Gardening": "Jardinería en balcón",
  "Bankruptcy Law": "Derecho de quiebra",
  "Barre Workout": "Ejercicio de barra",
  "Baseball": "Béisbol",
  "Basketball": "Baloncesto",
  "Battery Technology": "Tecnología de baterías",
  "Beach Destinations": "Destinos de playa",
  "Beat Making": "Creación de beats",
  "Beekeeping": "Apicultura",
  "Beer Brewing": "Elaboración de cerveza",
  "Behavioral Economics": "Economía conductual",
  "Behavioral Health": "Salud conductual",
  "Big Data Analytics": "Análisis de big data",
  "Biochemistry": "Bioquímica",
  "Biodiversity": "Biodiversidad",
  "Bioinformatics": "Bioinformática",
  "Biology": "Biología",
  "Biomechanics": "Biomecánica",
  "Bioprinting": "Bioimpresión",
  "Biotech": "Biotecnología",
  "Birdwatching": "Observación de aves",
  "Blender": "Blender",
  "Blockchain": "Cadena de bloques",
  "Blockchain Dev": "Desarrollo de cadena de bloques",
  "Blog Writing": "Escritura de blogs",
  "Blogging": "Blogs",
  "Blood Pressure": "Presión arterial",
  "Board Game Design": "Diseño de juegos de mesa",
  "Board Games": "Juegos de mesa",
  "Board Governance": "Gobernanza directiva",
  "Body Language": "Lenguaje corporal",
  "Bodybuilding": "Fisicoculturismo",
  "Bond Markets": "Mercados de bonos",
  "Bone Health": "Salud ósea",
  "Bonsai": "Bonsái",
  "Book Club": "Club de lectura",
  "Book Cover Design": "Diseño de portadas de libros",
  "Book Illustration": "Ilustración de libros",
  "Bootstrap": "Bootstrap",
  "Bootstrapping": "Autofinanciamiento",
  "Boxing": "Boxeo",
  "Brain Health": "Salud cerebral",
  "Brain Training": "Entrenamiento cerebral",
  "Brainstorming": "Lluvia de ideas",
  "Brand Guidelines": "Guías de marca",
  "Brand Identity": "Identidad de marca",
  "Brand Strategy": "Estrategia de marca",
  "Branding": "Branding",
  "Brazilian Cuisine": "Cocina brasileña",
  "Bread Making": "Elaboración de pan",
  "Breakfast Recipes": "Recetas de desayuno",
  "Breathing Exercises": "Ejercicios de respiración",
  "Breathwork": "Trabajo respiratorio",
  "Budget Airlines": "Aerolíneas económicas",
  "Budget Travel": "Viajes económicos",
  "Budgeting": "Presupuesto",
  "Bullet Journal": "Bullet Journal",
  "Burnout": "Agotamiento",
  "Bushcraft": "Supervivencia en la naturaleza",
  "Business": "Negocios",
  "Business Analytics": "Analítica de negocios",
  "Business Continuity": "Continuidad del negocio",
  "Business Ideas": "Ideas de negocio",
  "Business Intelligence": "Inteligencia de negocios",
  "Business Process Automation": "Automatización de procesos de negocio",
  "Business Proposals": "Propuestas comerciales",
  "Business Strategy": "Estrategia empresarial",
  "Business Valuation": "Valoración empresarial",
  "C Programming": "Programación en C",
  "C++ Development": "Desarrollo en C++",
  "CAD Design": "Diseño CAD",
  "CMS Development": "Desarrollo de CMS",
  "CNC Machining": "Mecanizado CNC",
  "CSS Advanced": "CSS avanzado",
  "Calculus": "Cálculo",
  "Calisthenics": "Calistenia",
  "Calligraphy": "Caligrafía",
  "Camping": "Camping",
  "Camping Skills": "Habilidades de camping",
  "Campus Life": "Vida universitaria",
  "Cancer Prevention": "Prevención del cáncer",
  "Candle Making": "Elaboración de velas",
  "Canning & Preserving": "Enlatado y conservación",
  "Capital Markets": "Mercados de capitales",
  "Car Buying": "Compra de autos",
  "Car Maintenance": "Mantenimiento de autos",
  "Carbon Capture": "Captura de carbono",
  "Carbon Footprint": "Huella de carbono",
  "Carbon Offsets": "Compensaciones de carbono",
  "Card Games": "Juegos de cartas",
  "Card Making": "Elaboración de tarjetas",
  "Cardio Fitness": "Fitness cardiovascular",
  "Career": "Carrera",
  "Career Change": "Cambio de carrera",
  "Career Growth": "Crecimiento profesional",
  "Career Pivot": "Reorientación profesional",
  "Career Portfolios": "Portafolios profesionales",
  "Caribbean Cuisine": "Cocina caribeña",
  "Cartography": "Cartografía",
  "Cassandra": "Cassandra",
  "Cats": "Gatos",
  "Celiac Disease": "Enfermedad celíaca",
  "Cell Biology": "Biología celular",
  "Ceramics": "Cerámica",
  "Change Management": "Gestión del cambio",
  "Channel Sales": "Ventas por canal",
  "Character Design": "Diseño de personajes",
  "Charisma": "Carisma",
  "Charity & Volunteering": "Caridad y voluntariado",
  "ChatGPT": "ChatGPT",
  "ChatGPT Prompts": "Prompts de ChatGPT",
  "Cheerleading": "Animación deportiva",
  "Cheese Making": "Elaboración de queso",
  "Chemical Engineering": "Ingeniería química",
  "Chemistry": "Química",
  "Chess": "Ajedrez",
  "Child Discipline": "Disciplina infantil",
  "Chinese Cuisine": "Cocina china",
  "Chiropractic Care": "Cuidado quiropráctico",
  "Chocolate Making": "Elaboración de chocolate",
  "Cholesterol Management": "Manejo del colesterol",
  "Chrome Extensions": "Extensiones de Chrome",
  "Chronic Fatigue": "Fatiga crónica",
  "Chronic Illness": "Enfermedad crónica",
  "Churn Reduction": "Reducción de cancelaciones",
  "Cinematography": "Cinematografía",
  "Circular Economy": "Economía circular",
  "Civic Engagement": "Participación cívica",
  "Civic Tech": "Tecnología cívica",
  "Civil Engineering": "Ingeniería civil",
  "Civil Law": "Derecho civil",
  "Civil Rights": "Derechos civiles",
  "Classical Music": "Música clásica",
  "Claude AI": "Claude AI",
  "Clean Energy": "Energía limpia",
  "Cleaning": "Limpieza",
  "Cleaning & Organizing": "Limpieza y organización",
  "Climate Action": "Acción climática",
  "Climate Adaptation": "Adaptación climática",
  "Climate Change": "Cambio climático",
  "Climate Policy": "Política climática",
  "Climate Science": "Ciencia climática",
  "Climatology": "Climatología",
  "Clothing Care": "Cuidado de la ropa",
  "Cloud Architecture": "Arquitectura en la nube",
  "Cloud Computing": "Computación en la nube",
  "Cloud Security": "Seguridad en la nube",
  "Co-Housing": "Covivienda",
  "Co-Parenting": "Copaternidad",
  "Coaching": "Coaching",
  "Coaching Skills": "Habilidades de coaching",
  "Cocktail Recipes": "Recetas de cócteles",
  "Code Review": "Revisión de código",
  "Coding": "Programación",
  "Coding for Kids": "Programación para niños",
  "Coffee & Tea": "Café y té",
  "Coffee Brewing": "Preparación de café",
  "Cognitive Behavioral Therapy": "Terapia cognitivo-conductual",
  "Cold & Flu": "Resfriado y gripe",
  "Cold Email": "Correo en frío",
  "Cold Outreach": "Contacto en frío",
  "Collecting": "Coleccionismo",
  "College Admissions": "Admisión universitaria",
  "College Applications": "Solicitudes universitarias",
  "College Essays": "Ensayos universitarios",
  "Color Grading": "Corrección de color",
  "Color Theory": "Teoría del color",
  "Comfort Zone": "Zona de confort",
  "Comic Art": "Arte cómico",
  "Commodities": "Materias primas",
  "Commodities Trading": "Comercio de materias primas",
  "Communication Skills": "Habilidades de comunicación",
  "Community Building": "Construcción de comunidad",
  "Community Organizing": "Organización comunitaria",
  "Comparative Anatomy": "Anatomía comparada",
  "Comparative Literature": "Literatura comparada",
  "Competitive Analysis": "Análisis competitivo",
  "Competitive Gaming": "Juegos competitivos",
  "Compiler Design": "Diseño de compiladores",
  "Compliance": "Cumplimiento normativo",
  "Composting": "Compostaje",
  "Computer Graphics": "Gráficos por computadora",
  "Computer Networking": "Redes de computadoras",
  "Computer Vision": "Visión por computadora",
  "Concept Art": "Arte conceptual",
  "Condensed Matter Physics": "Física de la materia condensada",
  "Conflict Resolution": "Resolución de conflictos",
  "Conservation": "Conservación",
  "Conservation Biology": "Biología de la conservación",
  "Consignment Business": "Negocio de consignación",
  "Constitutional Law": "Derecho constitucional",
  "Consulting": "Consultoría",
  "Consulting Skills": "Habilidades de consultoría",
  "Containers": "Contenedores",
  "Content Design": "Diseño de contenido",
  "Content Marketing": "Marketing de contenidos",
  "Content Strategy": "Estrategia de contenidos",
  "Content Writing": "Escritura de contenidos",
  "Contract Law": "Derecho contractual",
  "Convention Planning": "Planificación de convenciones",
  "Conversion Optimization": "Optimización de conversión",
  "Cooking": "Cocina",
  "Cooking on a Budget": "Cocina económica",
  "Copywriting": "Redacción publicitaria",
  "Corporate Finance": "Finanzas corporativas",
  "Corporate Law": "Derecho corporativo",
  "Cosplay": "Cosplay",
  "Cost Accounting": "Contabilidad de costos",
  "Couples Therapy": "Terapia de pareja",
  "Cover Letters": "Cartas de presentación",
  "Coworking": "Coworking",
  "Crafts": "Manualidades",
  "Creative": "Creatividad",
  "Creative Coding": "Programación creativa",
  "Creative Direction": "Dirección creativa",
  "Creative Nonfiction": "No ficción creativa",
  "Creative Thinking": "Pensamiento creativo",
  "Creative Writing": "Escritura creativa",
  "Creativity Boost": "Impulso creativo",
  "Credit Analysis": "Análisis crediticio",
  "Credit Score": "Puntuación crediticia",
  "Cricket": "Críquet",
  "Criminal Justice": "Justicia penal",
  "Criminal Law": "Derecho penal",
  "Crisis Communication": "Comunicación de crisis",
  "Crisis Management": "Gestión de crisis",
  "Critical Thinking": "Pensamiento crítico",
  "Cross-Cultural Business": "Negocios interculturales",
  "CrossFit": "CrossFit",
  "Crossword": "Crucigramas",
  "Cruise Planning": "Planificación de cruceros",
  "Cryogenics": "Criogenia",
  "Crypto Trading": "Trading de criptomonedas",
  "Cryptocurrency": "Criptomonedas",
  "Crystallography": "Cristalografía",
  "Cultural Adaptation": "Adaptación cultural",
  "Cultural Exchange": "Intercambio cultural",
  "Cultural Heritage": "Patrimonio cultural",
  "Cultural Intelligence": "Inteligencia cultural",
  "Cultural Travel": "Viajes culturales",
  "Cupcake Decorating": "Decoración de cupcakes",
  "Curriculum Design": "Diseño curricular",
  "Customer Experience": "Experiencia del cliente",
  "Customer Feedback": "Retroalimentación del cliente",
  "Customer Journey": "Recorrido del cliente",
  "Customer Retention": "Retención de clientes",
  "Customer Success": "Éxito del cliente",
  "Customer Success Strategy": "Estrategia de éxito del cliente",
  "Customs & Traditions": "Costumbres y tradiciones",
  "Cyber Law": "Derecho informático",
  "Cyber Threats": "Amenazas cibernéticas",
  "Cybersecurity": "Ciberseguridad",
  "Cycling": "Ciclismo",
  "Cypress Testing": "Pruebas con Cypress",
  "DALL-E": "DALL-E",
  "DAO Governance": "Gobernanza DAO",
  "DIY Home Decor": "Decoración del hogar DIY",
  "DIY Home Repair": "Reparaciones del hogar DIY",
  "DIY Repairs": "Reparaciones DIY",
  "DJing": "DJ",
  "Dairy Science": "Ciencia láctea",
  "Dance": "Danza",
  "Data & Analytics": "Datos y analítica",
  "Data Architecture": "Arquitectura de datos",
  "Data Engineering": "Ingeniería de datos",
  "Data Governance": "Gobernanza de datos",
  "Data Lakes": "Lagos de datos",
  "Data Modeling": "Modelado de datos",
  "Data Pipelines": "Pipelines de datos",
  "Data Privacy": "Privacidad de datos",
  "Data Quality": "Calidad de datos",
  "Data Science": "Ciencia de datos",
  "Data Visualization": "Visualización de datos",
  "Data Warehousing": "Almacenes de datos",
  "Database Design": "Diseño de bases de datos",
  "Databases": "Bases de datos",
  "Databricks": "Databricks",
  "Date Ideas": "Ideas para citas",
  "Dating": "Citas",
  "DeFi": "Finanzas descentralizadas",
  "DeFi Protocols": "Protocolos DeFi",
  "Deal Negotiation": "Negociación de acuerdos",
  "Debate Skills": "Habilidades de debate",
  "Debate for Teens": "Debate para adolescentes",
  "Debt Payoff": "Pago de deudas",
  "Debt Recovery": "Recuperación de deudas",
  "Debugging": "Depuración",
  "Decathlon": "Decatlón",
  "Decision Making": "Toma de decisiones",
  "Deep Learning": "Aprendizaje profundo",
  "Deep Work": "Trabajo profundo",
  "Deforestation": "Deforestación",
  "Delegation": "Delegación",
  "Demand Generation": "Generación de demanda",
  "Dental Care": "Cuidado dental",
  "Dental Health": "Salud dental",
  "Depression Support": "Apoyo para la depresión",
  "Design Patterns": "Patrones de diseño",
  "Design Thinking": "Pensamiento de diseño",
  "Desserts": "Postres",
  "Detoxification": "Desintoxicación",
  "DevOps": "DevOps",
  "Diabetes Management": "Manejo de la diabetes",
  "Diet & Nutrition": "Dieta y nutrición",
  "Diet Planning": "Planificación dietética",
  "Digestive Health": "Salud digestiva",
  "Digital Art": "Arte digital",
  "Digital Banking": "Banca digital",
  "Digital Detox": "Desintoxicación digital",
  "Digital Forensics": "Forense digital",
  "Digital Illustration": "Ilustración digital",
  "Digital Marketing": "Marketing digital",
  "Digital Nomad": "Nómada digital",
  "Digital Privacy": "Privacidad digital",
  "Digital Scrapbooking": "Scrapbooking digital",
  "Digital Sculpting": "Escultura digital",
  "Digital Transformation": "Transformación digital",
  "Digital Twins": "Gemelos digitales",
  "Dinner Recipes": "Recetas de cena",
  "Disability Support": "Apoyo para discapacidades",
  "Disaster Recovery": "Recuperación de desastres",
  "Dispute Resolution": "Resolución de disputas",
  "Distance Learning": "Educación a distancia",
  "Distribution Strategy": "Estrategia de distribución",
  "Diversity & Inclusion": "Diversidad e inclusión",
  "Divorce Recovery": "Recuperación del divorcio",
  "Django": "Django",
  "Docker": "Docker",
  "Documentary Filmmaking": "Realización de documentales",
  "Dog Training": "Adiestramiento canino",
  "Dogs": "Perros",
  "Domain Modeling": "Modelado de dominio",
  "Drawing": "Dibujo",
  "Dream Interpretation": "Interpretación de los sueños",
  "Drone Delivery": "Entrega con drones",
  "Drone Photography": "Fotografía con drones",
  "Drones": "Drones",
  "Dropshipping": "Dropshipping",
  "Drug Interactions": "Interacciones farmacológicas",
  "E-commerce": "Comercio electrónico",
  "E-commerce SEO": "SEO para comercio electrónico",
  "E-commerce Strategy": "Estrategia de comercio electrónico",
  "E-learning Design": "Diseño de e-learning",
  "ESG Investing": "Inversión ASG",
  "ESL Teaching": "Enseñanza de ESL",
  "ETL Pipelines": "Pipelines ETL",
  "Early Childhood Education": "Educación infantil",
  "Earth Science": "Ciencias de la Tierra",
  "Eating Disorders": "Trastornos alimentarios",
  "Eco-Friendly Products": "Productos ecológicos",
  "Eco-Tourism": "Ecoturismo",
  "Ecology": "Ecología",
  "Economic Forecasting": "Pronóstico económico",
  "Economics": "Economía",
  "Ecotourism": "Ecoturismo",
  "EdTech": "Tecnología educativa",
  "Edge Computing": "Computación en el borde",
  "Editorial Design": "Diseño editorial",
  "Education": "Educación",
  "Educational Psychology": "Psicología educativa",
  "Elasticsearch": "Elasticsearch",
  "Eldercare": "Cuidado de ancianos",
  "Elderly Care": "Cuidado de personas mayores",
  "Election Law": "Derecho electoral",
  "Electric Vehicles": "Vehículos eléctricos",
  "Electrical Engineering": "Ingeniería eléctrica",
  "Electromagnetism": "Electromagnetismo",
  "Electron Apps": "Aplicaciones Electron",
  "Electronics Repair": "Reparación de electrónicos",
  "Email": "Correo electrónico",
  "Email Automation": "Automatización de correo",
  "Email Marketing": "Marketing por correo electrónico",
  "Email Writing": "Redacción de correos",
  "Embedded Systems": "Sistemas embebidos",
  "Emergency Medicine": "Medicina de emergencia",
  "Emergency Preparedness": "Preparación para emergencias",
  "Emotion AI": "IA emocional",
  "Emotional Intelligence": "Inteligencia emocional",
  "Empathy": "Empatía",
  "Employee Engagement": "Compromiso de los empleados",
  "Employee Onboarding": "Incorporación de empleados",
  "Employee Training": "Capacitación de empleados",
  "Employment Law": "Derecho laboral",
  "Empty Nest": "Nido vacío",
  "Endocrine Health": "Salud endocrina",
  "Endocrinology": "Endocrinología",
  "Energy Conservation": "Conservación de energía",
  "Energy Engineering": "Ingeniería energética",
  "Energy Healing": "Sanación energética",
  "Energy Management": "Gestión energética",
  "Energy Saving": "Ahorro de energía",
  "English Grammar": "Gramática inglesa",
  "English Learning": "Aprendizaje de inglés",
  "English Literature": "Literatura inglesa",
  "Enterprise Sales": "Ventas empresariales",
  "Entomology": "Entomología",
  "Entrepreneurship": "Emprendimiento",
  "Environmental Engineering": "Ingeniería ambiental",
  "Environmental Impact": "Impacto ambiental",
  "Environmental Law": "Derecho ambiental",
  "Environmental Science": "Ciencias ambientales",
  "Epidemiology": "Epidemiología",
  "Equestrian": "Equitación",
  "Equity Research": "Investigación de valores",
  "Ergonomic Chair": "Silla ergonómica",
  "Ergonomics": "Ergonomía",
  "Escape Room Design": "Diseño de escape rooms",
  "Escape Room Solving": "Resolución de escape rooms",
  "Escape Rooms": "Escape rooms",
  "Essay Writing": "Escritura de ensayos",
  "Ethical Shopping": "Compra ética",
  "Ethics": "Ética",
  "Etiquette": "Etiqueta",
  "Etsy Selling": "Venta en Etsy",
  "Europe Travel": "Viajes por Europa",
  "Evening Routines": "Rutinas nocturnas",
  "Event Marketing": "Marketing de eventos",
  "Event Planning": "Planificación de eventos",
  "Evolutionary Biology": "Biología evolutiva",
  "Exam Prep": "Preparación de exámenes",
  "Executive Coaching": "Coaching ejecutivo",
  "Executive Leadership": "Liderazgo ejecutivo",
  "Exergaming": "Exergaming",
  "Exotic Pets": "Mascotas exóticas",
  "Export Business": "Negocio de exportación",
  "Express.js": "Express.js",
  "Eye Health": "Salud ocular",
  "Facebook Ads": "Anuncios de Facebook",
  "Fair Trade": "Comercio justo",
  "Family Budget": "Presupuesto familiar",
  "Family Business": "Negocio familiar",
  "Family Communication": "Comunicación familiar",
  "Family Law": "Derecho de familia",
  "Family Therapy": "Terapia familiar",
  "Fan Fiction": "Fan fiction",
  "Fantasy Sports": "Deportes fantásticos",
  "Fashion Design": "Diseño de moda",
  "Fashion Styling": "Estilismo de moda",
  "Fasting": "Ayuno",
  "Feedback Skills": "Habilidades de retroalimentación",
  "Fencing": "Esgrima",
  "Feng Shui": "Feng Shui",
  "Fermentation": "Fermentación",
  "Festivals & Events": "Festivales y eventos",
  "Fiction Writing": "Escritura de ficción",
  "Figma": "Figma",
  "Figure Skating": "Patinaje artístico",
  "Film Criticism": "Crítica cinematográfica",
  "Film Directing": "Dirección cinematográfica",
  "Film Editing": "Edición cinematográfica",
  "Filmmaking": "Realización cinematográfica",
  "FinTech": "Tecnología financiera",
  "Finance": "Finanzas",
  "Financial Independence": "Independencia financiera",
  "Financial Modeling": "Modelado financiero",
  "Firebase": "Firebase",
  "First Aid": "Primeros auxilios",
  "Fishing": "Pesca",
  "Fitness": "Fitness",
  "Fitness Over 50": "Fitness para mayores de 50",
  "Flask": "Flask",
  "Flexibility Training": "Entrenamiento de flexibilidad",
  "Floral Design": "Diseño floral",
  "Fluid Dynamics": "Dinámica de fluidos",
  "Flutter": "Flutter",
  "Focus & Concentration": "Enfoque y concentración",
  "Food Safety": "Seguridad alimentaria",
  "Food Science": "Ciencia de los alimentos",
  "Food Tourism": "Turismo gastronómico",
  "Football": "Fútbol",
  "Foraging": "Recolección silvestre",
  "Foreign Language Learning": "Aprendizaje de idiomas extranjeros",
  "Forensic Science": "Ciencia forense",
  "Forex": "Forex",
  "Forgiveness": "Perdón",
  "Franchise Business": "Negocio de franquicia",
  "Franchising": "Franquicias",
  "Freedom of Information": "Libertad de información",
  "Freelance Platforms": "Plataformas freelance",
  "Freelancing": "Trabajo freelance",
  "French Cuisine": "Cocina francesa",
  "French Learning": "Aprendizaje de francés",
  "Friendship": "Amistad",
  "Frontend Performance": "Rendimiento frontend",
  "Functional Medicine": "Medicina funcional",
  "Functional Programming": "Programación funcional",
  "Fundraising": "Recaudación de fondos",
  "Furniture Design": "Diseño de muebles",
  "GIS Mapping": "Mapeo SIG",
  "GTD Method": "Método GTD",
  "Game AI": "IA de juegos",
  "Game Art": "Arte de videojuegos",
  "Game Design": "Diseño de juegos",
  "Game Development": "Desarrollo de juegos",
  "Game Marketing": "Marketing de juegos",
  "Game Monetization": "Monetización de juegos",
  "Game Narratives": "Narrativas de juegos",
  "Game Streaming": "Streaming de juegos",
  "Game UI Design": "Diseño de UI de juegos",
  "Gamification": "Gamificación",
  "Gardening": "Jardinería",
  "Gender Equality": "Igualdad de género",
  "Gene Editing": "Edición genética",
  "Gene Therapy": "Terapia génica",
  "Genealogy": "Genealogía",
  "Generative AI": "IA generativa",
  "Genetics": "Genética",
  "Geocaching": "Geocaching",
  "Geochemistry": "Geoquímica",
  "Geography": "Geografía",
  "Geology": "Geología",
  "Geometry": "Geometría",
  "Geophysics": "Geofísica",
  "German Learning": "Aprendizaje de alemán",
  "Gift Ideas": "Ideas de regalos",
  "Gift Suggestions": "Sugerencias de regalos",
  "Gifted Education": "Educación para superdotados",
  "Git": "Git",
  "Glass Art": "Arte en vidrio",
  "Global Supply Chain": "Cadena de suministro global",
  "Gluten-Free Cooking": "Cocina sin gluten",
  "Go Programming": "Programación en Go",
  "Go-to-Market": "Lanzamiento al mercado",
  "Goal Setting": "Establecimiento de metas",
  "Golf": "Golf",
  "Google Ads": "Anuncios de Google",
  "Google Cloud": "Google Cloud",
  "Google Workspace": "Google Workspace",
  "Graduate School": "Posgrado",
  "Grant Writing": "Redacción de subvenciones",
  "GraphQL": "GraphQL",
  "Graphic Design": "Diseño gráfico",
  "Gratitude Practice": "Práctica de gratitud",
  "Greek Cuisine": "Cocina griega",
  "Green Architecture": "Arquitectura verde",
  "Green Building": "Construcción verde",
  "Green Business": "Negocio verde",
  "Green Energy": "Energía verde",
  "Green Living": "Vida ecológica",
  "Grief & Loss": "Duelo y pérdida",
  "Grooming": "Cuidado personal",
  "Growth Hacking": "Growth hacking",
  "Growth Mindset": "Mentalidad de crecimiento",
  "Guerrilla Marketing": "Marketing guerrillero",
  "Guitar": "Guitarra",
  "Gut Health": "Salud intestinal",
  "Gymnastics": "Gimnasia",
  "HIIT": "HIIT",
  "HR": "Recursos humanos",
  "HR Analytics": "Analítica de RRHH",
  "Habit Stacking": "Acumulación de hábitos",
  "Habit Trackers": "Rastreadores de hábitos",
  "Habitat Restoration": "Restauración de hábitats",
  "Habits": "Hábitos",
  "Hacking Ethics": "Ética del hacking",
  "Hadoop": "Hadoop",
  "Hair Care": "Cuidado del cabello",
  "Hair Loss": "Caída del cabello",
  "Ham Radio": "Radioafición",
  "Handball": "Balonmano",
  "Happiness": "Felicidad",
  "Hardware Security": "Seguridad de hardware",
  "Haskell": "Haskell",
  "Headache Relief": "Alivio del dolor de cabeza",
  "Health": "Salud",
  "HealthTech": "Tecnología de la salud",
  "Healthcare Law": "Derecho sanitario",
  "Healthy Eating": "Alimentación saludable",
  "Healthy Snacks": "Snacks saludables",
  "Hearing Health": "Salud auditiva",
  "Heart Health": "Salud cardíaca",
  "Hedge Funds": "Fondos de cobertura",
  "Herbal Medicine": "Medicina herbaria",
  "Herbalism": "Herbalismo",
  "Heritage Sites": "Sitios patrimoniales",
  "Higher Education": "Educación superior",
  "Hiking": "Senderismo",
  "Hiking Gear": "Equipo de senderismo",
  "Hiring": "Contratación",
  "History": "Historia",
  "Holistic Health": "Salud holística",
  "Home": "Hogar",
  "Home Automation": "Automatización del hogar",
  "Home Brewing": "Elaboración casera",
  "Home Buying": "Compra de vivienda",
  "Home Decoration": "Decoración del hogar",
  "Home Finance": "Finanzas del hogar",
  "Home Healthcare": "Atención médica domiciliaria",
  "Home Office Setup": "Configuración de oficina en casa",
  "Home Organization": "Organización del hogar",
  "Home Renovation": "Renovación del hogar",
  "Home Security": "Seguridad del hogar",
  "Home Selling": "Venta de vivienda",
  "Homeopathy": "Homeopatía",
  "Homeschool Curriculum": "Currículo de educación en casa",
  "Homeschooling": "Educación en casa",
  "Homesteading": "Vida autosuficiente",
  "Honeymoon Planning": "Planificación de luna de miel",
  "Hormone Health": "Salud hormonal",
  "Horse Riding": "Equitación",
  "Horticulture": "Horticultura",
  "Hospice Care": "Cuidados paliativos",
  "Hospitality": "Hostelería",
  "Hostel Travel": "Viajes en hostales",
  "Hotel Booking": "Reserva de hoteles",
  "Houseplants": "Plantas de interior",
  "Human Resources": "Recursos humanos",
  "Human Rights": "Derechos humanos",
  "Humor & Wit": "Humor e ingenio",
  "Hunting": "Caza",
  "Hydration": "Hidratación",
  "Hydrogen Energy": "Energía de hidrógeno",
  "Hydrology": "Hidrología",
  "Hydroponics": "Hidroponía",
  "Hypnotherapy": "Hipnoterapia",
  "IP Law": "Derecho de propiedad intelectual",
  "IPO": "IPO",
  "IPO Process": "Proceso de IPO",
  "IQ Testing": "Test de CI",
  "IT Consulting": "Consultoría de TI",
  "IT Infrastructure": "Infraestructura de TI",
  "IT Service Management": "Gestión de servicios de TI",
  "Ice Hockey": "Hockey sobre hielo",
  "Identity Change": "Cambio de identidad",
  "Identity Development": "Desarrollo de identidad",
  "Illustration": "Ilustración",
  "Image": "Imagen",
  "Immigration": "Inmigración",
  "Immigration Law": "Derecho de inmigración",
  "Immune System": "Sistema inmunológico",
  "Immunology": "Inmunología",
  "Import Business": "Negocio de importación",
  "Imposter Syndrome": "Síndrome del impostor",
  "Incident Management": "Gestión de incidentes",
  "Incident Response": "Respuesta a incidentes",
  "Index Funds": "Fondos indexados",
  "Indian Cuisine": "Cocina india",
  "Indie Hacking": "Indie hacking",
  "Indigenous Culture": "Cultura indígena",
  "Indoor Cycling": "Ciclismo en interiores",
  "Indoor Plants": "Plantas de interior",
  "Industrial Engineering": "Ingeniería industrial",
  "Industry Conferences": "Conferencias de la industria",
  "Infection Prevention": "Prevención de infecciones",
  "Influencer Marketing": "Marketing de influencers",
  "Influencer Strategy": "Estrategia de influencers",
  "Injury Recovery": "Recuperación de lesiones",
  "Inner Peace": "Paz interior",
  "Innovation Management": "Gestión de la innovación",
  "Insomnia": "Insomnio",
  "Instagram Growth": "Crecimiento en Instagram",
  "Instant Pot": "Olla a presión",
  "InsurTech": "Tecnología de seguros",
  "Insurance": "Seguros",
  "Integrated Health": "Salud integrativa",
  "Intellectual Property": "Propiedad intelectual",
  "Intentional Living": "Vida intencional",
  "Interior Decorating": "Decoración de interiores",
  "Interior Design": "Diseño de interiores",
  "Interior Styling": "Estilismo de interiores",
  "Internal Audit": "Auditoría interna",
  "International Law": "Derecho internacional",
  "International Trade": "Comercio internacional",
  "Internet Regulation": "Regulación de internet",
  "Interview Skills": "Habilidades de entrevista",
  "Inventory": "Inventario",
  "Inventory Management": "Gestión de inventario",
  "Investing": "Inversión",
  "Investment Banking": "Banca de inversión",
  "Investor Relations": "Relaciones con inversores",
  "IoT": "IoT",
  "IoT Platforms": "Plataformas IoT",
  "Italian Cuisine": "Cocina italiana",
  "Japanese Cuisine": "Cocina japonesa",
  "Japanese Learning": "Aprendizaje de japonés",
  "Java Advanced": "Java avanzado",
  "JavaScript Advanced": "JavaScript avanzado",
  "Jenkins CI": "Jenkins CI",
  "Jewelry Design": "Diseño de joyería",
  "Job Interviews": "Entrevistas de trabajo",
  "Job Search": "Búsqueda de empleo",
  "Joint Health": "Salud articular",
  "Journaling": "Diario personal",
  "Journaling Practice": "Práctica de diario",
  "Journalism": "Periodismo",
  "Joyful Living": "Vida alegre",
  "Judicial Process": "Proceso judicial",
  "Judo": "Judo",
  "Juggling": "Malabares",
  "K-12 STEM": "STEM K-12",
  "KPI Design": "Diseño de KPI",
  "Kafka": "Kafka",
  "Kali Linux": "Kali Linux",
  "Karate": "Karate",
  "Keto Recipes": "Recetas cetogénicas",
  "Kettlebell": "Kettlebell",
  "Key Account Management": "Gestión de cuentas clave",
  "Keyword Research": "Investigación de palabras clave",
  "Kickboxing": "Kickboxing",
  "Kidney Health": "Salud renal",
  "Kindness Practice": "Práctica de la bondad",
  "Kinesiology": "Cinesiología",
  "Knitting": "Tejido",
  "Knitting & Sewing": "Tejido y costura",
  "Korean Cuisine": "Cocina coreana",
  "Korean Learning": "Aprendizaje de coreano",
  "Kotlin": "Kotlin",
  "Kubernetes": "Kubernetes",
  "LEGO": "LEGO",
  "LLM Fine-Tuning": "Ajuste fino de LLM",
  "Lab Work": "Trabajo de laboratorio",
  "Lab-Grown Meat": "Carne de cultivo",
  "Labor Disputes": "Disputas laborales",
  "Lacrosse": "Lacrosse",
  "Landlord Rights": "Derechos del propietario",
  "Landscape Design": "Diseño de paisajes",
  "Landscape Painting": "Pintura de paisajes",
  "Landscape Photography": "Fotografía de paisajes",
  "Language Acquisition": "Adquisición del lenguaje",
  "Language Exchange": "Intercambio de idiomas",
  "Language Immersion": "Inmersión lingüística",
  "Language Learning": "Aprendizaje de idiomas",
  "Language Models": "Modelos de lenguaje",
  "Laravel": "Laravel",
  "Large Language Models": "Modelos de lenguaje grandes",
  "Laser Cutting": "Corte láser",
  "Lateral Thinking": "Pensamiento lateral",
  "Latin America Travel": "Viajes por Latinoamérica",
  "Latin American Cuisine": "Cocina latinoamericana",
  "Laundry": "Lavandería",
  "Law School": "Facultad de derecho",
  "Layer 2 Scaling": "Escalabilidad de capa 2",
  "Lead Generation": "Generación de prospectos",
  "Leadership": "Liderazgo",
  "Leadership Development": "Desarrollo de liderazgo",
  "Lean Management": "Gestión lean",
  "Learning": "Aprendizaje",
  "Leasing Business": "Negocio de arrendamiento",
  "Leather Craft": "Artesanía en cuero",
  "Leather Crafting": "Trabajo en cuero",
  "Legacy Planning": "Planificación de legado",
  "Legal": "Legal",
  "Legal Aid": "Asistencia legal",
  "Legal Research": "Investigación legal",
  "Library Science": "Bibliotecología",
  "Licensing": "Licenciamiento",
  "Life Balance": "Equilibrio de vida",
  "Life Coaching": "Coaching de vida",
  "Life Purpose": "Propósito de vida",
  "Life Transitions": "Transiciones de vida",
  "Linguistics": "Lingüística",
  "Link Building": "Construcción de enlaces",
  "LinkedIn": "LinkedIn",
  "LinkedIn Ads": "Anuncios de LinkedIn",
  "LinkedIn Growth": "Crecimiento en LinkedIn",
  "Linux": "Linux",
  "Linux Administration": "Administración de Linux",
  "Linux Security": "Seguridad en Linux",
  "Literacy Programs": "Programas de alfabetización",
  "Literary Analysis": "Análisis literario",
  "Live Streaming": "Transmisión en vivo",
  "Liver Health": "Salud hepática",
  "Local SEO": "SEO local",
  "Logic Puzzles": "Rompecabezas lógicos",
  "Logistics Management": "Gestión logística",
  "Logo Design": "Diseño de logotipos",
  "Loneliness": "Soledad",
  "Longevity": "Longevidad",
  "Loyalty Programs": "Programas de fidelización",
  "Lua Programming": "Programación en Lua",
  "Lung Health": "Salud pulmonar",
  "Luxury Hotels": "Hoteles de lujo",
  "Luxury Travel": "Viajes de lujo",
  "M&A": "Fusiones y adquisiciones",
  "MATLAB": "MATLAB",
  "MERN Stack": "Stack MERN",
  "MLOps": "MLOps",
  "Machine Learning Ops": "Operaciones de aprendizaje automático",
  "Magic Tricks": "Trucos de magia",
  "Maker Education": "Educación maker",
  "Makeup Artistry": "Maquillaje artístico",
  "Management Consulting": "Consultoría de gestión",
  "Mandarin Learning": "Aprendizaje de mandarín",
  "Manhood": "Masculinidad",
  "Manners": "Modales",
  "Marathon Training": "Entrenamiento de maratón",
  "Marine Biology": "Biología marina",
  "Maritime Law": "Derecho marítimo",
  "Market Entry": "Entrada al mercado",
  "Market Research": "Investigación de mercado",
  "Marketing": "Marketing",
  "Marketplace Building": "Construcción de marketplace",
  "Marriage": "Matrimonio",
  "Marriage Counseling": "Consejería matrimonial",
  "Mars Colonization": "Colonización de Marte",
  "Mars Mission": "Misión a Marte",
  "Martial Arts": "Artes marciales",
  "Massage Therapy": "Terapia de masaje",
  "Materials Science": "Ciencia de materiales",
  "Math": "Matemáticas",
  "Math Education": "Educación matemática",
  "Meal Planning": "Planificación de comidas",
  "Meal Prep": "Preparación de comidas",
  "Mechanical Engineering": "Ingeniería mecánica",
  "Media Literacy": "Alfabetización mediática",
  "Mediation": "Mediación",
  "Medical Imaging": "Imagen médica",
  "Medical School": "Facultad de medicina",
  "Medication Management": "Gestión de medicamentos",
  "Meditation": "Meditación",
  "Meditation Apps": "Apps de meditación",
  "Mediterranean Diet": "Dieta mediterránea",
  "Meeting Agendas": "Agendas de reuniones",
  "Meetings": "Reuniones",
  "Memory": "Memoria",
  "Memory Improvement": "Mejora de la memoria",
  "Men's Grooming": "Cuidado personal masculino",
  "Men's Health": "Salud masculina",
  "Mental Clarity": "Claridad mental",
  "Mental Health": "Salud mental",
  "Mental Health First Aid": "Primeros auxilios de salud mental",
  "Mentorship": "Mentoría",
  "Metabolic Health": "Salud metabólica",
  "Metallurgy": "Metalurgia",
  "Metaverse": "Metaverso",
  "Meteorology": "Meteorología",
  "Mexican Cuisine": "Cocina mexicana",
  "Micro Frontends": "Micro frontends",
  "Micro-SaaS": "Micro-SaaS",
  "Microbiology": "Microbiología",
  "Microfinance": "Microfinanzas",
  "Microservices": "Microservicios",
  "Middle East Travel": "Viajes por Oriente Medio",
  "Middle Eastern Cuisine": "Cocina de Oriente Medio",
  "Midjourney": "Midjourney",
  "Midlife Crisis": "Crisis de la mediana edad",
  "Military Law": "Derecho militar",
  "Mind Mapping": "Mapas mentales",
  "Mind-Body Connection": "Conexión mente-cuerpo",
  "Mindfulness": "Atención plena",
  "Mindfulness Exercises": "Ejercicios de atención plena",
  "Mindfulness Meditation": "Meditación de atención plena",
  "Mindset Shift": "Cambio de mentalidad",
  "Miniature Painting": "Pintura en miniatura",
  "Minimalism": "Minimalismo",
  "Mixology": "Mixología",
  "Mobile Apps": "Aplicaciones móviles",
  "Mobile Payments": "Pagos móviles",
  "Mobile Photography": "Fotografía móvil",
  "Mobile Security": "Seguridad móvil",
  "Mobile UI Design": "Diseño de UI móvil",
  "Mobility Training": "Entrenamiento de movilidad",
  "Model Building": "Construcción de modelos",
  "Model UN": "Modelo de la ONU",
  "Molecular Biology": "Biología molecular",
  "MongoDB": "MongoDB",
  "Mongoose": "Mongoose",
  "Montessori Activities": "Actividades Montessori",
  "Mood Disorders": "Trastornos del estado de ánimo",
  "Morning Routines": "Rutinas matutinas",
  "Mortgage Banking": "Banca hipotecaria",
  "Motherhood": "Maternidad",
  "Motion Graphics": "Gráficos en movimiento",
  "Motivation": "Motivación",
  "Mountain Biking": "Ciclismo de montaña",
  "Mountaineering": "Alpinismo",
  "Movie Making for Kids": "Cine para niños",
  "Movie Recommendations": "Recomendaciones de películas",
  "Moving": "Mudanza",
  "Multilevel Marketing": "Marketing multinivel",
  "Mural Art": "Arte mural",
  "Mural Painting": "Pintura mural",
  "Muscle Recovery": "Recuperación muscular",
  "Museum Visits": "Visitas a museos",
  "Mushroom Hunting": "Búsqueda de setas",
  "Music Composition": "Composición musical",
  "Music Production": "Producción musical",
  "Music Theory": "Teoría musical",
  "Mutual Funds": "Fondos mutuos",
  "NDA Drafting": "Redacción de NDA",
  "NFT & Digital Art": "NFT y arte digital",
  "NFT Minting": "Acuñación de NFT",
  "NLP": "Procesamiento del lenguaje natural",
  "Nanotechnology": "Nanotecnología",
  "Naturopathy": "Naturopatía",
  "Negotiation": "Negociación",
  "Negotiation Mastery": "Dominio de la negociación",
  "Negotiation Skills": "Habilidades de negociación",
  "Negotiation Tactics": "Tácticas de negociación",
  "Net Promoter Score": "Net Promoter Score",
  "Net Zero Strategy": "Estrategia net zero",
  "Networking": "Redes de contacto",
  "Neural Networks": "Redes neuronales",
  "Neurological Health": "Salud neurológica",
  "Neuroscience": "Neurociencia",
  "Neurotech": "Neurotecnología",
  "Neurotechnology": "Neurotecnología",
  "New Parents": "Padres primerizos",
  "Newsletter Content": "Contenido de boletines",
  "Newsletter Growth": "Crecimiento de boletines",
  "Next.js": "Next.js",
  "Nginx": "Nginx",
  "No-Code Tools": "Herramientas sin código",
  "NoSQL Databases": "Bases de datos NoSQL",
  "Nonprofit Management": "Gestión de organizaciones sin fines de lucro",
  "North America Travel": "Viajes por Norteamérica",
  "Note-Taking": "Toma de notas",
  "Notion": "Notion",
  "Novel Writing": "Escritura de novelas",
  "Nuclear Energy": "Energía nuclear",
  "Nuclear Engineering": "Ingeniería nuclear",
  "Nuclear Physics": "Física nuclear",
  "Nutrition": "Nutrición",
  "Nutrition Coaching": "Coaching nutricional",
  "OAuth Security": "Seguridad OAuth",
  "Obesity Management": "Manejo de la obesidad",
  "Objective-C": "Objective-C",
  "Occupational Health": "Salud ocupacional",
  "Ocean Conservation": "Conservación oceánica",
  "Ocean Pollution": "Contaminación oceánica",
  "Ocean Science": "Ciencia del océano",
  "Ocean Swimming": "Natación en aguas abiertas",
  "Oceania Travel": "Viajes por Oceanía",
  "Off-Grid Living": "Vida fuera de la red",
  "Office Management": "Gestión de oficina",
  "Onboarding": "Incorporación",
  "Oncology Support": "Apoyo oncológico",
  "Online Courses": "Cursos en línea",
  "Online Teaching": "Enseñanza en línea",
  "Open Government": "Gobierno abierto",
  "Open Source": "Código abierto",
  "OpenGL": "OpenGL",
  "Operating Systems": "Sistemas operativos",
  "Operations Management": "Gestión de operaciones",
  "Ophthalmology": "Oftalmología",
  "Optics": "Óptica",
  "Options Trading": "Trading de opciones",
  "Oracle Systems": "Sistemas Oracle",
  "Organic Chemistry": "Química orgánica",
  "Organic Farming": "Agricultura orgánica",
  "Organization Skills": "Habilidades de organización",
  "Organizational Design": "Diseño organizacional",
  "Origami": "Origami",
  "Ornithology": "Ornitología",
  "Orthopedics": "Ortopedia",
  "Osteoporosis": "Osteoporosis",
  "Outsourcing": "Externalización",
  "PCB Design": "Diseño de PCB",
  "PHP Development": "Desarrollo en PHP",
  "PR & Media": "Relaciones públicas y medios",
  "Packaging Design": "Diseño de empaques",
  "Paid Ads": "Anuncios de pago",
  "Pain Management": "Manejo del dolor",
  "Painting": "Pintura",
  "Paleontology": "Paleontología",
  "Palliative Care": "Cuidados paliativos",
  "Paper Crafts": "Manualidades en papel",
  "Parenting": "Crianza",
  "Parkinson's Support": "Apoyo para el Parkinson",
  "Parkour": "Parkour",
  "Partnership Marketing": "Marketing de alianzas",
  "Partnership Strategy": "Estrategia de alianzas",
  "Party Planning": "Planificación de fiestas",
  "Passion Discovery": "Descubrimiento de pasiones",
  "Passive Income": "Ingreso pasivo",
  "Passport & Visa": "Pasaporte y visa",
  "Pasta Making": "Elaboración de pasta",
  "Pastry": "Repostería",
  "Patent Law": "Derecho de patentes",
  "Patience": "Paciencia",
  "Pattern Design": "Diseño de patrones",
  "Payroll Management": "Gestión de nóminas",
  "Pediatric Health": "Salud pediátrica",
  "Penetration Testing": "Pruebas de penetración",
  "Pension Planning": "Planificación de pensiones",
  "Perfectionism": "Perfeccionismo",
  "Performance Art": "Arte de performance",
  "Performance Management": "Gestión del desempeño",
  "Performance Reviews": "Evaluaciones de desempeño",
  "Performance Testing": "Pruebas de rendimiento",
  "Permaculture": "Permacultura",
  "Personal": "Personal",
  "Personal Branding": "Marca personal",
  "Personal CRM": "CRM personal",
  "Personal Finance": "Finanzas personales",
  "Personal Growth": "Crecimiento personal",
  "Personal Injury": "Lesiones personales",
  "Personalized Medicine": "Medicina personalizada",
  "Persuasion": "Persuasión",
  "Pest Control": "Control de plagas",
  "Pet Care": "Cuidado de mascotas",
  "Pet Therapy": "Terapia con mascotas",
  "Pet Training": "Entrenamiento de mascotas",
  "Petroleum Engineering": "Ingeniería del petróleo",
  "Pets": "Mascotas",
  "Pharmacology": "Farmacología",
  "Pharmacy": "Farmacia",
  "Philosophy": "Filosofía",
  "Phonics": "Fonética",
  "Photo Editing": "Edición de fotos",
  "Photography": "Fotografía",
  "Photography Travel": "Viajes fotográficos",
  "Photography for Teens": "Fotografía para adolescentes",
  "Photovoltaics": "Fotovoltaica",
  "Physical Education": "Educación física",
  "Physical Rehabilitation": "Rehabilitación física",
  "Physical Therapy": "Fisioterapia",
  "Physics": "Física",
  "Piano": "Piano",
  "Pickleball": "Pickleball",
  "Pilates": "Pilates",
  "Pilgrimage": "Peregrinación",
  "Plant Care": "Cuidado de plantas",
  "Plasma Physics": "Física del plasma",
  "Plastic Reduction": "Reducción de plásticos",
  "Platform Business": "Negocio de plataforma",
  "Play-Based Learning": "Aprendizaje basado en el juego",
  "Podcast Editing": "Edición de podcasts",
  "Podcast Marketing": "Marketing de podcasts",
  "Podcast Topics": "Temas de podcasts",
  "Podcasting": "Podcasting",
  "Poetry": "Poesía",
  "Poetry Writing": "Escritura de poesía",
  "Political Science": "Ciencia política",
  "Polymer Science": "Ciencia de polímeros",
  "Pomodoro Technique": "Técnica Pomodoro",
  "Portfolio Career": "Carrera de portafolio",
  "Portfolio Management": "Gestión de portafolios",
  "Portrait Photography": "Fotografía de retrato",
  "Portuguese Learning": "Aprendizaje de portugués",
  "Positive Affirmations": "Afirmaciones positivas",
  "Positive Psychology": "Psicología positiva",
  "PostgreSQL": "PostgreSQL",
  "Postpartum Care": "Cuidado posparto",
  "Posture": "Postura",
  "Posture Correction": "Corrección de postura",
  "Pottery": "Alfarería",
  "Power BI": "Power BI",
  "Powerlifting": "Levantamiento de potencia",
  "Pregnancy": "Embarazo",
  "Prenatal Care": "Cuidado prenatal",
  "Prepping": "Preparación de emergencia",
  "Prescription Drugs": "Medicamentos recetados",
  "Presentation Skills": "Habilidades de presentación",
  "Preventive Medicine": "Medicina preventiva",
  "Pricing": "Fijación de precios",
  "Pricing Strategy": "Estrategia de precios",
  "Print Design": "Diseño para impresión",
  "Print on Demand": "Impresión bajo demanda",
  "Printmaking": "Grabado",
  "Privacy Law": "Derecho a la privacidad",
  "Private Equity": "Capital privado",
  "Probiotics": "Probióticos",
  "Problem Solving": "Resolución de problemas",
  "Process Optimization": "Optimización de procesos",
  "Procrastination": "Procrastinación",
  "Procurement": "Adquisiciones",
  "Product Descriptions": "Descripciones de productos",
  "Product Design": "Diseño de productos",
  "Product Hunt Launch": "Lanzamiento en Product Hunt",
  "Product Launch": "Lanzamiento de productos",
  "Product Lifecycle": "Ciclo de vida del producto",
  "Product Management": "Gestión de productos",
  "Product Marketing": "Marketing de productos",
  "Product-Led Growth": "Crecimiento impulsado por el producto",
  "Productivity": "Productividad",
  "Productized Services": "Servicios productizados",
  "Programmatic Ads": "Anuncios programáticos",
  "Project Management": "Gestión de proyectos",
  "Project Planning": "Planificación de proyectos",
  "Prompt Engineering": "Ingeniería de prompts",
  "Prompt Engineering Advanced": "Ingeniería de prompts avanzada",
  "Proofreading": "Corrección de pruebas",
  "Prop Making": "Elaboración de utilería",
  "Property Law": "Derecho inmobiliario",
  "Psychiatry": "Psiquiatría",
  "Psychology": "Psicología",
  "Psychotherapy": "Psicoterapia",
  "Public Administration": "Administración pública",
  "Public Policy": "Política pública",
  "Public Relations": "Relaciones públicas",
  "Public Schools": "Escuelas públicas",
  "Public Speaking": "Oratoria",
  "Public Speaking for Kids": "Oratoria para niños",
  "Public Transport": "Transporte público",
  "Puzzle Design": "Diseño de rompecabezas",
  "Puzzle Solving": "Resolución de rompecabezas",
  "PyTorch": "PyTorch",
  "Python": "Python",
  "QA Testing": "Pruebas de QA",
  "Quality Assurance": "Aseguramiento de calidad",
  "Quantum Computing": "Computación cuántica",
  "Quantum Mechanics": "Mecánica cuántica",
  "Quilting": "Acolchado",
  "R Programming": "Programación en R",
  "RAG Systems": "Sistemas RAG",
  "REITs": "REITs",
  "REST API Design": "Diseño de API REST",
  "RPA Automation": "Automatización RPA",
  "RV Living": "Vida en autocaravana",
  "RabbitMQ": "RabbitMQ",
  "Racquetball": "Racquetball",
  "Rail Travel": "Viajes en tren",
  "Rainwater Harvesting": "Recolección de agua de lluvia",
  "Raspberry Pi": "Raspberry Pi",
  "React": "React",
  "React Native": "React Native",
  "React Patterns": "Patrones de React",
  "Reading Comprehension": "Comprensión lectora",
  "Reading Lists": "Listas de lectura",
  "Reading More": "Leer más",
  "Real Estate": "Bienes raíces",
  "Real Estate Finance": "Finanzas inmobiliarias",
  "Real Estate Investing": "Inversión inmobiliaria",
  "Recipe Creation": "Creación de recetas",
  "Recommendation Letters": "Cartas de recomendación",
  "Recruitment": "Reclutamiento",
  "Recycling": "Reciclaje",
  "Redis": "Redis",
  "Referral Programs": "Programas de referidos",
  "Reflexology": "Reflexología",
  "RegTech": "Tecnología regulatoria",
  "Regulatory Affairs": "Asuntos regulatorios",
  "Regulatory Compliance": "Cumplimiento regulatorio",
  "Rehabilitation": "Rehabilitación",
  "Reiki": "Reiki",
  "Reinforcement Learning": "Aprendizaje por refuerzo",
  "Relationship Advice": "Consejos de relaciones",
  "Relationship Building": "Construcción de relaciones",
  "Relationships": "Relaciones",
  "Religious Studies": "Estudios religiosos",
  "Relocation": "Reubicación",
  "Remote Team Building": "Cohesión de equipos remotos",
  "Remote Work": "Trabajo remoto",
  "Remote Work Tools": "Herramientas de trabajo remoto",
  "Renewable Energy": "Energía renovable",
  "Renewable Resources": "Recursos renovables",
  "Renting": "Alquiler",
  "Report Writing": "Redacción de informes",
  "Reproductive Health": "Salud reproductiva",
  "Reptile Care": "Cuidado de reptiles",
  "Repurposing": "Reutilización",
  "Research": "Investigación",
  "Research Methods": "Métodos de investigación",
  "Resilience": "Resiliencia",
  "Resilience Building": "Construcción de resiliencia",
  "Respiratory Health": "Salud respiratoria",
  "Restaurants": "Restaurantes",
  "Restless Leg Syndrome": "Síndrome de piernas inquietas",
  "Resume Writing": "Redacción de currículum",
  "Retail": "Comercio minorista",
  "Retargeting": "Retargeting",
  "Retirement Planning": "Planificación de jubilación",
  "Revenue Operations": "Operaciones de ingresos",
  "Risk Assessment": "Evaluación de riesgos",
  "Risk Management": "Gestión de riesgos",
  "Rituals & Routines": "Rituales y rutinas",
  "Road Trips": "Viajes por carretera",
  "Robot Programming": "Programación de robots",
  "Robotics": "Robótica",
  "Robotics Education": "Educación en robótica",
  "Robotics Engineering": "Ingeniería de robótica",
  "Robotics for Kids": "Robótica para niños",
  "Rock Climbing": "Escalada en roca",
  "Roller Skating": "Patinaje sobre ruedas",
  "Romance": "Romance",
  "Rooftop Garden": "Jardín en la azotea",
  "Rowing": "Remo",
  "Royalties": "Regalías",
  "Ruby on Rails": "Ruby on Rails",
  "Rugby": "Rugby",
  "Running": "Running",
  "Running Injuries": "Lesiones por running",
  "Running Marathon": "Maratón de running",
  "Rust Programming": "Programación en Rust",
  "SAT Prep": "Preparación del SAT",
  "SEO": "SEO",
  "SEO Strategy": "Estrategia SEO",
  "SQL Optimization": "Optimización SQL",
  "STEM Education": "Educación STEM",
  "SaaS": "SaaS",
  "SaaS Business": "Negocio SaaS",
  "SaaS Development": "Desarrollo SaaS",
  "Sabbatical": "Año sabático",
  "Sailing": "Vela",
  "Salad Recipes": "Recetas de ensaladas",
  "Salary Negotiation": "Negociación salarial",
  "Sales": "Ventas",
  "Sales Closing": "Cierre de ventas",
  "Sales Enablement": "Habilitación de ventas",
  "Sales Pipeline": "Pipeline de ventas",
  "Sales Prospecting": "Prospección de ventas",
  "Salesforce": "Salesforce",
  "Sandwich Making": "Elaboración de sándwiches",
  "Satellite Systems": "Sistemas satelitales",
  "Satellite Technology": "Tecnología satelital",
  "Sauces & Dressings": "Salsas y aderezos",
  "Saving Money": "Ahorro de dinero",
  "Saying No": "Aprender a decir no",
  "Scala": "Scala",
  "Scheduling": "Programación de horarios",
  "Scholarship Writing": "Redacción de solicitudes de becas",
  "Scholarships": "Becas",
  "Science Fair": "Feria de ciencias",
  "Scientific Writing": "Escritura científica",
  "Scrapbooking": "Scrapbooking",
  "Scratch Programming": "Programación en Scratch",
  "Screen Printing": "Serigrafía",
  "Screenplay Writing": "Escritura de guiones",
  "Screenwriting": "Guionismo",
  "Scrum": "Scrum",
  "Scuba Diving": "Buceo",
  "Sculpture": "Escultura",
  "Seafood Cooking": "Cocina de mariscos",
  "Security Auditing": "Auditoría de seguridad",
  "Seismology": "Sismología",
  "Self-Awareness": "Autoconciencia",
  "Self-Compassion": "Autocompasión",
  "Self-Confidence": "Autoconfianza",
  "Self-Directed Learning": "Aprendizaje autodirigido",
  "Self-Discipline": "Autodisciplina",
  "Self-Esteem": "Autoestima",
  "Self-Improvement": "Superación personal",
  "Senior Fitness": "Fitness para adultos mayores",
  "Senior Living": "Vida para adultos mayores",
  "Sensory Play": "Juego sensorial",
  "Serverless Architecture": "Arquitectura sin servidor",
  "Set Design": "Diseño de escenografía",
  "Sewing": "Costura",
  "Sexual Health": "Salud sexual",
  "Shareholder Relations": "Relaciones con accionistas",
  "Shopify": "Shopify",
  "Short-Form Video": "Video corto",
  "Side Hustles": "Negocios paralelos",
  "Single Parenting": "Crianza monoparental",
  "Site Reliability": "Fiabilidad del sitio",
  "Six Sigma": "Seis Sigma",
  "Skateboarding": "Skateboard",
  "Sketch Design": "Diseño de bocetos",
  "Sketching": "Bocetos",
  "Skiing": "Esquí",
  "Skill Building": "Desarrollo de habilidades",
  "Skin Cancer": "Cáncer de piel",
  "Skincare Routine": "Rutina de cuidado de la piel",
  "Sleep": "Sueño",
  "Sleep Apps": "Apps de sueño",
  "Sleep Hygiene": "Higiene del sueño",
  "Sleep Optimization": "Optimización del sueño",
  "Slow Cooker": "Olla de cocción lenta",
  "Slow Cooking": "Cocción lenta",
  "Slow Living": "Vida pausada",
  "Small Business": "Pequeña empresa",
  "Small Claims": "Reclamos menores",
  "Small Talk": "Conversación casual",
  "Smart Cities": "Ciudades inteligentes",
  "Smart Contracts": "Contratos inteligentes",
  "Smart Home": "Hogar inteligente",
  "Smoking Cessation": "Dejar de fumar",
  "Smoothie Recipes": "Recetas de batidos",
  "Snorkeling": "Snorkel",
  "Snowboarding": "Snowboard",
  "Snowflake": "Snowflake",
  "Soap Making": "Elaboración de jabón",
  "Soccer": "Fútbol soccer",
  "Social": "Social",
  "Social Anxiety": "Ansiedad social",
  "Social Enterprise": "Empresa social",
  "Social Justice": "Justicia social",
  "Social Media Ads": "Anuncios en redes sociales",
  "Social Media Posts": "Publicaciones en redes sociales",
  "Social Skills": "Habilidades sociales",
  "Social-Emotional Learning": "Aprendizaje socioemocional",
  "Sociology": "Sociología",
  "Software Architecture": "Arquitectura de software",
  "Software Estimation": "Estimación de software",
  "Soil Conservation": "Conservación del suelo",
  "Soil Science": "Ciencia del suelo",
  "Solar Energy": "Energía solar",
  "Solar Power": "Energía solar fotovoltaica",
  "Solidity": "Solidity",
  "Solo Travel": "Viaje solo",
  "Song Lyrics": "Letras de canciones",
  "Songwriting": "Composición de canciones",
  "Sound Design": "Diseño de sonido",
  "Soup Recipes": "Recetas de sopas",
  "Sourdough": "Masa madre",
  "Sous Vide": "Sous vide",
  "South America Travel": "Viajes por Sudamérica",
  "Space Design": "Diseño espacial",
  "Space Exploration": "Exploración espacial",
  "Space Mining": "Minería espacial",
  "Space Science": "Ciencia espacial",
  "Space Tourism": "Turismo espacial",
  "Spanish Learning": "Aprendizaje de español",
  "Spatial Computing": "Computación espacial",
  "Special Education": "Educación especial",
  "Speech Writing": "Redacción de discursos",
  "Speed Learning": "Aprendizaje acelerado",
  "Speed Reading": "Lectura rápida",
  "Speed Running": "Speedrunning",
  "Spelling & Vocabulary": "Ortografía y vocabulario",
  "Spice Blends": "Mezclas de especias",
  "Spiritual Travel": "Viaje espiritual",
  "Spirituality": "Espiritualidad",
  "Sports Analytics": "Analítica deportiva",
  "Sports Injuries": "Lesiones deportivas",
  "Sports Medicine": "Medicina deportiva",
  "Sports Nutrition": "Nutrición deportiva",
  "Sports Psychology": "Psicología deportiva",
  "Spreadsheets": "Hojas de cálculo",
  "Stable Diffusion": "Stable Diffusion",
  "Stakeholder Management": "Gestión de partes interesadas",
  "Stamp Collecting": "Filatelia",
  "Standing Desk": "Escritorio de pie",
  "Startup": "Startup",
  "Startup Growth": "Crecimiento de startup",
  "Startup Strategy": "Estrategia de startup",
  "Statistics": "Estadística",
  "Steak Cooking": "Cocción de filetes",
  "Stock Market": "Bolsa de valores",
  "Stock Trading": "Trading de acciones",
  "Stoicism": "Estoicismo",
  "Storytelling": "Narrativa",
  "Strategic Planning": "Planificación estratégica",
  "Street Art": "Arte urbano",
  "Strength Training": "Entrenamiento de fuerza",
  "Stress Management": "Manejo del estrés",
  "Stress Relief": "Alivio del estrés",
  "Stroke Recovery": "Recuperación de accidente cerebrovascular",
  "Structural Engineering": "Ingeniería estructural",
  "Student Loans": "Préstamos estudiantiles",
  "Studio Recording": "Grabación en estudio",
  "Study Abroad": "Estudio en el extranjero",
  "Study Notes": "Notas de estudio",
  "Study Skills": "Habilidades de estudio",
  "Studying": "Estudio",
  "Subscription Business": "Negocio de suscripción",
  "Succulents": "Suculentas",
  "Sudoku": "Sudoku",
  "Sugar Addiction": "Adicción al azúcar",
  "Supplements": "Suplementos",
  "Supply Chain": "Cadena de suministro",
  "Support": "Soporte",
  "Surfing": "Surf",
  "Surgery Recovery": "Recuperación quirúrgica",
  "Survival Skills": "Habilidades de supervivencia",
  "Sushi Making": "Elaboración de sushi",
  "Sustainability": "Sostenibilidad",
  "Sustainable Agriculture": "Agricultura sostenible",
  "Sustainable Design": "Diseño sostenible",
  "Sustainable Fashion": "Moda sostenible",
  "Sustainable Fashion Design": "Diseño de moda sostenible",
  "Sustainable Health": "Salud sostenible",
  "Sustainable Living": "Vida sostenible",
  "Svelte": "Svelte",
  "Swift": "Swift",
  "Swift Development": "Desarrollo en Swift",
  "Swimming": "Natación",
  "Synthetic Biology": "Biología sintética",
  "System Design": "Diseño de sistemas",
  "Systems Thinking": "Pensamiento sistémico",
  "TOEFL Prep": "Preparación del TOEFL",
  "TRX Training": "Entrenamiento TRX",
  "TV Show Analysis": "Análisis de series de TV",
  "Table Tennis": "Tenis de mesa",
  "Tableau": "Tableau",
  "Tabletop RPGs": "RPG de mesa",
  "Taekwondo": "Taekwondo",
  "Tai Chi": "Tai Chi",
  "Tailoring": "Sastrería",
  "Talent Management": "Gestión del talento",
  "Tattoo Art": "Arte del tatuaje",
  "Tax Law": "Derecho fiscal",
  "Tax Planning": "Planificación fiscal",
  "Tax Strategy": "Estrategia fiscal",
  "Taxes": "Impuestos",
  "Tea Brewing": "Preparación de té",
  "Teacher Training": "Formación docente",
  "Teaching": "Enseñanza",
  "Teaching Skills": "Habilidades docentes",
  "Team Building": "Cohesión de equipo",
  "Team Leadership": "Liderazgo de equipo",
  "Team Management": "Gestión de equipos",
  "Tech Support": "Soporte técnico",
  "Technical SEO": "SEO técnico",
  "Technical Sales": "Ventas técnicas",
  "Technical Writing": "Escritura técnica",
  "Teen Parenting": "Crianza de adolescentes",
  "Telecommunications": "Telecomunicaciones",
  "Telemedicine": "Telemedicina",
  "Tenant Rights": "Derechos del inquilino",
  "Tennis": "Tenis",
  "TensorFlow": "TensorFlow",
  "Terraform": "Terraform",
  "Terrariums": "Terrarios",
  "Test Prep": "Preparación de exámenes",
  "Test-Driven Development": "Desarrollo guiado por pruebas",
  "Testimonial Requests": "Solicitudes de testimonios",
  "Textile Design": "Diseño textil",
  "Thai Cuisine": "Cocina tailandesa",
  "Thank You Messages": "Mensajes de agradecimiento",
  "Theme Parks": "Parques temáticos",
  "Therapy & Counseling": "Terapia y consejería",
  "Thermodynamics": "Termodinámica",
  "Thesis Writing": "Escritura de tesis",
  "Thought Leadership": "Liderazgo de pensamiento",
  "Thrift Fashion": "Moda de segunda mano",
  "Thrifting": "Compra de segunda mano",
  "Thyroid Health": "Salud de la tiroides",
  "Tidal Energy": "Energía de las mareas",
  "TikTok Marketing": "Marketing en TikTok",
  "Time Blocking": "Bloques de tiempo",
  "Time Management": "Gestión del tiempo",
  "Time Zones": "Zonas horarias",
  "Tiny House": "Casa pequeña",
  "Toddler Activities": "Actividades para niños pequeños",
  "Toddler Care": "Cuidado de niños pequeños",
  "Tokenomics": "Tokenómica",
  "Tour Guide Skills": "Habilidades de guía turístico",
  "Toxicology": "Toxicología",
  "Track & Field": "Atletismo",
  "Trade Compliance": "Cumplimiento comercial",
  "Trade Law": "Derecho comercial",
  "Trademark Law": "Derecho de marcas",
  "Traditional Chinese Medicine": "Medicina tradicional china",
  "Trail Running": "Running en senderos",
  "Translation": "Traducción",
  "Transportation Engineering": "Ingeniería de transporte",
  "Trauma Recovery": "Recuperación del trauma",
  "Travel": "Viajes",
  "Travel Hacking": "Travel hacking",
  "Travel Insurance": "Seguro de viaje",
  "Travel Photography": "Fotografía de viajes",
  "Travel Planning": "Planificación de viajes",
  "Travel Safety": "Seguridad en viajes",
  "Travel Writing": "Escritura de viajes",
  "Traveling with Kids": "Viajes con niños",
  "Traveling with Pets": "Viajes con mascotas",
  "Treadmill Training": "Entrenamiento en cinta de correr",
  "Treasury Management": "Gestión de tesorería",
  "Triathlon": "Triatlón",
  "Triathlon Training": "Entrenamiento de triatlón",
  "Trust Building": "Construcción de confianza",
  "Tutoring": "Tutoría",
  "Twitter/X Strategy": "Estrategia de Twitter/X",
  "TypeScript": "TypeScript",
  "TypeScript Advanced": "TypeScript avanzado",
  "Typography": "Tipografía",
  "UI Animation": "Animación de UI",
  "UI Design": "Diseño de UI",
  "UX Design": "Diseño de UX",
  "Unity": "Unity",
  "Unity Development": "Desarrollo en Unity",
  "University Life": "Vida universitaria",
  "Unreal Engine": "Unreal Engine",
  "Upcycling": "Upcycling",
  "Urban Exploration": "Exploración urbana",
  "Urban Farming": "Agricultura urbana",
  "Urban Sketching": "Dibujo urbano",
  "Usability Testing": "Pruebas de usabilidad",
  "User Research": "Investigación de usuarios",
  "VFX": "Efectos visuales",
  "VR Development": "Desarrollo de RV",
  "Vaccination": "Vacunación",
  "Valuation Methods": "Métodos de valoración",
  "Value Chain Analysis": "Análisis de la cadena de valor",
  "Values & Ethics": "Valores y ética",
  "Van Life": "Vida en furgoneta",
  "Vegan Cooking": "Cocina vegana",
  "Vegan Nutrition": "Nutrición vegana",
  "Vegetarian Cooking": "Cocina vegetariana",
  "Vendor Management": "Gestión de proveedores",
  "Venture Capital": "Capital de riesgo",
  "Vertical Farming": "Agricultura vertical",
  "Veterinary Care": "Cuidado veterinario",
  "Video": "Video",
  "Video Editing": "Edición de video",
  "Video Scripts": "Guiones de video",
  "Vietnamese Cuisine": "Cocina vietnamita",
  "Vintage Collecting": "Colección vintage",
  "Viral Marketing": "Marketing viral",
  "Virology": "Virología",
  "Virtual Meetings": "Reuniones virtuales",
  "Virtual Reality": "Realidad virtual",
  "Virtual Reality Fitness": "Fitness en realidad virtual",
  "Virtual Teams": "Equipos virtuales",
  "Visual Arts": "Artes visuales",
  "Visualization": "Visualización",
  "Vitamin Deficiency": "Deficiencia de vitaminas",
  "Vocabulary Building": "Desarrollo de vocabulario",
  "Voice Acting": "Doblaje",
  "Voiceover": "Voz en off",
  "Volcanology": "Vulcanología",
  "Volleyball": "Voleibol",
  "Volunteering": "Voluntariado",
  "Volunteering Abroad": "Voluntariado en el extranjero",
  "Voluntourism": "Volunturismo",
  "Voting Rights": "Derecho al voto",
  "Vue.js": "Vue.js",
  "Water Polo": "Waterpolo",
  "Water Technology": "Tecnología del agua",
  "Water Treatment": "Tratamiento del agua",
  "Watercolor": "Acuarela",
  "Wealth Management": "Gestión de patrimonio",
  "Wearable Tech": "Tecnología wearable",
  "Web Design": "Diseño web",
  "Web Development": "Desarrollo web",
  "Web3": "Web3",
  "Web3 Development": "Desarrollo Web3",
  "Web3 Security": "Seguridad Web3",
  "WebAssembly": "WebAssembly",
  "WebGL": "WebGL",
  "WebRTC": "WebRTC",
  "Webinar Marketing": "Marketing de webinars",
  "Wedding Budget": "Presupuesto de boda",
  "Wedding Photography": "Fotografía de bodas",
  "Wedding Planning": "Planificación de bodas",
  "Weekend Planning": "Planificación del fin de semana",
  "Weight Loss": "Pérdida de peso",
  "Weight Training": "Entrenamiento con pesas",
  "Weightlifting": "Halterofilia",
  "Welding": "Soldadura",
  "Wellness Routine": "Rutina de bienestar",
  "White Label": "Marca blanca",
  "Wholesale Business": "Negocio mayorista",
  "Wildlife Biology": "Biología de vida silvestre",
  "Wildlife Protection": "Protección de vida silvestre",
  "Willpower": "Fuerza de voluntad",
  "Wind Energy": "Energía eólica",
  "Wind Turbines": "Aerogeneradores",
  "Wine": "Vino",
  "Wine Making": "Elaboración de vino",
  "Wine Pairing": "Maridaje de vinos",
  "Wireshark": "Wireshark",
  "Women's Wellness": "Bienestar femenino",
  "Woodcraft": "Trabajo en madera",
  "Woodworking": "Carpintería",
  "WordPress": "WordPress",
  "WordPress Plugins": "Plugins de WordPress",
  "Work Visa": "Visa de trabajo",
  "Work-Life Balance": "Equilibrio trabajo-vida",
  "Workers' Compensation": "Compensación laboral",
  "Workplace Communication": "Comunicación en el trabajo",
  "Workplace Conflict": "Conflicto laboral",
  "Workplace Wellness": "Bienestar laboral",
  "World Religions": "Religiones del mundo",
  "Wound Care": "Cuidado de heridas",
  "Wrestling": "Lucha libre",
  "Writing": "Escritura",
  "Writing Emails": "Redacción de correos",
  "Writing Workshop": "Taller de escritura",
  "Xamarin": "Xamarin",
  "Yoga": "Yoga",
  "Yoga Therapy": "Terapia de yoga",
  "Yoga for Athletes": "Yoga para atletas",
  "YouTube": "YouTube",
  "YouTube SEO": "SEO en YouTube",
  "Zero Waste": "Cero residuos",
  "Zero-Knowledge Proofs": "Pruebas de conocimiento cero",
  "Zodiac": "Zodiaco",
  "Zoology": "Zoología",
  "Zumba": "Zumba",
  "jQuery": "jQuery"
};
