/* PromptRunic — cat-zh.js: Chinese category name map */
window.PROMPTS_CAT_ZH = {
  "3D Modeling": "3D建模",
  "3D Printing": "3D打印",
  "3D Printing Art": "3D打印艺术",
  "A/B Testing": "A/B测试",
  "AI & Machine Learning": "AI与机器学习",
  "AI Agents": "AI代理",
  "AI Art Tools": "AI艺术工具",
  "AI Basics": "AI基础",
  "AI Chatbots": "AI聊天机器人",
  "AI Code Assistants": "AI代码助手",
  "AI Ethics": "AI伦理",
  "AI Music": "AI音乐",
  "AI Video": "AI视频",
  "AI Writing Tools": "AI写作工具",
  "AI for Kids": "儿童AI",
  "APIs": "API接口",
  "AR Development": "AR开发",
  "ASP.NET": "ASP.NET",
  "AWS Certification": "AWS认证",
  "Abstract Art": "抽象艺术",
  "Academic Coaching": "学术辅导",
  "Academic Writing": "学术写作",
  "Accessibility": "无障碍访问",
  "Account Management": "账户管理",
  "Account-Based Marketing": "基于账户的营销",
  "Acrylic Painting": "丙烯画",
  "Active Listening": "积极倾听",
  "Actuarial Science": "精算科学",
  "Acupressure": "穴位按压",
  "Adaptability": "适应能力",
  "Addiction Recovery": "成瘾康复",
  "Administrative Law": "行政法",
  "Adoption": "收养",
  "Adult Education": "成人教育",
  "Aerospace Engineering": "航空航天工程",
  "Affiliate Marketing": "联盟营销",
  "Affiliate Strategy": "联盟策略",
  "Africa Travel": "非洲旅行",
  "African Cuisine": "非洲美食",
  "Agency Building": "代理建设",
  "Agile": "敏捷",
  "Agile Management": "敏捷管理",
  "Aging Gracefully": "优雅老去",
  "Aging Parents": "年迈父母",
  "Aging Well": "健康老龄化",
  "AgriTech": "农业科技",
  "Agricultural Science": "农业科学",
  "Air Fryer Cooking": "空气炸锅烹饪",
  "Air Pollution": "空气污染",
  "Air Quality": "空气质量",
  "Air Travel": "航空旅行",
  "Algebra": "代数",
  "Algorithm Design": "算法设计",
  "Allergy Management": "过敏管理",
  "Alternative Medicine": "替代医学",
  "Alzheimer's Care": "阿尔茨海默症护理",
  "Amazon Selling": "亚马逊销售",
  "Analytical Chemistry": "分析化学",
  "Ancient History": "古代历史",
  "Android Development": "安卓开发",
  "Angel Investing": "天使投资",
  "Anger Management": "愤怒管理",
  "Angular": "Angular",
  "Animation": "动画",
  "Animation 2D": "2D动画",
  "Animation 3D": "3D动画",
  "Animation for Kids": "儿童动画",
  "Anti-Aging": "抗衰老",
  "Antique Restoration": "古董修复",
  "Antiques": "古董",
  "Anxiety": "焦虑",
  "Anxiety Management": "焦虑管理",
  "Apartment Living": "公寓生活",
  "Apologizing": "道歉",
  "Apology Letters": "道歉信",
  "App Monetization": "应用变现",
  "Appetizers": "开胃菜",
  "Aquaponics": "鱼菜共生",
  "Aquarium": "水族箱",
  "Aquarium Fish": "观赏鱼",
  "Aquatic Therapy": "水疗",
  "Archery": "射箭",
  "Architecture Design": "建筑设计",
  "Arduino": "Arduino",
  "Aromatherapy": "芳香疗法",
  "Art Direction": "艺术指导",
  "Art Galleries": "艺术画廊",
  "Art History": "艺术史",
  "Art Portfolio": "艺术作品集",
  "Art for Seniors": "老年人艺术",
  "Asia Travel": "亚洲旅行",
  "Asian Cuisine": "亚洲美食",
  "Asset Management": "资产管理",
  "Astrology": "占星术",
  "Astronomy": "天文学",
  "Astrophotography": "天文摄影",
  "Astrophysics": "天体物理学",
  "Asylum Law": "庇护法",
  "Asynchronous Work": "异步工作",
  "Atmospheric Science": "大气科学",
  "Audio Engineering": "音频工程",
  "Audiobook Narration": "有声书旁白",
  "Augmented Reality": "增强现实",
  "AutoCAD": "AutoCAD",
  "Autoimmune Disorders": "自身免疫疾病",
  "Automation": "自动化",
  "Automation Testing": "自动化测试",
  "Autonomous Driving": "自动驾驶",
  "Autonomous Vehicles": "自动驾驶汽车",
  "Ayurveda": "阿育吠陀",
  "Azure": "Azure",
  "B2B Sales": "B2B销售",
  "B2C Marketing": "B2C营销",
  "BBQ & Grilling": "烧烤",
  "BMX": "BMX小轮车",
  "Baby Care": "婴儿护理",
  "Back Pain": "背痛",
  "Backend Development": "后端开发",
  "Backpacking": "背包旅行",
  "Badminton": "羽毛球",
  "Baking": "烘焙",
  "Balcony Gardening": "阳台园艺",
  "Bankruptcy Law": "破产法",
  "Barre Workout": "把杆健身",
  "Baseball": "棒球",
  "Basketball": "篮球",
  "Battery Technology": "电池技术",
  "Beach Destinations": "海滩度假",
  "Beat Making": "节拍制作",
  "Beekeeping": "养蜂",
  "Beer Brewing": "啤酒酿造",
  "Behavioral Economics": "行为经济学",
  "Behavioral Health": "行为健康",
  "Big Data Analytics": "大数据分析",
  "Biochemistry": "生物化学",
  "Biodiversity": "生物多样性",
  "Bioinformatics": "生物信息学",
  "Biology": "生物学",
  "Biomechanics": "生物力学",
  "Bioprinting": "生物打印",
  "Biotech": "生物技术",
  "Birdwatching": "观鸟",
  "Blender": "Blender",
  "Blockchain": "区块链",
  "Blockchain Dev": "区块链开发",
  "Blog Writing": "博客写作",
  "Blogging": "博客",
  "Blood Pressure": "血压",
  "Board Game Design": "桌游设计",
  "Board Games": "桌游",
  "Board Governance": "董事会治理",
  "Body Language": "肢体语言",
  "Bodybuilding": "健美",
  "Bond Markets": "债券市场",
  "Bone Health": "骨骼健康",
  "Bonsai": "盆景",
  "Book Club": "读书会",
  "Book Cover Design": "书籍封面设计",
  "Book Illustration": "书籍插画",
  "Bootstrap": "Bootstrap",
  "Bootstrapping": "自举创业",
  "Boxing": "拳击",
  "Brain Health": "大脑健康",
  "Brain Training": "大脑训练",
  "Brainstorming": "头脑风暴",
  "Brand Guidelines": "品牌指南",
  "Brand Identity": "品牌标识",
  "Brand Strategy": "品牌战略",
  "Branding": "品牌建设",
  "Brazilian Cuisine": "巴西美食",
  "Bread Making": "面包制作",
  "Breakfast Recipes": "早餐食谱",
  "Breathing Exercises": "呼吸练习",
  "Breathwork": "呼吸法",
  "Budget Airlines": "廉价航空",
  "Budget Travel": "预算旅行",
  "Budgeting": "预算管理",
  "Bullet Journal": "子弹笔记",
  "Burnout": "倦怠",
  "Bushcraft": "野外生存技能",
  "Business": "商业",
  "Business Analytics": "商业分析",
  "Business Continuity": "业务连续性",
  "Business Ideas": "商业创意",
  "Business Intelligence": "商业智能",
  "Business Process Automation": "业务流程自动化",
  "Business Proposals": "商业提案",
  "Business Strategy": "商业战略",
  "Business Valuation": "企业估值",
  "C Programming": "C语言编程",
  "C++ Development": "C++开发",
  "CAD Design": "CAD设计",
  "CMS Development": "CMS开发",
  "CNC Machining": "数控加工",
  "CSS Advanced": "CSS高级",
  "Calculus": "微积分",
  "Calisthenics": "徒手健身",
  "Calligraphy": "书法",
  "Camping": "露营",
  "Camping Skills": "露营技能",
  "Campus Life": "校园生活",
  "Cancer Prevention": "癌症预防",
  "Candle Making": "蜡烛制作",
  "Canning & Preserving": "罐装与保存",
  "Capital Markets": "资本市场",
  "Car Buying": "购车",
  "Car Maintenance": "汽车保养",
  "Carbon Capture": "碳捕获",
  "Carbon Footprint": "碳足迹",
  "Carbon Offsets": "碳抵消",
  "Card Games": "卡牌游戏",
  "Card Making": "贺卡制作",
  "Cardio Fitness": "有氧健身",
  "Career": "职业",
  "Career Change": "职业转型",
  "Career Growth": "职业发展",
  "Career Pivot": "职业转向",
  "Career Portfolios": "职业作品集",
  "Caribbean Cuisine": "加勒比美食",
  "Cartography": "制图学",
  "Cassandra": "Cassandra",
  "Cats": "猫咪",
  "Celiac Disease": "乳糜泻",
  "Cell Biology": "细胞生物学",
  "Ceramics": "陶瓷",
  "Change Management": "变革管理",
  "Channel Sales": "渠道销售",
  "Character Design": "角色设计",
  "Charisma": "魅力",
  "Charity & Volunteering": "慈善与志愿服务",
  "ChatGPT": "ChatGPT",
  "ChatGPT Prompts": "ChatGPT提示词",
  "Cheerleading": "啦啦队",
  "Cheese Making": "奶酪制作",
  "Chemical Engineering": "化学工程",
  "Chemistry": "化学",
  "Chess": "国际象棋",
  "Child Discipline": "儿童管教",
  "Chinese Cuisine": "中餐",
  "Chiropractic Care": "脊医护理",
  "Chocolate Making": "巧克力制作",
  "Cholesterol Management": "胆固醇管理",
  "Chrome Extensions": "Chrome扩展",
  "Chronic Fatigue": "慢性疲劳",
  "Chronic Illness": "慢性病",
  "Churn Reduction": "流失率降低",
  "Cinematography": "电影摄影",
  "Circular Economy": "循环经济",
  "Civic Engagement": "公民参与",
  "Civic Tech": "公民科技",
  "Civil Engineering": "土木工程",
  "Civil Law": "民法",
  "Civil Rights": "公民权利",
  "Classical Music": "古典音乐",
  "Claude AI": "Claude AI",
  "Clean Energy": "清洁能源",
  "Cleaning": "清洁",
  "Cleaning & Organizing": "清洁与整理",
  "Climate Action": "气候行动",
  "Climate Adaptation": "气候适应",
  "Climate Change": "气候变化",
  "Climate Policy": "气候政策",
  "Climate Science": "气候科学",
  "Climatology": "气候学",
  "Clothing Care": "衣物护理",
  "Cloud Architecture": "云架构",
  "Cloud Computing": "云计算",
  "Cloud Security": "云安全",
  "Co-Housing": "共享住宅",
  "Co-Parenting": "共同抚养",
  "Coaching": "教练",
  "Coaching Skills": "教练技能",
  "Cocktail Recipes": "鸡尾酒配方",
  "Code Review": "代码审查",
  "Coding": "编程",
  "Coding for Kids": "儿童编程",
  "Coffee & Tea": "咖啡与茶",
  "Coffee Brewing": "咖啡冲泡",
  "Cognitive Behavioral Therapy": "认知行为疗法",
  "Cold & Flu": "感冒与流感",
  "Cold Email": "冷邮件",
  "Cold Outreach": "冷拓展",
  "Collecting": "收藏",
  "College Admissions": "大学录取",
  "College Applications": "大学申请",
  "College Essays": "大学论文",
  "Color Grading": "调色",
  "Color Theory": "色彩理论",
  "Comfort Zone": "舒适区",
  "Comic Art": "漫画艺术",
  "Commodities": "大宗商品",
  "Commodities Trading": "大宗商品交易",
  "Communication Skills": "沟通技能",
  "Community Building": "社区建设",
  "Community Organizing": "社区组织",
  "Comparative Anatomy": "比较解剖学",
  "Comparative Literature": "比较文学",
  "Competitive Analysis": "竞争分析",
  "Competitive Gaming": "竞技游戏",
  "Compiler Design": "编译器设计",
  "Compliance": "合规",
  "Composting": "堆肥",
  "Computer Graphics": "计算机图形学",
  "Computer Networking": "计算机网络",
  "Computer Vision": "计算机视觉",
  "Concept Art": "概念艺术",
  "Condensed Matter Physics": "凝聚态物理",
  "Conflict Resolution": "冲突解决",
  "Conservation": "自然保护",
  "Conservation Biology": "保护生物学",
  "Consignment Business": "寄售业务",
  "Constitutional Law": "宪法",
  "Consulting": "咨询",
  "Consulting Skills": "咨询技能",
  "Containers": "容器",
  "Content Design": "内容设计",
  "Content Marketing": "内容营销",
  "Content Strategy": "内容策略",
  "Content Writing": "内容写作",
  "Contract Law": "合同法",
  "Convention Planning": "大会策划",
  "Conversion Optimization": "转化优化",
  "Cooking": "烹饪",
  "Cooking on a Budget": "预算烹饪",
  "Copywriting": "文案写作",
  "Corporate Finance": "公司财务",
  "Corporate Law": "公司法",
  "Cosplay": "角色扮演",
  "Cost Accounting": "成本会计",
  "Couples Therapy": "夫妻治疗",
  "Cover Letters": "求职信",
  "Coworking": "共享办公",
  "Crafts": "手工艺",
  "Creative": "创意",
  "Creative Coding": "创意编程",
  "Creative Direction": "创意指导",
  "Creative Nonfiction": "创意非虚构",
  "Creative Thinking": "创意思维",
  "Creative Writing": "创意写作",
  "Creativity Boost": "创造力提升",
  "Credit Analysis": "信用分析",
  "Credit Score": "信用评分",
  "Cricket": "板球",
  "Criminal Justice": "刑事司法",
  "Criminal Law": "刑法",
  "Crisis Communication": "危机沟通",
  "Crisis Management": "危机管理",
  "Critical Thinking": "批判性思维",
  "Cross-Cultural Business": "跨文化商业",
  "CrossFit": "交叉健身",
  "Crossword": "填字游戏",
  "Cruise Planning": "邮轮规划",
  "Cryogenics": "低温学",
  "Crypto Trading": "加密货币交易",
  "Cryptocurrency": "加密货币",
  "Crystallography": "结晶学",
  "Cultural Adaptation": "文化适应",
  "Cultural Exchange": "文化交流",
  "Cultural Heritage": "文化遗产",
  "Cultural Intelligence": "文化智力",
  "Cultural Travel": "文化旅行",
  "Cupcake Decorating": "纸杯蛋糕装饰",
  "Curriculum Design": "课程设计",
  "Customer Experience": "客户体验",
  "Customer Feedback": "客户反馈",
  "Customer Journey": "客户旅程",
  "Customer Retention": "客户留存",
  "Customer Success": "客户成功",
  "Customer Success Strategy": "客户成功策略",
  "Customs & Traditions": "习俗与传统",
  "Cyber Law": "网络法",
  "Cyber Threats": "网络威胁",
  "Cybersecurity": "网络安全",
  "Cycling": "骑行",
  "Cypress Testing": "Cypress测试",
  "DALL-E": "DALL-E",
  "DAO Governance": "DAO治理",
  "DIY Home Decor": "DIY家居装饰",
  "DIY Home Repair": "DIY家居维修",
  "DIY Repairs": "DIY修理",
  "DJ": "DJ打碟",
  "DJing": "DJ打碟",
  "Dairy Science": "乳品科学",
  "Dance": "舞蹈",
  "Data & Analytics": "数据与分析",
  "Data Architecture": "数据架构",
  "Data Engineering": "数据工程",
  "Data Governance": "数据治理",
  "Data Lakes": "数据湖",
  "Data Modeling": "数据建模",
  "Data Pipelines": "数据管道",
  "Data Privacy": "数据隐私",
  "Data Quality": "数据质量",
  "Data Science": "数据科学",
  "Data Visualization": "数据可视化",
  "Data Warehousing": "数据仓库",
  "Database Design": "数据库设计",
  "Databases": "数据库",
  "Databricks": "Databricks",
  "Date Ideas": "约会创意",
  "Dating": "约会",
  "DeFi": "去中心化金融",
  "DeFi Protocols": "DeFi协议",
  "Deal Negotiation": "交易谈判",
  "Debate Skills": "辩论技能",
  "Debate for Teens": "青少年辩论",
  "Debt Payoff": "还债",
  "Debt Recovery": "债务回收",
  "Debugging": "调试",
  "Decathlon": "十项全能",
  "Decision Making": "决策",
  "Deep Learning": "深度学习",
  "Deep Work": "深度工作",
  "Deforestation": "森林砍伐",
  "Delegation": "授权",
  "Demand Generation": "需求生成",
  "Dental Care": "牙科护理",
  "Dental Health": "牙齿健康",
  "Depression Support": "抑郁支持",
  "Design Patterns": "设计模式",
  "Design Thinking": "设计思维",
  "Desserts": "甜点",
  "Detoxification": "排毒",
  "DevOps": "DevOps",
  "Diabetes Management": "糖尿病管理",
  "Diet & Nutrition": "饮食与营养",
  "Diet Planning": "饮食计划",
  "Digestive Health": "消化健康",
  "Digital Art": "数字艺术",
  "Digital Banking": "数字银行",
  "Digital Detox": "数字排毒",
  "Digital Forensics": "数字取证",
  "Digital Illustration": "数字插画",
  "Digital Marketing": "数字营销",
  "Digital Nomad": "数字游民",
  "Digital Privacy": "数字隐私",
  "Digital Scrapbooking": "数字剪贴簿",
  "Digital Sculpting": "数字雕塑",
  "Digital Transformation": "数字化转型",
  "Digital Twins": "数字孪生",
  "Dinner Recipes": "晚餐食谱",
  "Disability Support": "残障支持",
  "Disaster Recovery": "灾难恢复",
  "Dispute Resolution": "争议解决",
  "Distance Learning": "远程学习",
  "Distribution Strategy": "分销策略",
  "Diversity & Inclusion": "多元与包容",
  "Divorce Recovery": "离婚恢复",
  "Django": "Django",
  "Docker": "Docker",
  "Documentary Filmmaking": "纪录片制作",
  "Dog Training": "训犬",
  "Dogs": "狗狗",
  "Domain Modeling": "领域建模",
  "Drawing": "绘画",
  "Dream Interpretation": "解梦",
  "Drone Delivery": "无人机配送",
  "Drone Photography": "无人机摄影",
  "Drones": "无人机",
  "Dropshipping": "代发货",
  "Drug Interactions": "药物相互作用",
  "E-commerce": "电商",
  "E-commerce SEO": "电商SEO",
  "E-commerce Strategy": "电商策略",
  "E-learning Design": "电子学习设计",
  "ESG Investing": "ESG投资",
  "ESL Teaching": "ESL教学",
  "ETL Pipelines": "ETL管道",
  "Early Childhood Education": "幼儿教育",
  "Earth Science": "地球科学",
  "Eating Disorders": "饮食失调",
  "Eco-Friendly Products": "环保产品",
  "Eco-Tourism": "生态旅游",
  "Ecology": "生态学",
  "Economic Forecasting": "经济预测",
  "Economics": "经济学",
  "Ecotourism": "生态旅游",
  "EdTech": "教育科技",
  "Edge Computing": "边缘计算",
  "Editorial Design": "编辑设计",
  "Education": "教育",
  "Educational Psychology": "教育心理学",
  "Elasticsearch": "Elasticsearch",
  "Eldercare": "老人护理",
  "Elderly Care": "老年护理",
  "Election Law": "选举法",
  "Electric Vehicles": "电动汽车",
  "Electrical Engineering": "电气工程",
  "Electromagnetism": "电磁学",
  "Electron Apps": "Electron应用",
  "Electronics Repair": "电子维修",
  "Email": "邮件",
  "Email Automation": "邮件自动化",
  "Email Marketing": "邮件营销",
  "Email Writing": "邮件写作",
  "Embedded Systems": "嵌入式系统",
  "Emergency Medicine": "急诊医学",
  "Emergency Preparedness": "应急准备",
  "Emotion AI": "情感AI",
  "Emotional Intelligence": "情商",
  "Empathy": "同理心",
  "Employee Engagement": "员工敬业度",
  "Employee Onboarding": "员工入职",
  "Employee Training": "员工培训",
  "Employment Law": "劳动法",
  "Empty Nest": "空巢",
  "Endocrine Health": "内分泌健康",
  "Endocrinology": "内分泌学",
  "Energy Conservation": "节能",
  "Energy Engineering": "能源工程",
  "Energy Healing": "能量疗愈",
  "Energy Management": "能源管理",
  "Energy Saving": "节能",
  "English Grammar": "英语语法",
  "English Learning": "英语学习",
  "English Literature": "英国文学",
  "Enterprise Sales": "企业销售",
  "Entomology": "昆虫学",
  "Entrepreneurship": "创业",
  "Environmental Engineering": "环境工程",
  "Environmental Impact": "环境影响",
  "Environmental Law": "环境法",
  "Environmental Science": "环境科学",
  "Epidemiology": "流行病学",
  "Equestrian": "马术",
  "Equity Research": "股权研究",
  "Ergonomic Chair": "人体工学椅",
  "Ergonomics": "人体工学",
  "Escape Room Design": "密室设计",
  "Escape Room Solving": "密室解谜",
  "Escape Rooms": "密室逃脱",
  "Essay Writing": "论文写作",
  "Ethical Shopping": "道德购物",
  "Ethics": "伦理",
  "Etiquette": "礼仪",
  "Etsy Selling": "Etsy销售",
  "Europe Travel": "欧洲旅行",
  "Evening Routines": "晚间习惯",
  "Event Marketing": "活动营销",
  "Event Planning": "活动策划",
  "Evolutionary Biology": "进化生物学",
  "Exam Prep": "考试准备",
  "Executive Coaching": "高管教练",
  "Executive Leadership": "高管领导力",
  "Exergaming": "体感游戏",
  "Exotic Pets": "异宠",
  "Export Business": "出口业务",
  "Express.js": "Express.js",
  "Eye Health": "眼部健康",
  "Facebook Ads": "Facebook广告",
  "Fair Trade": "公平贸易",
  "Family Budget": "家庭预算",
  "Family Business": "家族企业",
  "Family Communication": "家庭沟通",
  "Family Law": "家庭法",
  "Family Therapy": "家庭治疗",
  "Fan Fiction": "同人小说",
  "Fantasy Sports": "梦幻体育",
  "Fashion Design": "时装设计",
  "Fashion Styling": "时尚造型",
  "Fasting": "断食",
  "Feedback Skills": "反馈技能",
  "Fencing": "击剑",
  "Feng Shui": "风水",
  "Fermentation": "发酵",
  "Festivals & Events": "节日与活动",
  "Fiction Writing": "小说写作",
  "Figma": "Figma",
  "Figure Skating": "花样滑冰",
  "Film Criticism": "电影评论",
  "Film Directing": "电影导演",
  "Film Editing": "电影剪辑",
  "Filmmaking": "电影制作",
  "FinTech": "金融科技",
  "Finance": "金融",
  "Financial Independence": "财务自由",
  "Financial Modeling": "财务建模",
  "Firebase": "Firebase",
  "First Aid": "急救",
  "Fishing": "钓鱼",
  "Fitness": "健身",
  "Fitness Over 50": "50岁以上健身",
  "Flask": "Flask",
  "Flexibility Training": "柔韧训练",
  "Floral Design": "花艺设计",
  "Fluid Dynamics": "流体力学",
  "Flutter": "Flutter",
  "Focus & Concentration": "专注力",
  "Food Safety": "食品安全",
  "Food Science": "食品科学",
  "Food Tourism": "美食旅游",
  "Football": "足球",
  "Foraging": "觅食",
  "Foreign Language Learning": "外语学习",
  "Forensic Science": "法医学",
  "Forex": "外汇",
  "Forgiveness": "宽恕",
  "Franchise Business": "加盟业务",
  "Franchising": "特许经营",
  "Freedom of Information": "信息自由",
  "Freelance Platforms": "自由职业平台",
  "Freelancing": "自由职业",
  "French Cuisine": "法国美食",
  "French Learning": "法语学习",
  "Friendship": "友谊",
  "Frontend Performance": "前端性能",
  "Functional Medicine": "功能医学",
  "Functional Programming": "函数式编程",
  "Fundraising": "筹款",
  "Furniture Design": "家具设计",
  "GIS Mapping": "GIS制图",
  "GTD Method": "GTD方法",
  "Game AI": "游戏AI",
  "Game Art": "游戏美术",
  "Game Design": "游戏设计",
  "Game Development": "游戏开发",
  "Game Marketing": "游戏营销",
  "Game Monetization": "游戏变现",
  "Game Narratives": "游戏叙事",
  "Game Streaming": "游戏直播",
  "Game UI Design": "游戏UI设计",
  "Gamification": "游戏化",
  "Gardening": "园艺",
  "Gender Equality": "性别平等",
  "Gene Editing": "基因编辑",
  "Gene Therapy": "基因治疗",
  "Genealogy": "家谱学",
  "Generative AI": "生成式AI",
  "Genetics": "遗传学",
  "Geocaching": "地理寻宝",
  "Geochemistry": "地球化学",
  "Geography": "地理学",
  "Geology": "地质学",
  "Geometry": "几何学",
  "Geophysics": "地球物理学",
  "German Learning": "德语学习",
  "Gift Ideas": "礼物创意",
  "Gift Suggestions": "礼物建议",
  "Gifted Education": "天才教育",
  "Git": "Git",
  "Glass Art": "玻璃艺术",
  "Global Supply Chain": "全球供应链",
  "Gluten-Free Cooking": "无麸质烹饪",
  "Go Programming": "Go编程",
  "Go-to-Market": "推向市场",
  "Goal Setting": "目标设定",
  "Golf": "高尔夫",
  "Google Ads": "Google广告",
  "Google Cloud": "Google云",
  "Google Workspace": "Google办公套件",
  "Graduate School": "研究生院",
  "Grant Writing": "基金申请写作",
  "GraphQL": "GraphQL",
  "Graphic Design": "平面设计",
  "Gratitude Practice": "感恩练习",
  "Greek Cuisine": "希腊美食",
  "Green Architecture": "绿色建筑",
  "Green Building": "绿色建筑",
  "Green Business": "绿色商业",
  "Green Energy": "绿色能源",
  "Green Living": "绿色生活",
  "Grief & Loss": "悲伤与失去",
  "Grooming": "仪容",
  "Growth Hacking": "增长黑客",
  "Growth Mindset": "成长型思维",
  "Guerrilla Marketing": "游击营销",
  "Guitar": "吉他",
  "Gut Health": "肠道健康",
  "Gymnastics": "体操",
  "HIIT": "高强度间歇训练",
  "HR": "人力资源",
  "HR Analytics": "HR分析",
  "Habit Stacking": "习惯叠加",
  "Habit Trackers": "习惯追踪",
  "Habitat Restoration": "栖息地恢复",
  "Habits": "习惯",
  "Hacking Ethics": "黑客伦理",
  "Hadoop": "Hadoop",
  "Hair Care": "护发",
  "Hair Loss": "脱发",
  "Ham Radio": "业余无线电",
  "Handball": "手球",
  "Happiness": "幸福",
  "Hardware Security": "硬件安全",
  "Haskell": "Haskell",
  "Headache Relief": "头痛缓解",
  "Health": "健康",
  "HealthTech": "健康科技",
  "Healthcare Law": "医疗法",
  "Healthy Eating": "健康饮食",
  "Healthy Snacks": "健康零食",
  "Hearing Health": "听力健康",
  "Heart Health": "心脏健康",
  "Hedge Funds": "对冲基金",
  "Herbal Medicine": "草药医学",
  "Herbalism": "草药学",
  "Heritage Sites": "遗产地",
  "Higher Education": "高等教育",
  "Hiking": "徒步",
  "Hiking Gear": "徒步装备",
  "Hiring": "招聘",
  "History": "历史",
  "Holistic Health": "整体健康",
  "Home": "家居",
  "Home Automation": "家居自动化",
  "Home Brewing": "家酿",
  "Home Buying": "购房",
  "Home Decoration": "家居装饰",
  "Home Finance": "家庭财务",
  "Home Healthcare": "家庭医疗",
  "Home Office Setup": "家庭办公",
  "Home Organization": "家居整理",
  "Home Renovation": "家装翻新",
  "Home Security": "家庭安全",
  "Home Selling": "卖房",
  "Homeopathy": "顺势疗法",
  "Homeschool Curriculum": "在家教育课程",
  "Homeschooling": "在家教育",
  "Homesteading": "自给自足生活",
  "Honeymoon Planning": "蜜月规划",
  "Hormone Health": "激素健康",
  "Horse Riding": "骑马",
  "Horticulture": "园艺学",
  "Hospice Care": "临终关怀",
  "Hospitality": "酒店业",
  "Hostel Travel": "青旅旅行",
  "Hotel Booking": "酒店预订",
  "Houseplants": "室内植物",
  "Human Resources": "人力资源",
  "Human Rights": "人权",
  "Humor & Wit": "幽默与机智",
  "Hunting": "狩猎",
  "Hydration": "补水",
  "Hydrogen Energy": "氢能",
  "Hydrology": "水文学",
  "Hydroponics": "水培",
  "Hypnotherapy": "催眠疗法",
  "IP Law": "知识产权法",
  "IPO": "IPO",
  "IPO Process": "IPO流程",
  "IQ Testing": "IQ测试",
  "IT Consulting": "IT咨询",
  "IT Infrastructure": "IT基础设施",
  "IT Service Management": "IT服务管理",
  "Ice Hockey": "冰球",
  "Identity Change": "身份转变",
  "Identity Development": "身份发展",
  "Illustration": "插画",
  "Image": "图像",
  "Immigration": "移民",
  "Immigration Law": "移民法",
  "Immune System": "免疫系统",
  "Immunology": "免疫学",
  "Import Business": "进口业务",
  "Imposter Syndrome": "冒名顶替综合征",
  "Incident Management": "事件管理",
  "Incident Response": "应急响应",
  "Index Funds": "指数基金",
  "Indian Cuisine": "印度美食",
  "Indie Hacking": "独立开发",
  "Indigenous Culture": "原住民文化",
  "Indoor Cycling": "室内骑行",
  "Indoor Plants": "室内植物",
  "Industrial Engineering": "工业工程",
  "Industry Conferences": "行业会议",
  "Infection Prevention": "感染预防",
  "Influencer Marketing": "网红营销",
  "Influencer Strategy": "网红策略",
  "Injury Recovery": "伤病恢复",
  "Inner Peace": "内心平静",
  "Innovation Management": "创新管理",
  "Insomnia": "失眠",
  "Instagram Growth": "Instagram增长",
  "Instant Pot": "电压力锅",
  "InsurTech": "保险科技",
  "Insurance": "保险",
  "Integrated Health": "整合健康",
  "Intellectual Property": "知识产权",
  "Intentional Living": "有意生活",
  "Interior Decorating": "室内装饰",
  "Interior Design": "室内设计",
  "Interior Styling": "室内造型",
  "Internal Audit": "内部审计",
  "International Law": "国际法",
  "International Trade": "国际贸易",
  "Internet Regulation": "互联网监管",
  "Interview Skills": "面试技能",
  "Inventory": "库存",
  "Inventory Management": "库存管理",
  "Investing": "投资",
  "Investment Banking": "投资银行",
  "Investor Relations": "投资者关系",
  "IoT": "物联网",
  "IoT Platforms": "物联网平台",
  "Italian Cuisine": "意大利美食",
  "Japanese Cuisine": "日本美食",
  "Japanese Learning": "日语学习",
  "Java Advanced": "Java高级",
  "JavaScript Advanced": "JavaScript高级",
  "Jenkins CI": "Jenkins CI",
  "Jewelry Design": "珠宝设计",
  "Job Interviews": "求职面试",
  "Job Search": "求职",
  "Joint Health": "关节健康",
  "Journaling": "日记",
  "Journaling Practice": "日记练习",
  "Journalism": "新闻学",
  "Joyful Living": "快乐生活",
  "Judicial Process": "司法程序",
  "Judo": "柔道",
  "Juggling": "杂耍",
  "K-12 STEM": "K-12 STEM",
  "KPI Design": "KPI设计",
  "Kafka": "Kafka",
  "Kali Linux": "Kali Linux",
  "Karate": "空手道",
  "Keto Recipes": "生酮食谱",
  "Kettlebell": "壶铃",
  "Key Account Management": "大客户管理",
  "Keyword Research": "关键词研究",
  "Kickboxing": "踢拳",
  "Kidney Health": "肾脏健康",
  "Kindness Practice": "善意练习",
  "Kinesiology": "运动学",
  "Knitting": "编织",
  "Knitting & Sewing": "编织与缝纫",
  "Korean Cuisine": "韩国美食",
  "Korean Learning": "韩语学习",
  "Kotlin": "Kotlin",
  "Kubernetes": "Kubernetes",
  "LEGO": "乐高",
  "LLM Fine-Tuning": "大模型微调",
  "Lab Work": "实验工作",
  "Lab-Grown Meat": "培养肉",
  "Labor Disputes": "劳动纠纷",
  "Lacrosse": "长曲棍球",
  "Landlord Rights": "房东权利",
  "Landscape Design": "景观设计",
  "Landscape Painting": "风景画",
  "Landscape Photography": "风景摄影",
  "Language Acquisition": "语言习得",
  "Language Exchange": "语言交换",
  "Language Immersion": "语言沉浸",
  "Language Learning": "语言学习",
  "Language Models": "语言模型",
  "Laravel": "Laravel",
  "Large Language Models": "大语言模型",
  "Laser Cutting": "激光切割",
  "Lateral Thinking": "横向思维",
  "Latin America Travel": "拉丁美洲旅行",
  "Latin American Cuisine": "拉丁美洲美食",
  "Laundry": "洗衣",
  "Law School": "法学院",
  "Layer 2 Scaling": "二层扩容",
  "Lead Generation": "线索生成",
  "Leadership": "领导力",
  "Leadership Development": "领导力发展",
  "Lean Management": "精益管理",
  "Learning": "学习",
  "Leasing Business": "租赁业务",
  "Leather Craft": "皮革工艺",
  "Leather Crafting": "皮革手作",
  "Legacy Planning": "遗产规划",
  "Legal": "法律",
  "Legal Aid": "法律援助",
  "Legal Research": "法律研究",
  "Library Science": "图书馆学",
  "Licensing": "许可",
  "Life Balance": "生活平衡",
  "Life Coaching": "人生教练",
  "Life Purpose": "人生目标",
  "Life Transitions": "人生转变",
  "Linguistics": "语言学",
  "Link Building": "链接建设",
  "LinkedIn": "LinkedIn",
  "LinkedIn Ads": "LinkedIn广告",
  "LinkedIn Growth": "LinkedIn增长",
  "Linux": "Linux",
  "Linux Administration": "Linux管理",
  "Linux Security": "Linux安全",
  "Literacy Programs": "读写项目",
  "Literary Analysis": "文学分析",
  "Live Streaming": "直播",
  "Liver Health": "肝脏健康",
  "Local SEO": "本地SEO",
  "Logic Puzzles": "逻辑谜题",
  "Logistics Management": "物流管理",
  "Logo Design": "Logo设计",
  "Loneliness": "孤独",
  "Longevity": "长寿",
  "Loyalty Programs": "会员计划",
  "Lua Programming": "Lua编程",
  "Lung Health": "肺部健康",
  "Luxury Hotels": "豪华酒店",
  "Luxury Travel": "奢华旅行",
  "M&A": "并购",
  "MATLAB": "MATLAB",
  "MERN Stack": "MERN技术栈",
  "MLOps": "MLOps",
  "Machine Learning Ops": "机器学习运维",
  "Magic Tricks": "魔术",
  "Maker Education": "创客教育",
  "Makeup Artistry": "化妆艺术",
  "Management Consulting": "管理咨询",
  "Mandarin Learning": "汉语学习",
  "Manhood": "男子气概",
  "Manners": "礼貌",
  "Marathon Training": "马拉松训练",
  "Marine Biology": "海洋生物学",
  "Maritime Law": "海商法",
  "Market Entry": "市场进入",
  "Market Research": "市场调研",
  "Marketing": "营销",
  "Marketplace Building": "市场平台建设",
  "Marriage": "婚姻",
  "Marriage Counseling": "婚姻咨询",
  "Mars Colonization": "火星殖民",
  "Mars Mission": "火星任务",
  "Martial Arts": "武术",
  "Massage Therapy": "按摩疗法",
  "Materials Science": "材料科学",
  "Math": "数学",
  "Math Education": "数学教育",
  "Meal Planning": "膳食规划",
  "Meal Prep": "备餐",
  "Mechanical Engineering": "机械工程",
  "Media Literacy": "媒体素养",
  "Mediation": "调解",
  "Medical Imaging": "医学影像",
  "Medical School": "医学院",
  "Medication Management": "用药管理",
  "Meditation": "冥想",
  "Meditation Apps": "冥想应用",
  "Mediterranean Diet": "地中海饮食",
  "Meeting Agendas": "会议议程",
  "Meetings": "会议",
  "Memory": "记忆",
  "Memory Improvement": "记忆提升",
  "Men's Grooming": "男士仪容",
  "Men's Health": "男性健康",
  "Mental Clarity": "思维清晰",
  "Mental Health": "心理健康",
  "Mental Health First Aid": "心理急救",
  "Mentorship": "导师制",
  "Metabolic Health": "代谢健康",
  "Metallurgy": "冶金学",
  "Metaverse": "元宇宙",
  "Meteorology": "气象学",
  "Mexican Cuisine": "墨西哥美食",
  "Micro Frontends": "微前端",
  "Micro-SaaS": "微SaaS",
  "Microbiology": "微生物学",
  "Microfinance": "小额金融",
  "Microservices": "微服务",
  "Middle East Travel": "中东旅行",
  "Middle Eastern Cuisine": "中东美食",
  "Midjourney": "Midjourney",
  "Midlife Crisis": "中年危机",
  "Military Law": "军事法",
  "Mind Mapping": "思维导图",
  "Mind-Body Connection": "身心连接",
  "Mindfulness": "正念",
  "Mindfulness Exercises": "正念练习",
  "Mindfulness Meditation": "正念冥想",
  "Mindset Shift": "心态转变",
  "Miniature Painting": "微型绘画",
  "Minimalism": "极简主义",
  "Mixology": "调酒学",
  "Mobile Apps": "移动应用",
  "Mobile Payments": "移动支付",
  "Mobile Photography": "手机摄影",
  "Mobile Security": "移动安全",
  "Mobile UI Design": "移动UI设计",
  "Mobility Training": "活动度训练",
  "Model Building": "模型制作",
  "Model UN": "模拟联合国",
  "Molecular Biology": "分子生物学",
  "MongoDB": "MongoDB",
  "Mongoose": "Mongoose",
  "Montessori Activities": "蒙氏活动",
  "Mood Disorders": "情绪障碍",
  "Morning Routines": "晨间习惯",
  "Mortgage Banking": "按揭银行",
  "Motherhood": "母亲角色",
  "Motion Graphics": "动态图形",
  "Motivation": "动力",
  "Mountain Biking": "山地骑行",
  "Mountaineering": "登山",
  "Movie Making for Kids": "儿童电影制作",
  "Movie Recommendations": "电影推荐",
  "Moving": "搬家",
  "Multilevel Marketing": "多层次营销",
  "Mural Art": "壁画艺术",
  "Mural Painting": "壁画",
  "Muscle Recovery": "肌肉恢复",
  "Museum Visits": "博物馆参观",
  "Mushroom Hunting": "采蘑菇",
  "Music Composition": "音乐创作",
  "Music Production": "音乐制作",
  "Music Theory": "音乐理论",
  "Mutual Funds": "共同基金",
  "NDA Drafting": "保密协议起草",
  "NFT & Digital Art": "NFT与数字艺术",
  "NFT Minting": "NFT铸造",
  "NLP": "自然语言处理",
  "Nanotechnology": "纳米技术",
  "Naturopathy": "自然疗法",
  "Negotiation": "谈判",
  "Negotiation Mastery": "谈判精通",
  "Negotiation Skills": "谈判技能",
  "Negotiation Tactics": "谈判策略",
  "Net Promoter Score": "净推荐值",
  "Net Zero Strategy": "净零战略",
  "Networking": "人脉",
  "Neural Networks": "神经网络",
  "Neurological Health": "神经健康",
  "Neuroscience": "神经科学",
  "Neurotech": "神经科技",
  "Neurotechnology": "神经技术",
  "New Parents": "新手父母",
  "Newsletter Content": "通讯内容",
  "Newsletter Growth": "通讯增长",
  "Next.js": "Next.js",
  "Nginx": "Nginx",
  "No-Code Tools": "无代码工具",
  "NoSQL Databases": "NoSQL数据库",
  "Nonprofit Management": "非营利管理",
  "North America Travel": "北美旅行",
  "Note-Taking": "笔记",
  "Notion": "Notion",
  "Novel Writing": "小说创作",
  "Nuclear Energy": "核能",
  "Nuclear Engineering": "核工程",
  "Nuclear Physics": "核物理",
  "Nutrition": "营养",
  "Nutrition Coaching": "营养教练",
  "OAuth Security": "OAuth安全",
  "Obesity Management": "肥胖管理",
  "Objective-C": "Objective-C",
  "Occupational Health": "职业健康",
  "Ocean Conservation": "海洋保护",
  "Ocean Pollution": "海洋污染",
  "Ocean Science": "海洋科学",
  "Ocean Swimming": "公开水域游泳",
  "Oceania Travel": "大洋洲旅行",
  "Off-Grid Living": "离网生活",
  "Office Management": "办公室管理",
  "Onboarding": "入职引导",
  "Oncology Support": "肿瘤支持",
  "Online Courses": "在线课程",
  "Online Teaching": "在线教学",
  "Open Government": "开放政府",
  "Open Source": "开源",
  "OpenGL": "OpenGL",
  "Operating Systems": "操作系统",
  "Operations Management": "运营管理",
  "Ophthalmology": "眼科",
  "Optics": "光学",
  "Options Trading": "期权交易",
  "Oracle Systems": "Oracle系统",
  "Organic Chemistry": "有机化学",
  "Organic Farming": "有机农业",
  "Organization Skills": "组织技能",
  "Organizational Design": "组织设计",
  "Origami": "折纸",
  "Ornithology": "鸟类学",
  "Orthopedics": "骨科",
  "Osteoporosis": "骨质疏松",
  "Outsourcing": "外包",
  "PCB Design": "PCB设计",
  "PHP Development": "PHP开发",
  "PR & Media": "公关与媒体",
  "Packaging Design": "包装设计",
  "Paid Ads": "付费广告",
  "Pain Management": "疼痛管理",
  "Painting": "绘画",
  "Paleontology": "古生物学",
  "Palliative Care": "姑息治疗",
  "Paper Crafts": "纸艺",
  "Parenting": "育儿",
  "Parkinson's Support": "帕金森支持",
  "Parkour": "跑酷",
  "Partnership Marketing": "合作营销",
  "Partnership Strategy": "合作策略",
  "Party Planning": "派对策划",
  "Passion Discovery": "热情发现",
  "Passive Income": "被动收入",
  "Passport & Visa": "护照与签证",
  "Pasta Making": "意面制作",
  "Pastry": "糕点",
  "Patent Law": "专利法",
  "Patience": "耐心",
  "Pattern Design": "图案设计",
  "Payroll Management": "薪酬管理",
  "Pediatric Health": "儿科健康",
  "Penetration Testing": "渗透测试",
  "Pension Planning": "养老金规划",
  "Perfectionism": "完美主义",
  "Performance Art": "行为艺术",
  "Performance Management": "绩效管理",
  "Performance Reviews": "绩效考核",
  "Performance Testing": "性能测试",
  "Permaculture": "永续农业",
  "Personal": "个人",
  "Personal Branding": "个人品牌",
  "Personal CRM": "个人CRM",
  "Personal Finance": "个人财务",
  "Personal Growth": "个人成长",
  "Personal Injury": "人身伤害",
  "Personalized Medicine": "个性化医疗",
  "Persuasion": "说服力",
  "Pest Control": "害虫防治",
  "Pet Care": "宠物护理",
  "Pet Therapy": "宠物治疗",
  "Pet Training": "宠物训练",
  "Petroleum Engineering": "石油工程",
  "Pets": "宠物",
  "Pharmacology": "药理学",
  "Pharmacy": "药学",
  "Philosophy": "哲学",
  "Phonics": "自然拼读",
  "Photo Editing": "照片编辑",
  "Photography": "摄影",
  "Photography Travel": "摄影旅行",
  "Photography for Teens": "青少年摄影",
  "Photovoltaics": "光伏",
  "Physical Education": "体育",
  "Physical Rehabilitation": "物理康复",
  "Physical Therapy": "物理治疗",
  "Physics": "物理学",
  "Piano": "钢琴",
  "Pickleball": "匹克球",
  "Pilates": "普拉提",
  "Pilgrimage": "朝圣",
  "Plant Care": "植物护理",
  "Plasma Physics": "等离子体物理",
  "Plastic Reduction": "减塑",
  "Platform Business": "平台商业",
  "Play-Based Learning": "游戏式学习",
  "Podcast Editing": "播客编辑",
  "Podcast Marketing": "播客营销",
  "Podcast Topics": "播客选题",
  "Podcasting": "播客",
  "Poetry": "诗歌",
  "Poetry Writing": "诗歌写作",
  "Political Science": "政治学",
  "Polymer Science": "高分子科学",
  "Pomodoro Technique": "番茄工作法",
  "Portfolio Career": "组合职业",
  "Portfolio Management": "投资组合管理",
  "Portrait Photography": "人像摄影",
  "Portuguese Learning": "葡萄牙语学习",
  "Positive Affirmations": "积极肯定",
  "Positive Psychology": "积极心理学",
  "PostgreSQL": "PostgreSQL",
  "Postpartum Care": "产后护理",
  "Posture": "体态",
  "Posture Correction": "体态矫正",
  "Pottery": "陶艺",
  "Power BI": "Power BI",
  "Powerlifting": "力量举",
  "Pregnancy": "怀孕",
  "Prenatal Care": "产前护理",
  "Prepping": "应急储备",
  "Prescription Drugs": "处方药",
  "Presentation Skills": "演讲技能",
  "Preventive Medicine": "预防医学",
  "Pricing": "定价",
  "Pricing Strategy": "定价策略",
  "Print Design": "印刷设计",
  "Print on Demand": "按需印刷",
  "Printmaking": "版画",
  "Privacy Law": "隐私法",
  "Private Equity": "私募股权",
  "Probiotics": "益生菌",
  "Problem Solving": "问题解决",
  "Process Optimization": "流程优化",
  "Procrastination": "拖延症",
  "Procurement": "采购",
  "Product Descriptions": "产品描述",
  "Product Design": "产品设计",
  "Product Hunt Launch": "Product Hunt发布",
  "Product Launch": "产品发布",
  "Product Lifecycle": "产品生命周期",
  "Product Management": "产品管理",
  "Product Marketing": "产品营销",
  "Product-Led Growth": "产品驱动增长",
  "Productivity": "生产力",
  "Productized Services": "产品化服务",
  "Programmatic Ads": "程序化广告",
  "Project Management": "项目管理",
  "Project Planning": "项目规划",
  "Prompt Engineering": "提示工程",
  "Prompt Engineering Advanced": "高级提示工程",
  "Proofreading": "校对",
  "Prop Making": "道具制作",
  "Property Law": "财产法",
  "Psychiatry": "精神病学",
  "Psychology": "心理学",
  "Psychotherapy": "心理治疗",
  "Public Administration": "公共行政",
  "Public Policy": "公共政策",
  "Public Relations": "公共关系",
  "Public Schools": "公立学校",
  "Public Speaking": "公众演讲",
  "Public Speaking for Kids": "儿童演讲",
  "Public Transport": "公共交通",
  "Puzzle Design": "谜题设计",
  "Puzzle Solving": "解谜",
  "PyTorch": "PyTorch",
  "Python": "Python",
  "QA Testing": "QA测试",
  "Quality Assurance": "质量保证",
  "Quantum Computing": "量子计算",
  "Quantum Mechanics": "量子力学",
  "Quilting": "绗缝",
  "R Programming": "R语言编程",
  "RAG Systems": "RAG系统",
  "REITs": "REITs",
  "REST API Design": "REST API设计",
  "RPA Automation": "RPA自动化",
  "RV Living": "房车生活",
  "RabbitMQ": "RabbitMQ",
  "Racquetball": "壁球",
  "Rail Travel": "铁路旅行",
  "Rainwater Harvesting": "雨水收集",
  "Raspberry Pi": "树莓派",
  "React": "React",
  "React Native": "React Native",
  "React Patterns": "React模式",
  "Reading Comprehension": "阅读理解",
  "Reading Lists": "阅读清单",
  "Reading More": "多读书",
  "Real Estate": "房地产",
  "Real Estate Finance": "房地产金融",
  "Real Estate Investing": "房地产投资",
  "Recipe Creation": "食谱创作",
  "Recommendation Letters": "推荐信",
  "Recruitment": "招聘",
  "Recycling": "回收",
  "Redis": "Redis",
  "Referral Programs": "推荐计划",
  "Reflexology": "反射疗法",
  "RegTech": "监管科技",
  "Regulatory Affairs": "监管事务",
  "Regulatory Compliance": "法规合规",
  "Rehabilitation": "康复",
  "Reiki": "灵气疗法",
  "Reinforcement Learning": "强化学习",
  "Relationship Advice": "关系建议",
  "Relationship Building": "关系建立",
  "Relationships": "人际关系",
  "Religious Studies": "宗教研究",
  "Relocation": "搬迁",
  "Remote Team Building": "远程团建",
  "Remote Work": "远程工作",
  "Remote Work Tools": "远程工作工具",
  "Renewable Energy": "可再生能源",
  "Renewable Resources": "可再生资源",
  "Renting": "租房",
  "Report Writing": "报告写作",
  "Reproductive Health": "生殖健康",
  "Reptile Care": "爬行动物护理",
  "Repurposing": "旧物改造",
  "Research": "研究",
  "Research Methods": "研究方法",
  "Resilience": "韧性",
  "Resilience Building": "韧性建设",
  "Respiratory Health": "呼吸健康",
  "Restaurants": "餐厅",
  "Restless Leg Syndrome": "不安腿综合征",
  "Resume Writing": "简历写作",
  "Retail": "零售",
  "Retargeting": "重定向",
  "Retirement Planning": "退休规划",
  "Revenue Operations": "营收运营",
  "Risk Assessment": "风险评估",
  "Risk Management": "风险管理",
  "Rituals & Routines": "仪式与习惯",
  "Road Trips": "公路旅行",
  "Robot Programming": "机器人编程",
  "Robotics": "机器人",
  "Robotics Education": "机器人教育",
  "Robotics Engineering": "机器人工程",
  "Robotics for Kids": "儿童机器人",
  "Rock Climbing": "攀岩",
  "Roller Skating": "轮滑",
  "Romance": "浪漫",
  "Rooftop Garden": "屋顶花园",
  "Rowing": "赛艇",
  "Royalties": "版税",
  "Ruby on Rails": "Ruby on Rails",
  "Rugby": "橄榄球",
  "Running": "跑步",
  "Running Injuries": "跑步伤病",
  "Running Marathon": "马拉松跑步",
  "Rust Programming": "Rust编程",
  "SAT Prep": "SAT备考",
  "SEO": "SEO",
  "SEO Strategy": "SEO策略",
  "SQL Optimization": "SQL优化",
  "STEM Education": "STEM教育",
  "SaaS": "SaaS",
  "SaaS Business": "SaaS业务",
  "SaaS Development": "SaaS开发",
  "Sabbatical": "休假年",
  "Sailing": "帆船",
  "Salad Recipes": "沙拉食谱",
  "Salary Negotiation": "薪资谈判",
  "Sales": "销售",
  "Sales Closing": "销售成交",
  "Sales Enablement": "销售赋能",
  "Sales Pipeline": "销售管道",
  "Sales Prospecting": "销售拓展",
  "Salesforce": "Salesforce",
  "Sandwich Making": "三明治制作",
  "Satellite Systems": "卫星系统",
  "Satellite Technology": "卫星技术",
  "Sauces & Dressings": "酱汁与调料",
  "Saving Money": "省钱",
  "Saying No": "学会说不",
  "Scala": "Scala",
  "Scheduling": "日程安排",
  "Scholarship Writing": "奖学金申请",
  "Scholarships": "奖学金",
  "Science Fair": "科学展",
  "Scientific Writing": "科学写作",
  "Scrapbooking": "剪贴簿",
  "Scratch Programming": "Scratch编程",
  "Screen Printing": "丝网印刷",
  "Screenplay Writing": "剧本写作",
  "Screenwriting": "编剧",
  "Scrum": "Scrum",
  "Scuba Diving": "水肺潜水",
  "Sculpture": "雕塑",
  "Seafood Cooking": "海鲜烹饪",
  "Security Auditing": "安全审计",
  "Seismology": "地震学",
  "Self-Awareness": "自我觉察",
  "Self-Compassion": "自我慈悲",
  "Self-Confidence": "自信",
  "Self-Directed Learning": "自主学习",
  "Self-Discipline": "自律",
  "Self-Esteem": "自尊",
  "Self-Improvement": "自我提升",
  "Senior Fitness": "老年健身",
  "Senior Living": "老年生活",
  "Sensory Play": "感官游戏",
  "Serverless Architecture": "无服务器架构",
  "Set Design": "布景设计",
  "Sewing": "缝纫",
  "Sexual Health": "性健康",
  "Shareholder Relations": "股东关系",
  "Shopify": "Shopify",
  "Short-Form Video": "短视频",
  "Side Hustles": "副业",
  "Single Parenting": "单亲育儿",
  "Site Reliability": "站点可靠性",
  "Six Sigma": "六西格玛",
  "Skateboarding": "滑板",
  "Sketch Design": "草图设计",
  "Sketching": "速写",
  "Skiing": "滑雪",
  "Skill Building": "技能建设",
  "Skin Cancer": "皮肤癌",
  "Skincare Routine": "护肤",
  "Sleep": "睡眠",
  "Sleep Apps": "睡眠应用",
  "Sleep Hygiene": "睡眠卫生",
  "Sleep Optimization": "睡眠优化",
  "Slow Cooker": "慢炖锅",
  "Slow Cooking": "慢炖",
  "Slow Living": "慢生活",
  "Small Business": "小企业",
  "Small Claims": "小额索赔",
  "Small Talk": "闲聊",
  "Smart Cities": "智慧城市",
  "Smart Contracts": "智能合约",
  "Smart Home": "智能家居",
  "Smoking Cessation": "戒烟",
  "Smoothie Recipes": "冰沙食谱",
  "Snorkeling": "浮潜",
  "Snowboarding": "单板滑雪",
  "Snowflake": "Snowflake",
  "Soap Making": "手工皂制作",
  "Soccer": "英式足球",
  "Social": "社交",
  "Social Anxiety": "社交焦虑",
  "Social Enterprise": "社会企业",
  "Social Justice": "社会正义",
  "Social Media Ads": "社交媒体广告",
  "Social Media Posts": "社交媒体帖子",
  "Social Skills": "社交技能",
  "Social-Emotional Learning": "社会情感学习",
  "Sociology": "社会学",
  "Software Architecture": "软件架构",
  "Software Estimation": "软件估算",
  "Soil Conservation": "土壤保护",
  "Soil Science": "土壤科学",
  "Solar Energy": "太阳能",
  "Solar Power": "太阳能发电",
  "Solidity": "Solidity",
  "Solo Travel": "独自旅行",
  "Song Lyrics": "歌词",
  "Songwriting": "词曲创作",
  "Sound Design": "声音设计",
  "Soup Recipes": "汤谱",
  "Sourdough": "酸面团",
  "Sous Vide": "低温慢煮",
  "South America Travel": "南美旅行",
  "Space Design": "空间设计",
  "Space Exploration": "太空探索",
  "Space Mining": "太空采矿",
  "Space Science": "空间科学",
  "Space Tourism": "太空旅游",
  "Spanish Learning": "西班牙语学习",
  "Spatial Computing": "空间计算",
  "Special Education": "特殊教育",
  "Speech Writing": "演讲稿写作",
  "Speed Learning": "快速学习",
  "Speed Reading": "快速阅读",
  "Speed Running": "速通",
  "Spelling & Vocabulary": "拼写与词汇",
  "Spice Blends": "混合香料",
  "Spiritual Travel": "心灵旅行",
  "Spirituality": "灵性",
  "Sports Analytics": "体育分析",
  "Sports Injuries": "运动伤病",
  "Sports Medicine": "运动医学",
  "Sports Nutrition": "运动营养",
  "Sports Psychology": "运动心理",
  "Spreadsheets": "电子表格",
  "Stable Diffusion": "Stable Diffusion",
  "Stakeholder Management": "利益相关者管理",
  "Stamp Collecting": "集邮",
  "Standing Desk": "站立办公桌",
  "Startup": "创业公司",
  "Startup Growth": "创业增长",
  "Startup Strategy": "创业战略",
  "Statistics": "统计学",
  "Steak Cooking": "牛排烹饪",
  "Stock Market": "股市",
  "Stock Trading": "股票交易",
  "Stoicism": "斯多葛主义",
  "Storytelling": "讲故事",
  "Strategic Planning": "战略规划",
  "Street Art": "街头艺术",
  "Strength Training": "力量训练",
  "Stress Management": "压力管理",
  "Stress Relief": "减压",
  "Stroke Recovery": "中风恢复",
  "Structural Engineering": "结构工程",
  "Student Loans": "学生贷款",
  "Studio Recording": "录音棚录制",
  "Study Abroad": "留学",
  "Study Notes": "学习笔记",
  "Study Skills": "学习技能",
  "Studying": "学习",
  "Subscription Business": "订阅业务",
  "Succulents": "多肉植物",
  "Sudoku": "数独",
  "Sugar Addiction": "糖瘾",
  "Supplements": "补剂",
  "Supply Chain": "供应链",
  "Support": "客服支持",
  "Surfing": "冲浪",
  "Surgery Recovery": "术后恢复",
  "Survival Skills": "生存技能",
  "Sushi Making": "寿司制作",
  "Sustainability": "可持续性",
  "Sustainable Agriculture": "可持续农业",
  "Sustainable Design": "可持续设计",
  "Sustainable Fashion": "可持续时尚",
  "Sustainable Fashion Design": "可持续时装设计",
  "Sustainable Health": "可持续健康",
  "Sustainable Living": "可持续生活",
  "Svelte": "Svelte",
  "Swift": "Swift",
  "Swift Development": "Swift开发",
  "Swimming": "游泳",
  "Synthetic Biology": "合成生物学",
  "System Design": "系统设计",
  "Systems Thinking": "系统思维",
  "TOEFL Prep": "TOEFL备考",
  "TRX Training": "TRX训练",
  "TV Show Analysis": "电视剧分析",
  "Table Tennis": "乒乓球",
  "Tableau": "Tableau",
  "Tabletop RPGs": "桌面角色扮演",
  "Taekwondo": "跆拳道",
  "Tai Chi": "太极",
  "Tailoring": "裁缝",
  "Talent Management": "人才管理",
  "Tattoo Art": "纹身艺术",
  "Tax Law": "税法",
  "Tax Planning": "税务规划",
  "Tax Strategy": "税务策略",
  "Taxes": "税务",
  "Tea Brewing": "泡茶",
  "Teacher Training": "教师培训",
  "Teaching": "教学",
  "Teaching Skills": "教学技能",
  "Team Building": "团队建设",
  "Team Leadership": "团队领导力",
  "Team Management": "团队管理",
  "Tech Support": "技术支持",
  "Technical SEO": "技术SEO",
  "Technical Sales": "技术销售",
  "Technical Writing": "技术写作",
  "Teen Parenting": "青少年育儿",
  "Telecommunications": "电信",
  "Telemedicine": "远程医疗",
  "Tenant Rights": "租户权利",
  "Tennis": "网球",
  "TensorFlow": "TensorFlow",
  "Terraform": "Terraform",
  "Terrariums": "生态缸",
  "Test Prep": "考试准备",
  "Test-Driven Development": "测试驱动开发",
  "Testimonial Requests": "推荐请求",
  "Textile Design": "纺织品设计",
  "Thai Cuisine": "泰国美食",
  "Thank You Messages": "感谢信息",
  "Theme Parks": "主题公园",
  "Therapy & Counseling": "治疗与咨询",
  "Thermodynamics": "热力学",
  "Thesis Writing": "论文写作",
  "Thought Leadership": "思想领导力",
  "Thrift Fashion": "二手时尚",
  "Thrifting": "旧货淘购",
  "Thyroid Health": "甲状腺健康",
  "Tidal Energy": "潮汐能",
  "TikTok Marketing": "TikTok营销",
  "Time Blocking": "时间块",
  "Time Management": "时间管理",
  "Time Zones": "时区",
  "Tiny House": "小屋生活",
  "Toddler Activities": "幼儿活动",
  "Toddler Care": "幼儿护理",
  "Tokenomics": "代币经济学",
  "Tour Guide Skills": "导游技能",
  "Toxicology": "毒理学",
  "Track & Field": "田径",
  "Trade Compliance": "贸易合规",
  "Trade Law": "贸易法",
  "Trademark Law": "商标法",
  "Traditional Chinese Medicine": "中医",
  "Trail Running": "越野跑",
  "Translation": "翻译",
  "Transportation Engineering": "交通工程",
  "Trauma Recovery": "创伤恢复",
  "Travel": "旅行",
  "Travel Hacking": "旅行黑客",
  "Travel Insurance": "旅行保险",
  "Travel Photography": "旅行摄影",
  "Travel Planning": "旅行规划",
  "Travel Safety": "旅行安全",
  "Travel Writing": "旅行写作",
  "Traveling with Kids": "亲子旅行",
  "Traveling with Pets": "携宠旅行",
  "Treadmill Training": "跑步机训练",
  "Treasury Management": "资金管理",
  "Triathlon": "铁人三项",
  "Triathlon Training": "铁三训练",
  "Trust Building": "信任建设",
  "Tutoring": "辅导",
  "Twitter/X Strategy": "Twitter/X策略",
  "TypeScript": "TypeScript",
  "TypeScript Advanced": "TypeScript高级",
  "Typography": "排版",
  "UI Animation": "UI动画",
  "UI Design": "UI设计",
  "UX Design": "UX设计",
  "Unity": "Unity",
  "Unity Development": "Unity开发",
  "University Life": "大学生活",
  "Unreal Engine": "虚幻引擎",
  "Upcycling": "升级回收",
  "Urban Exploration": "城市探索",
  "Urban Farming": "城市农业",
  "Urban Sketching": "城市速写",
  "Usability Testing": "可用性测试",
  "User Research": "用户研究",
  "VFX": "视觉特效",
  "VR Development": "VR开发",
  "Vaccination": "疫苗接种",
  "Valuation Methods": "估值方法",
  "Value Chain Analysis": "价值链分析",
  "Values & Ethics": "价值观与伦理",
  "Van Life": "房车生活",
  "Vegan Cooking": "纯素烹饪",
  "Vegan Nutrition": "纯素营养",
  "Vegetarian Cooking": "素食烹饪",
  "Vendor Management": "供应商管理",
  "Venture Capital": "风险投资",
  "Vertical Farming": "垂直农业",
  "Veterinary Care": "兽医护理",
  "Video": "视频",
  "Video Editing": "视频编辑",
  "Video Scripts": "视频脚本",
  "Vietnamese Cuisine": "越南美食",
  "Vintage Collecting": "古着收藏",
  "Viral Marketing": "病毒式营销",
  "Virology": "病毒学",
  "Virtual Meetings": "虚拟会议",
  "Virtual Reality": "虚拟现实",
  "Virtual Reality Fitness": "VR健身",
  "Virtual Teams": "虚拟团队",
  "Visual Arts": "视觉艺术",
  "Visualization": "可视化",
  "Vitamin Deficiency": "维生素缺乏",
  "Vocabulary Building": "词汇构建",
  "Voice Acting": "配音",
  "Voiceover": "旁白",
  "Volcanology": "火山学",
  "Volleyball": "排球",
  "Volunteering": "志愿服务",
  "Volunteering Abroad": "海外志愿",
  "Voluntourism": "志愿旅游",
  "Voting Rights": "投票权",
  "Vue.js": "Vue.js",
  "Water Polo": "水球",
  "Water Technology": "水技术",
  "Water Treatment": "水处理",
  "Watercolor": "水彩",
  "Wealth Management": "财富管理",
  "Wearable Tech": "可穿戴技术",
  "Web Design": "网页设计",
  "Web Development": "Web开发",
  "Web3": "Web3",
  "Web3 Development": "Web3开发",
  "Web3 Security": "Web3安全",
  "WebAssembly": "WebAssembly",
  "WebGL": "WebGL",
  "WebRTC": "WebRTC",
  "Webinar Marketing": "网络研讨会营销",
  "Wedding Budget": "婚礼预算",
  "Wedding Photography": "婚礼摄影",
  "Wedding Planning": "婚礼策划",
  "Weekend Planning": "周末规划",
  "Weight Loss": "减重",
  "Weight Training": "负重训练",
  "Weightlifting": "举重",
  "Welding": "焊接",
  "Wellness Routine": "健康习惯",
  "White Label": "白标",
  "Wholesale Business": "批发业务",
  "Wildlife Biology": "野生生物学",
  "Wildlife Protection": "野生动物保护",
  "Willpower": "意志力",
  "Wind Energy": "风能",
  "Wind Turbines": "风力涡轮机",
  "Wine": "葡萄酒",
  "Wine Making": "酿酒",
  "Wine Pairing": "葡萄酒搭配",
  "Wireshark": "Wireshark",
  "Women's Wellness": "女性健康",
  "Woodcraft": "木工",
  "Woodworking": "木工",
  "WordPress": "WordPress",
  "WordPress Plugins": "WordPress插件",
  "Work Visa": "工作签证",
  "Work-Life Balance": "工作生活平衡",
  "Workers' Compensation": "工伤赔偿",
  "Workplace Communication": "职场沟通",
  "Workplace Conflict": "职场冲突",
  "Workplace Wellness": "职场健康",
  "World Religions": "世界宗教",
  "Wound Care": "伤口护理",
  "Wrestling": "摔跤",
  "Writing": "写作",
  "Writing Emails": "邮件写作",
  "Writing Workshop": "写作工坊",
  "Xamarin": "Xamarin",
  "Yoga": "瑜伽",
  "Yoga Therapy": "瑜伽疗法",
  "Yoga for Athletes": "运动员瑜伽",
  "YouTube": "YouTube",
  "YouTube SEO": "YouTube SEO",
  "Zero Waste": "零废弃",
  "Zero-Knowledge Proofs": "零知识证明",
  "Zodiac": "星座",
  "Zoology": "动物学",
  "Zumba": "尊巴",
  "jQuery": "jQuery"
};
