/* =====================================================================
 * PromptRunic — lang-es.js  (Spanish translations)
 * Register Spanish dictionary with the i18n engine.
 * ===================================================================== */
(function(){
'use strict';

var ES = {
  /* ---- Header ---- */
  'header.prompts': 'Prompts',
  'header.guide': 'Guía para principiantes',
  'header.activate': 'Activar código',
  'header.signin': 'Iniciar sesión',
  'header.game': 'Juego',
  'header.getpro': 'Obtener Pro',
  'header.community': 'Comunidad',
  'header.friends': 'Amigos',

  /* ---- Hero ---- */
  'hero.h1.prefix': 'PromptRunic',
  'hero.h1.grad': 'Tu generador de prompts IA & asistente IA',
  'hero.h1.suffix': '<br/>700,000+ prompts de IA, envía cualquiera con un clic.',
  'hero.p': '{freeN} prompts son de uso gratuito — desbloquea los {totalN} con un código de activación Pro. PromptRunic es tu compañero IA para escritura, programación, marketing y más. ¿Nuevo en IA? Te enseñamos cómo preguntar.',

  /* ---- CTA ---- */
  'cta.browse': 'Explorar prompts',
  'cta.unlock': 'Obtener Pro — desde $0.99',
  'cta.play': '🎮 Jugar',

  /* ---- Stats ---- */
  'stat.prompts': 'prompts listos para usar',
  'stat.categories': 'categorías',
  'stat.styles': 'estilos de respuesta',
  'stat.assistants': 'asistentes de IA',

  /* ---- Universe ---- */
  'universe.eyebrow': 'Universo PromptRunic',
  'universe.title': 'Toda una galaxia de prompts.\nUna plataforma de lanzamiento.',
  'universe.sub': '700,000 prompts listos para usar en 1,684 categorías — escritura, programación, marketing, aprendizaje, crianza, viajes y mucho más. Elige uno, rellena los espacios, envíalo a tu IA.',
  'universe.cta': 'Entrar a la biblioteca ›',

  /* ---- Guide ---- */
  'guide.title': '¿Nuevo en IA? Domina todo en 2 minutos.',
  'guide.sub': 'La respuesta de una IA solo es tan buena como tu prompt. Aquí está la receta que cada prompt de PromptRunic ya incluye — solo rellena los espacios.',
  'guide.step1': '1 · Rol',
  'guide.step1.desc': 'Dile a la IA quién ser — "Actúa como un coach profesional experimentado…"',
  'guide.step2': '2 · Tarea',
  'guide.step2.desc': 'Di exactamente qué quieres que haga.',
  'guide.step3': '3 · Contexto',
  'guide.step3.desc': 'Proporciona detalles reales: nombres, números, tu situación.',
  'guide.step4': '4 · Formato',
  'guide.step4.desc': 'Cómo quieres la respuesta — una tabla, 5 viñetas, un correo.',
  'guide.step5': '5 · Restricciones',
  'guide.step5.desc': 'Límites y tono — "Menos de 150 palabras, amigable, sin jerga."',
  'guide.weak': 'Prompt débil',
  'guide.weak.example': '"Escribe un currículum."',
  'guide.strong': 'Prompt fuerte',
  'guide.strong.example': '"Actúa como un redactor de currículums profesional. Reescribe mi experiencia como gerente de marketing en 5 viñetas de logros con resultados medibles. Una página, seguro sin ser presuntuoso."',
  'guide.tip': 'Consejo: abre la categoría <strong>Fundamentos de IA</strong> abajo — esos prompts son herramientas de coaching que convierten tu idea vaga en un gran prompt.',

  /* ---- Search ---- */
  'search.placeholder': "Buscar 700,000+ prompts — prueba 'currículum', 'correo frío', 'plan de viaje'...",

  /* ---- Sidebar ---- */
  'sidebar.library': 'Biblioteca',
  'sidebar.you': 'Tú',
  'sidebar.all': 'Todos los prompts',
  'sidebar.favorites': '★ Favoritos',

  /* ---- Grid ---- */
  'grid.locked': '🔒 PRO',
  'grid.free': 'GRATIS',
  'grid.noprompts': 'No hay prompts aquí todavía.',
  'grid.noprompts.fav': ' Marca un prompt como favorito para guardarlo.',
  'grid.showmore': 'Mostrar más',
  'grid.prompt.s': ' prompts',
  'grid.prompt': ' prompt',
  'grid.locked.count': ' bloqueados (activa Pro para desbloquear)',
  'grid.showing': ' · mostrando ',

  /* ---- Prompt Modal ---- */
  'pm.tip': '💡 Consejo: cuánto más específico seas en los espacios abajo, mejor será la respuesta. Añade nombres reales, números y contexto.',
  'pm.style.label': 'Estilo de respuesta — elige el tipo de respuesta que quieres:',
  'pm.output.label': 'Tu prompt terminado',
  'pm.copy': 'Copiar prompt',
  'pm.fav.save': '☆ Guardar en favoritos',
  'pm.fav.saved': '★ Guardado',
  'pm.noblanks': 'Este prompt no tiene espacios — solo cópialo o envíalo a una IA.',
  'pm.ai.label': 'Enviar directamente a una IA — el prompt se copia y la IA se abre:',
  'pm.ai.note': 'ChatGPT y Claude rellenan automáticamente el prompt desde el enlace. Para Copilot, Gemini y DeepSeek, presiona <strong>Ctrl+V</strong> para pegar — ya está en tu portapapeles. El autocompletado con un clic en todas las IA, además de dos IA locales integradas, están en la aplicación de escritorio PromptRunic.',

  /* ---- Prompt History / Share ---- */
  'pm.history.title': 'Historial de Prompts',
  'pm.history.empty': 'Aún no hay prompts vistos recientemente.',
  'pm.share.copied': '¡Enlace compartido copiado! Los prompts Pro requieren inicio de sesión + Pro para ver.',
  'share.login.required': 'Este es un prompt Pro. Inicia sesión para verlo.',
  'share.pro.required': 'Este es un prompt Pro. Activa Pro para verlo.',

  /* ---- Avatar ---- */
  'avatar.title': 'Elige Tu Avatar',
  'avatar.desc': 'Los avatares gratuitos siempre están disponibles. Los avatares Pro requieren Pro. Los avatares de nivel se desbloquean al subir de nivel. Los avatares de monedas se pueden comprar con monedas.',

  /* ---- Friends ---- */
  'friends.title': 'Amigos',
  'friends.add': '+ Agregar',
  'friends.email.placeholder': 'Correo del amigo',
  'friends.sendrequest': 'Enviar solicitud',
  'friends.chat.placeholder': 'Escribe un mensaje...',

  /* ---- Variant groups ---- */
  'variant.depth': 'Profundidad',
  'variant.length': 'Longitud',
  'variant.format': 'Formato',
  'variant.tone': 'Tono',
  'variant.perspective': 'Perspectiva',

  /* ---- 40 Variant style names ---- */
  'variant.v0': 'Estándar',
  'variant.v1': 'En profundidad',
  'variant.v2': 'Rápido',
  'variant.v3': 'Para principiantes',
  'variant.v4': 'Revisión experta',
  'variant.v5': '3 opciones',
  'variant.v6': 'Una frase',
  'variant.v7': 'Resumen + detalle',
  'variant.v8': 'Completo',
  'variant.v9': 'Viñetas',
  'variant.v10': 'Pasos numerados',
  'variant.v11': 'Tabla',
  'variant.v12': 'Lista de verificación',
  'variant.v13': 'Formato P&R',
  'variant.v14': 'Pros y contras',
  'variant.v15': 'Profesional',
  'variant.v16': 'Amigable y casual',
  'variant.v17': 'Persuasivo',
  'variant.v18': 'Empático',
  'variant.v19': 'Ingenioso',
  'variant.v20': 'Abogado del diablo',
  'variant.v21': 'Socrático',
  'variant.v22': 'Con ejemplos',
  'variant.v23': 'Plan de acción',
  'variant.v24': 'Explica como a un niño',
  'variant.v25': 'Mostrar razonamiento',
  'variant.v26': 'Critica y mejora',
  'variant.v27': 'Respuesta de dos líneas',
  'variant.v28': 'Inmersión exhaustiva',
  'variant.v29': 'Esquema de mapa mental',
  'variant.v30': 'Formato de correo',
  'variant.v31': 'Guión / diálogo',
  'variant.v32': 'Esquema de diapositivas',
  'variant.v33': 'Ejemplo anotado',
  'variant.v34': 'Motivacional',
  'variant.v35': 'Directo y sin rodeos',
  'variant.v36': 'Académico',
  'variant.v37': 'Narrador',
  'variant.v38': 'Fortalecer ambos lados',
  'variant.v39': 'Consejo del yo futuro',

  /* ---- 40 Variant wrapper prompts (Spanish) ---- */
  'vw.v1': 'Quiero una respuesta exhaustiva y de nivel experto.\n\n',
  'vw.v1.suffix': '\n\nIncluye ejemplos concretos, errores comunes a evitar y casos extremos. Explica brevemente el razonamiento detrás de tus principales recomendaciones.',
  'vw.v2': 'Dame una respuesta rápida, sin relleno — viñetas concisas, sin introducción ni conclusión.\n\n',
  'vw.v3.pre': 'Soy nuevo en esto, así que mantenlo simple y alentador.\n\n',
  'vw.v3.suffix': '\n\nEvita la jerga (o explícala en palabras simples), y termina con lo más importante que debo recordar.',
  'vw.v4.pre': 'Actúa como un experto senior en ',
  'vw.v4.mid': '.\n\n',
  'vw.v4.suffix': '\n\nLuego desafía mi enfoque: ¿qué me falta, y qué haría diferente un experto de primer nivel?',
  'vw.v5.suffix': '\n\nDame 3 versiones o enfoques claramente diferentes. Etiqueta cada uno, luego recomienda cuál se adapta mejor y por qué.',
  'vw.v6.suffix': '\n\nResponde en una sola frase bien elaborada.',
  'vw.v7.suffix': '\n\nComienza con un resumen de una línea, luego da la respuesta completa debajo.',
  'vw.v8.pre': 'Dame una respuesta completa, sin dejar nada fuera.\n\n',
  'vw.v8.suffix': '\n\nCubre cada ángulo relevante, subcaso y consideración en profundidad.',
  'vw.v9.suffix': '\n\nFormatea toda la respuesta como viñetas claras — sin párrafos largos.',
  'vw.v10.suffix': '\n\nDa la respuesta como pasos numerados en orden.',
  'vw.v11.suffix': '\n\nOrganiza la respuesta como una tabla clara con columnas bien elegidas.',
  'vw.v12.suffix': '\n\nDa la respuesta como una lista de verificación de elementos concretos que pueda marcar.',
  'vw.v13.suffix': '\n\nEstructura la respuesta como una serie de preguntas probables con respuestas claras.',
  'vw.v14.suffix': '\n\nPresenta claramente los pros y contras, luego da un veredicto final con razonamiento.',
  'vw.v15.pre': 'Usa un tono pulido y profesional.\n\n',
  'vw.v16.pre': 'Usa un tono cálido, amigable y conversacional, como un amigo útil.\n\n',
  'vw.v17.pre': 'Usa un tono seguro y persuasivo que presente un caso convincente.\n\n',
  'vw.v18.pre': 'Usa un tono cálido, empático y de apoyo.\n\n',
  'vw.v19.pre': 'Usa un tono ligero e ingenioso con un toque de humor — pero mantente genuinamente útil.\n\n',
  'vw.v20.suffix': '\n\nLuego argumenta el lado opuesto: encuentra los agujeros en la respuesta obvia y muestra qué podría salir mal.',
  'vw.v21.pre': 'Antes de responder, hazme las preguntas clave que necesitas para dar la mejor respuesta posible. Espera mis respuestas, luego responde.\n\n',
  'vw.v22.suffix': '\n\nIlustra cada punto clave con un ejemplo concreto del mundo real.',
  'vw.v23.suffix': '\n\nTermina con un plan de acción claro y priorizado: qué hacer primero, después y luego.',
  'vw.v24.pre': 'Explica esto como si yo tuviera 5 años — palabras muy simples y una analogía divertida.\n\n',
  'vw.v25.suffix': '\n\nMuestra tu razonamiento paso a paso antes de dar la respuesta final.',
  'vw.v26.suffix': '\n\nDa la respuesta, luego critícala tú mismo y proporciona una versión mejorada.',
  'vw.v27.suffix': '\n\nResponde en no más de dos líneas.',
  'vw.v28.pre': 'Dame una inmersión exhaustiva de nivel experto — sin reservas.\n\n',
  'vw.v29.suffix': '\n\nEstructura la respuesta como un esquema de mapa mental con sangría.',
  'vw.v30.suffix': '\n\nEscribe la respuesta como un correo listo para enviar, con una línea de asunto.',
  'vw.v31.suffix': '\n\nEscribe la respuesta como un guión o diálogo.',
  'vw.v32.suffix': '\n\nEstructura la respuesta como un esquema de presentación diapositiva por diapositiva.',
  'vw.v33.suffix': '\n\nDa un ejemplo trabajado y anota por qué funciona cada parte.',
  'vw.v34.pre': 'Usa un tono alentador y motivacional.\n\n',
  'vw.v35.pre': 'Sé directo y sin rodeos — sin ambages, sin relleno.\n\n',
  'vw.v36.pre': 'Usa un tono académico y preciso.\n\n',
  'vw.v37.pre': 'Responde a través de una historia corta o narrativa.\n\n',
  'vw.v38.suffix': '\n\nPresenta la versión más fuerte de cada lado antes de concluir.',
  'vw.v39.suffix': '\n\nResponde como mi yo futuro más sabio dándome consejo.',

  /* ---- Activate Modal ---- */
  'activate.title': 'Activar PromptRunic Pro',
  'activate.desc': 'Ingresa tu código para desbloquear los más de 700,000+ prompts. Soporta todos los planes Pro y paquetes de monedas.',
  'activate.login.title': 'Cuenta requerida',
  'activate.login.desc': 'Para usar Pro, debes iniciar sesión con una cuenta registrada o continuar con Google/GitHub. Tu membresía Pro está vinculada a tu cuenta y se sincroniza en todos los dispositivos.',
  'activate.login.btn': 'Iniciar sesión / Crear cuenta',
  'activate.login.required': 'Por favor inicia sesión primero. Pro requiere una cuenta registrada o inicio de sesión con Google/GitHub.',
  'activate.trial.removed': 'La prueba gratuita de 3 días ha sido descontinuada. Por favor elige un plan de membresía desde $0.99 por 3 días.',
  'activate.code.label': 'Ingresa tu código de activación',
  'activate.code.placeholder': 'ej. 8B7C-4FA2-9D11-...',
  'activate.redeem': 'Activar',
  'activate.buy': 'Ver planes de membresía',
  'activate.note': 'Cada código de activación solo puede usarse una vez. Pro y monedas están vinculados a tu cuenta y se sincronizan en todos los dispositivos.',
  'activate.entercode': 'Por favor ingresa tu código de activación.',
  'activate.checking': 'Verificando…',
  'activate.notready': 'La activación aún no está lista. Por favor intenta de nuevo en un momento.',
  'activate.unlocked': 'Pro desbloqueado. ¡Disfruta la biblioteca completa de prompts!',
  'activate.coincode': 'Ese es un código de monedas — {n} monedas añadidas. Para Pro, usa un código de activación Pro.',
  'activate.notpro': 'Ese código es válido, pero no es un código de activación Pro.',
  'activate.network': 'No se pudo conectar al servidor de activación. Verifica tu conexión e intenta de nuevo.',
  'activate.invalid': 'Código inválido. Revisa el código en el correo de recibo de Lemon Squeezy.',
  'activate.testmode': 'Desbloqueo en modo PRUEBA — los clientes usan un código real de Lemon Squeezy.',
  'activate.alreadypro': 'Ya tienes acceso completo a Pro — no necesitas prueba.',
  'activate.trialused': 'Tu prueba gratuita ya ha sido utilizada.',
  'activate.trialactive': 'Pro está activo — disfruta los {n} prompts!', 
  'activate.pro.unlocked': '¡PromptRunic Pro desbloqueado!',
  'activate.trial.unlocked': 'Pro desbloqueado!',
  'activate.unlocked.sub': 'Pro desbloqueado por {d} días. ¡Disfruta la biblioteca completa de prompts!',
  'activate.promo.14d': '¡Pro de 14 días activado! Disfruta los 700,000+ prompts.',
  'activate.promo.1m': '¡Pro de 1 mes activado! Disfruta los 700,000+ prompts.',
  'activate.promo.5000c': '¡5,000 monedas añadidas a tu cuenta!',
  'activate.promo.used': 'Este código promocional ya ha sido usado en esta cuenta.',
  'activate.code.used': 'Este código de activación ya ha sido usado en tu cuenta. Cada código solo puede activarse una vez.',
  'activate.code.used.other': 'Este código de activación ya ha sido usado y activado. Cada código solo puede usarse una vez.',
  'activate.limit': 'Esta clave de licencia ha alcanzado su límite de activación. Si ya la activaste en otro dispositivo, desactívala allí primero, o contacta soporte.',

  /* ---- Auth Modal ---- */
  'auth.signin.title': 'Iniciar sesión en PromptRunic',
  'auth.register.title': 'Crea tu cuenta',
  'auth.signin.tab': 'Iniciar sesión',
  'auth.register.tab': 'Crear cuenta',
  'auth.email': 'Correo electrónico',
  'auth.email.placeholder': 'tú@ejemplo.com',
  'auth.password': 'Contraseña',
  'auth.password.placeholder': 'Al menos 6 caracteres',
  'auth.optin': 'Envíame ocasionalmente actualizaciones del producto y nuevos paquetes de prompts.',
  'auth.submit.signin': 'Iniciar sesión',
  'auth.submit.register': 'Crear cuenta',
  'auth.divider': 'o continúa con',
  'auth.google': 'Continuar con Google',
  'auth.github': 'Continuar con GitHub',
  'auth.reset': 'Enviar correo de restablecimiento',
  'auth.forgot': '¿Olvidaste tu contraseña?',
  'auth.entercredentials': 'Por favor ingresa tu correo y contraseña.',
  'auth.pleasewait': 'Por favor espera…',
  'auth.account.created': 'Cuenta creada — ¡bienvenido!',
  'auth.signedin': 'Sesión iniciada — ¡bienvenido de nuevo!',
  'auth.signedout': 'Sesión cerrada',
  'auth.notsetup': 'El inicio de sesión de cuenta no está configurado aún. Consulta FIREBASE-SETUP.md para habilitarlo.',
  'auth.resetplaceholder': 'Ingresa tu correo arriba primero, luego presiona restablecer.',
  'auth.resetsent': 'Correo de restablecimiento de contraseña enviado — revisa tu bandeja de entrada.',
  'auth.opening': 'Abriendo {which}…',
  'auth.welcome': 'Sesión iniciada — ¡bienvenido!',

  /* ---- Auth errors ---- */
  'auth.err.email-in-use': 'Ese correo ya está registrado — cambia a "Iniciar sesión".',
  'auth.err.invalid-email': 'Esa dirección de correo parece inválida.',
  'auth.err.weak-password': 'La contraseña es demasiado débil — usa al menos 6 caracteres.',
  'auth.err.wrong-password': 'Contraseña incorrecta. Intenta de nuevo o restablécela abajo.',
  'auth.err.user-not-found': 'No hay cuenta con ese correo — crea una en su lugar.',
  'auth.err.invalid-credential': 'Correo o contraseña incorrectos.',
  'auth.err.missing-password': 'Por favor ingresa una contraseña.',
  'auth.err.popup-closed': 'La ventana de inicio de sesión se cerró antes de terminar.',
  'auth.err.cancelled': 'El inicio de sesión fue cancelado.',
  'auth.err.popup-blocked': 'Tu navegador bloqueó la ventana emergente — permite ventanas emergentes para este sitio e intenta de nuevo.',
  'auth.err.account-exists': 'Este correo ya está vinculado a un método de inicio de sesión diferente.',
  'auth.err.too-many': 'Demasiados intentos — por favor espera un momento e intenta de nuevo.',
  'auth.err.network': 'Error de red — verifica tu conexión e intenta de nuevo.',
  'auth.err.not-allowed': 'Este método de inicio de sesión no está habilitado en Firebase aún.',
  'auth.err.default': 'Algo salió mal. Por favor intenta de nuevo.',

  /* ---- Account Modal ---- */
  'account.title': 'Tu cuenta',
  'account.desc': 'Tus favoritos y acceso Pro se sincronizan automáticamente en todos los dispositivos donde inicies sesión.',
  'account.signedin': 'Sesión iniciada como',
  'account.method': 'Método de inicio de sesión',
  'account.plan': 'Plan',
  'account.favs': 'Favoritos guardados',
  'account.profile': 'CONFIGURACIÓN DEL PERFIL',
  'account.displayname': 'Nombre para mostrar',
  'account.displayname.placeholder': 'Tu nombre',
  'account.bio': 'Breve biografía',
  'account.bio.placeholder': 'Una o dos líneas sobre ti',
  'account.newpassword': 'Nueva contraseña (dejar en blanco para mantener la actual)',
  'account.save': 'Guardar cambios',
  'account.signout': 'Cerrar sesión',
  'account.getpro': 'Obtener Pro',
  'account.saving': 'Guardando…',
  'account.saved': 'Guardado.',
  'account.saved.pw': 'Guardado — tu contraseña fue actualizada.',
  'account.pw.tooshort': 'La nueva contraseña debe tener al menos 6 caracteres.',
  'account.recentlogin': 'Para cambiar tu contraseña, cierra sesión y vuelve a iniciar, luego intenta de nuevo.',
  'account.saved.count': '{n} guardados',

  /* ---- Plan badge ---- */
  'plan.free': 'GRATIS',
  'plan.pro': 'PRO',
  'plan.pro.days': 'PRO · {d}d restantes',
  'plan.pro.trial': 'PRO · {d}d restantes',
  'plan.pro.full': 'Pro — acceso completo',
  'plan.pro.trial.label': 'Pro — {d} día{s} restantes',

  /* ---- Upsell ---- */
  'upsell.title': 'Elige tu plan Pro',
  'upsell.desc': 'Desbloquea los más de 700,000+ prompts en 1,684 categorías — escritura, marketing, ventas, carrera, programación, fundamentos de IA, crianza, viajes y más. Planes flexibles para tus necesidades.',
  'upsell.feat1': '✓ 700,000+ prompts',
  'upsell.feat2': '✓ 1,684 categorías',
  'upsell.feat3': '✓ 40 estilos de respuesta',
  'upsell.feat4': '✓ Todos los asistentes de IA',
  'upsell.buy': 'Obtener membresía Pro',
  'upsell.havecode': 'Ya tengo un código',
  'upsell.note': 'Todos los planes incluyen acceso completo a 700,000+ prompts, 40 estilos de respuesta y todos los asistentes de IA. Las suscripciones se renuevan automáticamente — cancela en cualquier momento. El plan vitalicio es un pago único, tuyo para siempre.',

  /* ---- Pricing Table ---- */
  'pricing.plan': 'Plan',
  'pricing.original': 'Original',
  'pricing.sale': 'Precio oferta',
  'pricing.permonth': 'Por mes',
  'pricing.save': 'Ahorro',
  'pricing.month': 'Mes',
  'pricing.months': 'Meses',
  'pricing.days': 'Días',
  'pricing.billed.3d': 'Cobro único de $0.99',
  'pricing.lifetime': 'Vitalicio',
  'pricing.flexible': 'Prueba flexible',
  'pricing.bestvalue': 'Mejor valor',
  'pricing.onetime': 'Pago único',
  'pricing.payonce': 'Paga una vez, para siempre',
  'pricing.select': 'Seleccionar',
  'pricing.permonth2': '/mes',
  'pricing.forever': 'para siempre',
  'pricing.billed.once': 'Cobro único de $7.99',
  'pricing.billed.3m': 'Cobro de $18 cada 3 meses',
  'pricing.billed.6m': 'Cobro de $29 cada 6 meses',
  'pricing.billed.12m': 'Cobro de $39 al año',
  'pricing.feat.all': 'Acceso completo a 700K+ prompts',
  'pricing.feat.styles': '40 estilos de respuesta',
  'pricing.feat.ai': 'Todos los asistentes de IA',
  'pricing.feat.priority': 'Soporte prioritario',
  'pricing.feat.nosub': 'Sin suscripción',

  /* ---- Footer ---- */
  'footer.tagline': 'PromptRunic — biblioteca de plantillas de prompts de IA',
  'footer.stats': '700,000+ plantillas · 1,600+ categorías',
  'footer.builtby': 'Mantenido por Z. Xie',
  'footer.privacy': 'Política de privacidad',
  'footer.terms': 'Términos de servicio',
  'footer.disclaimer': 'Descargo de responsabilidad: PromptRunic proporciona acceso a modelos de IA de terceros solo con fines informativos. No poseemos, operamos ni controlamos ningún modelo de IA subyacente. Todos los resultados generados por IA pueden ser inexactos, incompletos o sesgados. Usted es el único responsable de verificar cualquier información antes de depender de ella.',
  'footer.affiliation': 'PromptRunic no está afiliado con OpenAI, Anthropic, Microsoft, Google, DeepSeek ni ningún otro proveedor de modelos.',
  'footer.accuracy': 'Precisión de datos: los recuentos de prompts y los números de categorías son aproximados y se actualizan regularmente. Los números reales pueden variar ligeramente.',
  'footer.misuse': 'Usted acepta no usar este sitio para generar: contenido dañino, ilegal o poco ético; contenido que infrinja derechos de terceros; o desinformación, acoso o código malicioso.',
  'footer.rights': 'Todos los derechos reservados.',

  /* ---- Toast messages ---- */
  'toast.copied': 'Prompt copiado al portapapeles',
  'toast.opening': 'Abriendo {ai} con tu prompt…',
  'toast.copypaste': 'Prompt copiado — presiona Ctrl+V en {ai}',
  'toast.trial.ended': 'Tu acceso Pro ha terminado — activa Pro para mantener acceso completo',
  'toast.pro.ended': 'Tu acceso Pro ha terminado — activa Pro para mantener acceso completo',

  /* ---- Fun.js / Gamification ---- */
  'game.levelup': '🎉 ¡Subiste de nivel! Nivel {lvl} — +{coins} 🪙',
  'game.achievement': '🏅 ¡Logro desbloqueado: {name}  (+{xp} XP)',
  'game.daily.complete': '✅ ¡Reto diario completado! +{xp} XP',
  'game.streak': '🔥 ¡{n} días seguidos — bienvenido de nuevo! +{xp} XP',
  'game.mood.locked': '🔒 {n} emojis más se desbloquean al subir de nivel',
  'game.mood.header': 'Estado de ánimo para este prompt',

  /* ---- Backgrounds ---- */
  'bg.choose': 'Elige un fondo',
  'bg.title': 'Fondos',
  'bg.desc.pro': 'Elige cualquier fondo animado — tu elección se guarda en este dispositivo.',
  'bg.desc.free': '5 fondos son gratuitos (PromptRunic AI, Red Cibernética, Reino Cuántico, Constelación y Live Coder). Los otros 9 son función Pro — activa Pro para desbloquearlos.',
  'bg.pro.only': 'Ese fondo es función Pro — activa Pro para usarlo',
  'bg.set': 'Fondo cambiado a {name}',

  /* ---- Community / Social ---- */
  'community.title': 'Comunidad',
  'community.desc': 'Mira a los mejores jugadores y los estados de ánimo que los miembros dejan en los prompts. Toca cualquier jugador para ver su perfil.',
  'community.tab.level': '🏆 Nivel',
  'community.tab.coins': '🪙 Monedas',
  'community.tab.badges': '🏅 Insignias',
  'community.tab.avatars': '🎭 Avatares',
  'community.tab.games': '🎮 Juegos',
  'community.tab.speed': '⏱️ Velocidad',
  'community.tab.mood': '😊 Muro de ánimos',
  'community.loading': 'Cargando tabla de clasificación…',
  'community.empty': 'No hay jugadores en la tabla aún.<br>Inicia sesión y usa PromptRunic — tu perfil aparecerá aquí automáticamente.',
  'community.top50.level': 'Top 50 — nivel más alto y XP',
  'community.top50.coins': 'Top 50 — más monedas',
  'community.top50.badges': '🏅 Top 50 — más insignias desbloqueadas',
  'community.top50.avatars': '🎭 Top 50 — avatares desbloqueados',
  'community.top50.games': 'Top 50 — mejores puntuaciones PROMPT MATRIX',
  'community.top50.speed': 'Top 50 — completaciones más rápidas de PROMPT MATRIX',
  'community.back': '‹ Volver a la tabla de clasificación',
  'community.level': 'nivel',
  'community.totalxp': 'XP total',
  'community.coins': 'monedas',
  'community.achievements': 'logros',
  'community.beststreak': 'mejor racha',
  'community.matrixbest': 'PROMPT MATRIX mejor',
  'community.fastestclear': 'completación más rápida',
  'community.moodwall.loading': 'Cargando el muro de ánimos…',
  'community.moodwall.empty': 'No hay estados de ánimo aún.<br>Abre cualquier prompt, elige un emoji en "Estado de ánimo para este prompt" — aparecerá aquí.',
  'community.moodwall.recent': 'Estados de ánimo recientes de la comunidad',
  'community.mood.others': 'Cómo se sintieron otros sobre este prompt',
  'community.mood.others.count': 'Cómo se sintieron otros sobre este prompt — {n}',
  'community.mood.signin': 'Inicia sesión con Firestore habilitado para ver los estados de ánimo de la comunidad.',
  'community.mood.nobody': 'Nadie más ha establecido un estado de ánimo aquí aún — podrías ser el primero.',
  'community.mood.couldnotload': 'No se pudieron cargar los estados de ánimo de la comunidad.',
  'community.offline': '{what} necesita Firebase Firestore habilitado.<br>Propietario: habilita Firestore y publica las reglas en <code>FIRESTORE-RULES.md</code>.',
  'community.felt': 'sintió',
  'community.on': 'en',
  'community.you': '(tú)',
  'community.member': 'Miembro',

  /* ---- Method names ---- */
  'method.password': 'Correo y contraseña',
  'method.google.com': 'Google',
  'method.github.com': 'GitHub',

  /* ---- Category names ---- */
  'cat.all': 'Todos los prompts',

  /* ---- Data load error ---- */
  'data.loaderror': 'No se pudieron cargar los datos de prompts. Asegúrate de que todos los archivos .js estén en la misma carpeta que index.html y recarga la página.',

  /* ---- Search Dropdown ---- */
  'search.placeholder': "Buscar 700,000+ prompts — prueba 'currículum', 'email frío', 'plan de viaje'...",
  'search.categories': 'Categorías',
  'search.prompts': 'Prompts',
  'search.nomatch': 'No se encontraron categorías o prompts coincidentes.',

  /* ---- Prompt Optimizer ---- */
  'optimizer.title': 'Optimizador de Prompts',
  'optimizer.desc': 'Ingresa tu prompt o idea abajo — lo optimizaremos usando nuestra biblioteca de 700,000+ prompts + IA local opcional.',
  'optimizer.placeholder': "Pega tu prompt o describe lo que necesitas — ej. 'Escribe una carta de presentación para un puesto de ingeniero de software en Google'...",
  'optimizer.quickbtn': '⚡ Optimización rápida',
  'optimizer.aibtn': '🧠 Optimización IA',
  'optimizer.ainotice': '🧠 El primer uso requiere descargar un modelo de IA local (~1GB). Se ejecuta completamente en tu navegador — ningún dato sale de tu dispositivo.',
  'optimizer.searching': 'Optimizando...',
  'optimizer.results': 'Prompts relacionados:',
  'optimizer.results.none': 'No se encontraron coincidencias',
  'optimizer.empty': 'Por favor ingresa un prompt o descripción para optimizar.',
  'optimizer.nomatch': 'No se encontraron prompts relevantes. Prueba con palabras clave diferentes.',
  'optimizer.relevance': 'Relevancia',
  'optimizer.outputlabel': '✨ Prompt optimizado',
  'optimizer.copy': '📋 Copiar',
  'optimizer.send': '→ Enviar a IA',
  'optimizer.loading': 'Cargando modelo IA...',
  'optimizer.loadstart': 'Inicializando motor IA...',
  'optimizer.downloading': 'Descargando modelo Qwen2.5-1.5B...',
  'optimizer.running': 'Optimizando con IA...',
  'optimizer.nogpu': 'Tu navegador no soporta WebGPU. Prueba Chrome 113+.',
  'optimizer.aierror': 'Optimización IA fallida. Usando optimización rápida.',
  'optimizer.intent': 'Intención',
  'optimizer.keywords': 'Palabras clave',
  'optimizer.matched': 'Coincidentes',
  'optimizer.prompts': 'prompts',
  'optimizer.ailoaded': 'Modelo de IA cargado. Ahora puedes usarlo en todo el sitio.',
  'optimizer.keywords.label': '🔍 Palabras clave sugeridas (clic para buscar)',
  'optimizer.refine.title': '🧠 Refina tu Prompt',
  'optimizer.refine.placeholder': 'Dile a la IA cómo ajustar tu prompt...',
  'optimizer.refine.send': 'Refinar',

  /* ---- AI Selector Popup ---- */
  'aisel.title': 'Enviar a IA',
  'aisel.subtitle': 'Elige un servicio de IA — tu prompt optimizado será copiado y enviado:',

  /* ---- Consultation Chat ---- */
  'consult.title': 'Asistente PromptRunic',
  'consult.greeting': '¡Hola! Soy tu asistente de PromptRunic. Pregúntame lo que quieras sobre el sitio web — cómo usar prompts, encontrar categorías, optimizar tus prompts o navegar el sitio.',
  'consult.placeholder': 'Pregunta sobre PromptRunic...',
  'consult.send': 'Enviar',

  /* ---- Global AI Badge ---- */
  'badge.ai.ready': 'IA Lista',

  /* ---- Hero Chat Demo ---- */
  'demo.title': 'PromptRunic — enviando un prompt a una IA',
  'demo.q1': 'Escribe un email frío a un cliente potencial',
  'demo.a1': 'Asunto: Una idea rápida para {Empresa}\n\nHola Alex — noté que tu equipo acaba de lanzar X. Aquí hay una forma de…',
  'demo.q2': 'Planifica un viaje de 5 días a Japón con presupuesto',
  'demo.a2': 'Día 1 — Tokio: Asakusa + comida callejera. Día 2 — excursión a Nikko…\nPresupuesto aproximado: vuelos, alojamiento, pase de tren…',
  'demo.q3': 'Explica el interés compuesto como si fuera nuevo',
  'demo.a3': 'Imagina una bola de nieve rodando cuesta abajo — crece más rápido cuanto más grande se hace. Tu dinero hace lo mismo…',
  'demo.q4': 'Haz que esta línea de currículum suene más fuerte',
  'demo.a4': '"Manejé un equipo" se convierte en "Lideré un equipo de 6 personas para lanzar 3 productos, reduciendo costos un 20%".',
  'demo.q5': 'Escribe una descripción de producto para una botella ecológica',
  'demo.a5': 'Conoce la botella que retribuye — acero inoxidable 100% reciclado, mantiene bebidas frías 24h…',
  'demo.q6': 'Resume este informe de 3 páginas en 5 puntos',
  'demo.a6': '• Ingresos +12% interanual  • Tasa de abandono bajó a 3.2%  • Nuevo mercado: Sudeste Asiático…',
  'demo.q7': 'Redacta un email de seguimiento después de una entrevista',
  'demo.a7': 'Hola Sarah — gracias por la conversación de hoy. Disfruté conocer sobre el equipo…',
  'demo.q8': 'Crea un plan de comidas semanal vegetariano',
  'demo.a8': 'Lunes: curry de garbanzos + arroz integral. Martes: tacos de frijoles negros con salsa de mango…',
  'demo.q9': 'Convierte estas notas de reunión en acciones',
  'demo.a9': '1. @Alex: finalizar spec de API para el viernes  2. @Mia: programar prueba de usuarios…',
  'demo.q10': 'Escribe un pie de foto para una foto de atardecer',
  'demo.a10': 'Hora dorada, vibras doradas. Donde el cielo pinta su propia obra maestra…',
  'demo.q11': 'Explica blockchain a un niño de 10 años',
  'demo.a11': 'Imagina un cuaderno que todos pueden leer pero nadie puede borrar — cada página es permanente…',
  'demo.q12': 'Escribe una función Python que ordene una lista de diccionarios por clave',
  'demo.a12': 'def sort_by_key(items, key):\n  return sorted(items, key=lambda x: x[key])',
  'demo.q13': 'Redacta un email de disculpa por un envío retrasado',
  'demo.a13': 'Estimado cliente — su pedido tiene 2 días de retraso por un problema logístico. Hemos…',
  'demo.q14': 'Brainstorm de 10 nombres para una app de cuidado de mascotas',
  'demo.a14': '1. PawStay  2. FidoWatch  3. PetNest  4. CritterCare  5. WhiskerKeep…',
  'demo.q15': 'Reescribe este párrafo en tono profesional',
  'demo.a15': 'Original: "Esta cosa es medio difícil de usar." → Revisado: "La interfaz actual presenta…',
  'demo.q16': 'Crea un plan de ejercicio para principiantes en casa',
  'demo.a16': 'Semana 1 — 3 días/semana: 10 sentadillas, 10 flexiones (rodillas OK), 30s plancha…',
  'demo.q17': 'Escribe un post de LinkedIn sobre un cambio de carrera a tecnología',
  'demo.a17': 'Hace seis meses no sabía escribir una línea de código. Hoy lancé mi primera app…',
  'demo.q18': 'Compara GPT-4, Claude y Gemini para tareas de programación',
  'demo.a18': 'GPT-4: fuerte en razonamiento complejo, verboso. Claude: cuidadoso, genial en refactorización…',
  'demo.q19': 'Traduce "gracias por tu paciencia" a 5 idiomas',
  'demo.a19': 'Francés: Merci pour votre patience  Inglés: Thank you for your patience…',
  'demo.q20': 'Escribe un poema corto sobre el océano de noche',
  'demo.a20': 'La marea susurra secretos a la orilla, la luz de la luna baila sobre las olas…',
  'demo.q21': 'Ayúdame a esbozar una presentación de 10 diapositivas para una startup',
  'demo.a21': 'Diapositiva 1: Gancho + visión  2: Problema  3: Solución  4: Demo  5: Tamaño de mercado…',

  /* ---- Friends / Chat panel ---- */
  'friends.no.requests': 'Sin solicitudes pendientes',
  'friends.requests': 'Solicitudes de amistad',
  'friends.load.error': 'No se pudieron cargar las solicitudes',
  'friends.accept': 'Aceptar',
  'friends.decline': 'Rechazar',
  'friends.withdraw': 'Retirar',
  'friends.sent': 'Enviado',
  'friends.load.error.list': 'No se pudo cargar la lista de amigos.<br>Inténtalo de nuevo más tarde.',
  'friends.no.friends': 'Aún no tienes amigos.',
  'friends.no.friends.hint': '¡Ve a la pestaña Descubrir para encontrar y agregar amigos!',
  'friends.signin': 'Inicia sesión para ver amigos',
  'friends.signin.chats': 'Inicia sesión para ver chats',
  'friends.no.conversations': 'Aún no hay conversaciones.',
  'friends.no.conversations.hint': '¡Comienza un chat desde Contactos!',
  'friends.conv.error': 'No se pudieron cargar las conversaciones',
  'friends.no.messages': 'Aún no hay mensajes. ¡Saluda!',
  'friends.loading.messages': 'Cargando mensajes...',
  'friends.chat': 'Chat',
  'friends.online': 'En línea',
  'friends.offline': 'Desconectado',
  'friends.discover': 'Descubrir',
  'friends.contacts': 'Contactos',
  'friends.chats': 'Chats',
  'friends.no.suggestions': 'Aún no hay sugerencias',
  'friends.already.friends': 'Ya son amigos',
  'friends.request.received': 'Solicitud recibida',
  'friends.profile.error': 'No se pudo cargar el perfil',
  'friends.send.error': 'Error al enviar la solicitud',
  'friends.request.sent': 'Solicitud de amistad enviada a',
  'friends.cannot.add.self': 'No puedes agregarte a ti mismo',
  'friends.request.already.sent': 'Solicitud ya enviada',
  'friends.already.friends.short': 'Ya son amigos',
  'friends.reverse.request': 'Este usuario ya te envió una solicitud',
  'friends.accept.error': 'Error al aceptar la solicitud',
  'friends.now.friend': '¡ahora es tu amigo!',
  'friends.withdrawn': 'Solicitud de amistad retirada'
};

if(typeof window.PPI18n!=='undefined') window.PPI18n.registerDict('es', ES);
window._LANG_ES = ES;

})();
