/* =====================================================================
 * PromptRunic — lang-en.js  (English translations)
 * Register English dictionary with the i18n engine.
 * ===================================================================== */
(function(){
'use strict';

var EN = {
  /* ---- Header ---- */
  'header.prompts': 'Prompts',
  'header.guide': 'Beginner Guide',
  'header.activate': 'Activate code',
  'header.signin': 'Sign in',
  'header.game': 'Game',
  'header.getpro': 'Get Pro',
  'header.community': 'Community',

  /* ---- Hero ---- */
  'hero.h1.prefix': 'PromptRunic',
  'hero.h1.grad': 'Your AI Prompt Generator & AI Helper',
  'hero.h1.suffix': '<br/>700,000+ AI prompts, fire any of them in one click.',
  'hero.p': '{freeN} prompts are free to use right now — unlock all {totalN} with a Pro activation code. PromptRunic is your AI mate for writing, coding, marketing & more. New to AI? We teach you how to ask.',

  /* ---- CTA ---- */
  'cta.browse': 'Browse Prompts',
  'cta.unlock': 'Get Pro — from $0.99',
  'cta.play': '🎮 Play Game',

  /* ---- Stats ---- */
  'stat.prompts': 'ready-to-use prompts',
  'stat.categories': 'categories',
  'stat.styles': 'answer styles',
  'stat.assistants': 'AI assistants',

  /* ---- Universe ---- */
  'universe.eyebrow': 'PromptRunic Universe',
  'universe.title': 'A whole galaxy of prompts.\nOne launchpad.',
  'universe.sub': '700,000 ready-to-use prompts across 1,684 categories — writing, coding, marketing, learning, parenting, travel, and a lot more. Pick one, fill the blanks, fire it to your AI.',
  'universe.cta': 'Enter the library ›',

  /* ---- Guide ---- */
  'guide.title': 'New to AI? The whole skill in 2 minutes.',
  'guide.sub': 'An AI\'s answer is only as good as your prompt. Here is the recipe every PromptRunic prompt is already built on — you just fill in the blanks.',
  'guide.step1': '1 · Role',
  'guide.step1.desc': 'Tell the AI who to be — "Act as an experienced career coach…"',
  'guide.step2': '2 · Task',
  'guide.step2.desc': 'Say exactly what you want done.',
  'guide.step3': '3 · Context',
  'guide.step3.desc': 'Give real details: names, numbers, your situation.',
  'guide.step4': '4 · Format',
  'guide.step4.desc': 'How you want the answer — a table, 5 bullets, an email.',
  'guide.step5': '5 · Constraints',
  'guide.step5.desc': 'Limits and tone — "Under 150 words, friendly, no jargon."',
  'guide.weak': 'Weak prompt',
  'guide.weak.example': '"Write a resume."',
  'guide.strong': 'Strong prompt',
  'guide.strong.example': '"Act as a professional resume writer. Rewrite my experience as a marketing manager into 5 achievement bullets with measurable results. One page, confident but not boastful."',
  'guide.tip': 'Tip: open the <strong>AI Basics</strong> category below — those prompts are coaching tools that turn your rough idea into a great prompt.',

  /* ---- Search ---- */
  'search.placeholder': "Search 700,000+ prompts — try 'resume', 'cold email', 'trip plan'...",

  /* ---- Sidebar ---- */
  'sidebar.library': 'Library',
  'sidebar.you': 'You',
  'sidebar.all': 'All Prompts',
  'sidebar.favorites': '★ Favorites',

  /* ---- Grid ---- */
  'grid.locked': '🔒 PRO',
  'grid.free': 'FREE',
  'grid.noprompts': 'No prompts here yet.',
  'grid.noprompts.fav': ' Star a prompt to save it.',
  'grid.showmore': 'Show more',
  'grid.prompt.s': ' prompts',
  'grid.prompt': ' prompt',
  'grid.locked.count': ' locked (activate Pro to unlock)',
  'grid.showing': ' · showing ',

  /* ---- Prompt Modal ---- */
  'pm.tip': '💡 Tip: the more specific you are in the blanks below, the better the answer. Add real names, numbers and context.',
  'pm.style.label': 'Answer style — pick the kind of reply you want:',
  'pm.output.label': 'Your finished prompt',
  'pm.copy': 'Copy prompt',
  'pm.fav.save': '☆ Save to favorites',
  'pm.fav.saved': '★ Saved',
  'pm.noblanks': 'This prompt has no blanks — just copy it or send it to an AI.',
  'pm.ai.label': 'Send straight to an AI — the prompt is copied and the AI opens:',
  'pm.ai.note': 'ChatGPT and Claude auto-fill the prompt from the link. For Copilot, Gemini and DeepSeek, press <strong>Ctrl+V</strong> to paste — it is already on your clipboard. True one-click auto-fill on every AI, plus two built-in local AIs, are in the PromptRunic desktop app.',

  /* ---- Variant groups ---- */
  'variant.depth': 'Depth',
  'variant.length': 'Length',
  'variant.format': 'Format',
  'variant.tone': 'Tone',
  'variant.perspective': 'Perspective',

  /* ---- 40 Variant style names ---- */
  'variant.v0': 'Standard',
  'variant.v1': 'In-depth',
  'variant.v2': 'Quick',
  'variant.v3': 'Beginner-friendly',
  'variant.v4': 'Expert review',
  'variant.v5': '3 options',
  'variant.v6': 'One sentence',
  'variant.v7': 'TL;DR + detail',
  'variant.v8': 'Comprehensive',
  'variant.v9': 'Bullet points',
  'variant.v10': 'Numbered steps',
  'variant.v11': 'Table',
  'variant.v12': 'Checklist',
  'variant.v13': 'Q&A format',
  'variant.v14': 'Pros & cons',
  'variant.v15': 'Professional',
  'variant.v16': 'Friendly & casual',
  'variant.v17': 'Persuasive',
  'variant.v18': 'Empathetic',
  'variant.v19': 'Witty',
  'variant.v20': "Devil's advocate",
  'variant.v21': 'Socratic',
  'variant.v22': 'With examples',
  'variant.v23': 'Action plan',
  'variant.v24': 'ELI5',
  'variant.v25': 'Show reasoning',
  'variant.v26': 'Critique & improve',
  'variant.v27': 'Two-line answer',
  'variant.v28': 'Exhaustive deep-dive',
  'variant.v29': 'Mind-map outline',
  'variant.v30': 'Email format',
  'variant.v31': 'Script / dialogue',
  'variant.v32': 'Slide outline',
  'variant.v33': 'Annotated example',
  'variant.v34': 'Motivational',
  'variant.v35': 'Blunt & direct',
  'variant.v36': 'Academic',
  'variant.v37': 'Storyteller',
  'variant.v38': 'Steelman both sides',
  'variant.v39': 'Future-self advice',

  /* ---- 40 Variant wrapper prompts (English) ---- */
  'vw.v1': 'I want a thorough, expert-level answer.\n\n',
  'vw.v1.suffix': '\n\nInclude concrete examples, common mistakes to avoid, and edge cases. Briefly explain the reasoning behind your main recommendations.',
  'vw.v2': 'Give me a fast, no-fluff answer - tight bullet points, no intro or conclusion.\n\n',
  'vw.v3.pre': 'I am new to this, so keep it simple and encouraging.\n\n',
  'vw.v3.suffix': '\n\nAvoid jargon (or explain it in plain words), and end with the single most important thing to remember.',
  'vw.v4.pre': 'Act as a senior ',
  'vw.v4.mid': ' expert.\n\n',
  'vw.v4.suffix': '\n\nThen challenge my framing: what am I missing, and what would a top expert do differently?',
  'vw.v5.suffix': '\n\nGive me 3 clearly different versions or approaches. Label each, then recommend which fits best and why.',
  'vw.v6.suffix': '\n\nAnswer in a single, well-crafted sentence.',
  'vw.v7.suffix': '\n\nStart with a one-line TL;DR, then give the full answer below it.',
  'vw.v8.pre': 'Give me a comprehensive, leave-nothing-out answer.\n\n',
  'vw.v8.suffix': '\n\nCover every relevant angle, sub-case and consideration in depth.',
  'vw.v9.suffix': '\n\nFormat the whole answer as clear bullet points - no long paragraphs.',
  'vw.v10.suffix': '\n\nGive the answer as numbered, do-this-then-that steps in order.',
  'vw.v11.suffix': '\n\nOrganize the answer as a clear table with well-chosen columns.',
  'vw.v12.suffix': '\n\nGive the answer as a checklist of concrete items I can tick off.',
  'vw.v13.suffix': '\n\nStructure the answer as a series of likely questions with clear answers.',
  'vw.v14.suffix': '\n\nLay out the pros and cons clearly, then give a final verdict with reasoning.',
  'vw.v15.pre': 'Use a polished, professional tone.\n\n',
  'vw.v16.pre': 'Use a warm, friendly, conversational tone, like a helpful friend.\n\n',
  'vw.v17.pre': 'Use a confident, persuasive tone that makes a compelling case.\n\n',
  'vw.v18.pre': 'Use a warm, empathetic and supportive tone.\n\n',
  'vw.v19.pre': 'Use a light, witty tone with a touch of humor - but stay genuinely useful.\n\n',
  'vw.v20.suffix': '\n\nThen argue the opposite side: poke holes in the obvious answer and show what could go wrong.',
  'vw.v21.pre': 'Before answering, ask me the key questions you need to give the best possible answer. Wait for my replies, then answer.\n\n',
  'vw.v22.suffix': '\n\nIllustrate every key point with a concrete, real-world example.',
  'vw.v23.suffix': '\n\nEnd with a clear, prioritized action plan: what to do first, next and later.',
  'vw.v24.pre': 'Explain this as if I am 5 years old - very simple words and a fun analogy.\n\n',
  'vw.v25.suffix': '\n\nShow your step-by-step reasoning before giving the final answer.',
  'vw.v26.suffix': '\n\nGive the answer, then critique it yourself and provide an improved version.',
  'vw.v27.suffix': '\n\nAnswer in no more than two lines.',
  'vw.v28.pre': 'Give an exhaustive, expert-level deep-dive - hold nothing back.\n\n',
  'vw.v29.suffix': '\n\nStructure the answer as an indented mind-map style outline.',
  'vw.v30.suffix': '\n\nWrite the answer as a ready-to-send email, with a subject line.',
  'vw.v31.suffix': '\n\nWrite the answer as a script or dialogue.',
  'vw.v32.suffix': '\n\nStructure the answer as a slide-by-slide presentation outline.',
  'vw.v33.suffix': '\n\nGive one worked example and annotate why each part works.',
  'vw.v34.pre': 'Use an encouraging, motivational tone.\n\n',
  'vw.v35.pre': 'Be blunt and direct - no hedging, no padding.\n\n',
  'vw.v36.pre': 'Use a precise, academic tone.\n\n',
  'vw.v37.pre': 'Answer through a short story or narrative.\n\n',
  'vw.v38.suffix': '\n\nPresent the strongest version of each side before concluding.',
  'vw.v39.suffix': '\n\nAnswer as my wiser future self giving me advice.',

  /* ---- Activate Modal ---- */
  'activate.title': 'Activate PromptRunic Pro',
  'activate.desc': 'Unlock all 700,000+ prompts on this site.',
  'activate.login.title': 'Account Required',
  'activate.login.desc': 'To use Pro, you must be signed in with a registered account or continue with Google/GitHub. Your Pro membership is linked to your account and syncs across all devices.',
  'activate.login.btn': 'Sign in / Create account',
  'activate.login.required': 'Please sign in first. Pro requires a registered account or Google/GitHub login.',
  'activate.trial.removed': 'The free 3-day trial has been discontinued. Please choose a membership plan starting at $0.99 for 3 days.',
  'activate.code.label': 'Enter your activation code',
  'activate.code.placeholder': 'e.g. 8B7C-4FA2-9D11-...',
  'activate.redeem': 'Activate',
  'activate.buy': 'View membership plans',
  'activate.note': 'Pro is linked to your account. Sign in to activate and sync your Pro access across all devices.',
  'activate.entercode': 'Please enter your activation code.',
  'activate.checking': 'Checking…',
  'activate.notready': 'Activation is not ready yet. Please try again in a moment.',
  'activate.unlocked': 'Pro unlocked. Enjoy the full prompt library!',
  'activate.coincode': 'That is a coin code — {n} coins added. For Pro, use a Pro activation code.',
  'activate.notpro': 'That code is valid, but it is not a Pro activation code.',
  'activate.network': 'Could not reach the activation server. Check your connection and try again.',
  'activate.invalid': 'Invalid code. Check the code in your Lemon Squeezy receipt email.',
  'activate.testmode': 'TEST mode unlock — customers use a real Lemon Squeezy code.',
  'activate.alreadypro': 'You already have full Pro access — no trial needed.',
  'activate.trialused': 'Your free trial has already been used.',
  'activate.trialactive': 'Pro is active — enjoy all {n} prompts!',
  'activate.pro.unlocked': 'PromptRunic Pro unlocked!',
  'activate.trial.unlocked': 'Pro unlocked!',
  'activate.unlocked.sub': 'Pro unlocked for {d} days. Enjoy the full prompt library!',
  'activate.promo.14d': '14-day Pro activated! Enjoy all 700,000+ prompts.',
  'activate.promo.1m': '1-month Pro activated! Enjoy all 700,000+ prompts.',
  'activate.promo.5000c': '5,000 coins added to your account!',
  'activate.promo.used': 'This promo code has already been used on this account.',

  /* ---- Auth Modal ---- */
  'auth.signin.title': 'Sign in to PromptRunic',
  'auth.register.title': 'Create your account',
  'auth.signin.tab': 'Sign in',
  'auth.register.tab': 'Create account',
  'auth.email': 'Email',
  'auth.email.placeholder': 'you@example.com',
  'auth.password': 'Password',
  'auth.password.placeholder': 'At least 6 characters',
  'auth.optin': 'Email me occasional product updates and new prompt packs.',
  'auth.submit.signin': 'Sign in',
  'auth.submit.register': 'Create account',
  'auth.divider': 'or continue with',
  'auth.google': 'Continue with Google',
  'auth.github': 'Continue with GitHub',
  'auth.reset': 'Send a reset email',
  'auth.forgot': 'Forgot your password?',
  'auth.entercredentials': 'Please enter your email and password.',
  'auth.pleasewait': 'Please wait…',
  'auth.account.created': 'Account created — welcome!',
  'auth.signedin': 'Signed in — welcome back!',
  'auth.signedout': 'Signed out',
  'auth.notsetup': 'Account sign-in is not set up yet. See FIREBASE-SETUP.md to enable it.',
  'auth.resetplaceholder': 'Enter your email above first, then tap reset.',
  'auth.resetsent': 'Password reset email sent — check your inbox.',
  'auth.opening': 'Opening {which}…',
  'auth.welcome': 'Signed in — welcome!',

  /* ---- Auth errors ---- */
  'auth.err.email-in-use': 'That email is already registered — switch to "Sign in".',
  'auth.err.invalid-email': 'That email address looks invalid.',
  'auth.err.weak-password': 'Password is too weak — use at least 6 characters.',
  'auth.err.wrong-password': 'Wrong password. Try again or reset it below.',
  'auth.err.user-not-found': 'No account with that email — create one instead.',
  'auth.err.invalid-credential': 'Email or password is incorrect.',
  'auth.err.missing-password': 'Please enter a password.',
  'auth.err.popup-closed': 'The sign-in window was closed before finishing.',
  'auth.err.cancelled': 'Sign-in was cancelled.',
  'auth.err.popup-blocked': 'Your browser blocked the popup — allow popups for this site and retry.',
  'auth.err.account-exists': 'This email is already linked to a different sign-in method.',
  'auth.err.too-many': 'Too many attempts — please wait a moment and try again.',
  'auth.err.network': 'Network error — check your connection and retry.',
  'auth.err.not-allowed': 'This sign-in method is not enabled in Firebase yet.',
  'auth.err.default': 'Something went wrong. Please try again.',

  /* ---- Account Modal ---- */
  'account.title': 'Your account',
  'account.desc': 'Your favorites and Pro access sync automatically across every device you sign in on.',
  'account.signedin': 'Signed in as',
  'account.method': 'Sign-in method',
  'account.plan': 'Plan',
  'account.favs': 'Saved favorites',
  'account.profile': 'PROFILE SETTINGS',
  'account.displayname': 'Display name',
  'account.displayname.placeholder': 'Your name',
  'account.bio': 'Short bio',
  'account.bio.placeholder': 'A line or two about you',
  'account.newpassword': 'New password (leave blank to keep current)',
  'account.save': 'Save changes',
  'account.signout': 'Sign out',
  'account.getpro': 'Get Pro',
  'account.saving': 'Saving…',
  'account.saved': 'Saved.',
  'account.saved.pw': 'Saved - your password was updated.',
  'account.pw.tooshort': 'New password must be at least 6 characters.',
  'account.recentlogin': 'To change your password, please sign out and sign back in, then try again.',
  'account.saved.count': '{n} saved',

  /* ---- Plan badge ---- */
  'plan.free': 'FREE',
  'plan.pro': 'PRO',
  'plan.pro.days': 'PRO · {d}d left',
  'plan.pro.trial': 'PRO · {d}d left',
  'plan.pro.full': 'Pro — full access',
  'plan.pro.trial.label': 'Pro — {d} day{s} left',

  /* ---- Upsell ---- */
  'upsell.title': 'Choose Your Pro Plan',
  'upsell.desc': 'Unlock all 700,000+ prompts across 1,684 categories — writing, marketing, sales, career, coding, AI basics, parenting, travel and more. Flexible plans to fit your needs.',
  'upsell.feat1': '✓ 700,000+ prompts',
  'upsell.feat2': '✓ 1,684 categories',
  'upsell.feat3': '✓ 40 answer styles',
  'upsell.feat4': '✓ All AI assistants',
  'upsell.buy': 'Get Pro Membership',
  'upsell.havecode': 'I already have a code',
  'upsell.note': 'All plans include full access to 700,000+ prompts, 40 answer styles, and all AI assistants. Subscription plans auto-renew — cancel anytime. Lifetime is a one-time payment, yours forever.',

  /* ---- Pricing Table ---- */
  'pricing.plan': 'Plan',
  'pricing.original': 'Original',
  'pricing.sale': 'Sale Price',
  'pricing.permonth': 'Per Month',
  'pricing.save': 'You Save',
  'pricing.month': 'Month',
  'pricing.months': 'Months',
  'pricing.days': 'Days',
  'pricing.billed.3d': 'Billed $0.99 once',
  'pricing.lifetime': 'Lifetime',
  'pricing.flexible': 'Flexible trial',
  'pricing.bestvalue': 'Best Value',
  'pricing.onetime': 'One-time',
  'pricing.payonce': 'Pay once, yours forever',
  'pricing.select': 'Select',
  'pricing.permonth2': '/month',
  'pricing.forever': 'forever',
  'pricing.billed.once': 'Billed $7.99 once',
  'pricing.billed.3m': 'Billed $18 every 3 months',
  'pricing.billed.6m': 'Billed $29 every 6 months',
  'pricing.billed.12m': 'Billed $39 per year',
  'pricing.feat.all': 'Full access to 700K+ prompts',
  'pricing.feat.styles': '40 answer styles',
  'pricing.feat.ai': 'All AI assistants',
  'pricing.feat.priority': 'Priority support',
  'pricing.feat.nosub': 'No subscription ever',

  /* ---- Footer ---- */
  'footer.tagline': 'PromptRunic — an AI prompt launchpad with 700,000+ templates across 1,684 categories.',
  'footer.builtby': 'Built by Zongyu Xie',
  'footer.privacy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.disclaimer': 'PromptRunic is an independent product and is not affiliated with, endorsed by, or sponsored by OpenAI, Anthropic, Microsoft, Google, or DeepSeek. All product names and trademarks are the property of their respective owners. AI-generated answers may be inaccurate — please verify before relying on them.',
  'footer.rights': 'All rights reserved.',

  /* ---- Toast messages ---- */
  'toast.copied': 'Prompt copied to clipboard',
  'toast.opening': 'Opening {ai} with your prompt…',
  'toast.copypaste': 'Prompt copied — press Ctrl+V in {ai}',
  'toast.trial.ended': 'Your Pro access has ended — activate Pro to keep full access',
  'toast.pro.ended': 'Your Pro access has ended — activate Pro to keep full access',

  /* ---- Fun.js / Gamification ---- */
  'game.levelup': '🎉 Level up! Level {lvl} — +{coins} 🪙',
  'game.achievement': '🏅 Achievement unlocked: {name}  (+{xp} XP)',
  'game.daily.complete': '✅ Daily challenge complete! +{xp} XP',
  'game.streak': '🔥 Day {n} streak — welcome back! +{xp} XP',
  'game.mood.locked': '🔒 {n} more emojis unlock as you level up',
  'game.mood.header': 'Mood for this prompt',

  /* ---- Backgrounds ---- */
  'bg.choose': 'Choose a background',
  'bg.title': 'Backgrounds',
  'bg.desc.pro': 'Pick any animated background - your choice is saved on this device.',
  'bg.desc.free': '5 backgrounds are free (PromptRunic AI, Cyber Network, Quantum Realm, Constellation & Live Coder). The other 9 are a Pro feature - activate Pro to unlock them.',
  'bg.pro.only': 'That background is a Pro feature - activate Pro to use it',
  'bg.set': 'Background set to {name}',

  /* ---- Community / Social ---- */
  'community.title': 'Community',
  'community.desc': 'See the top players and the moods members leave on prompts. Tap any player to view their profile.',
  'community.tab.level': '🏆 Level',
  'community.tab.coins': '🪙 Coins',
  'community.tab.games': '🎮 Games',
  'community.tab.speed': '⏱️ Speed',
  'community.tab.mood': '😊 Mood Wall',
  'community.loading': 'Loading leaderboard…',
  'community.empty': 'No players on the board yet.<br>Sign in and use PromptRunic — your profile appears here automatically.',
  'community.top50.level': 'Top 50 — highest level & XP',
  'community.top50.coins': 'Top 50 — most coins',
  'community.top50.games': 'Top 50 — best PROMPT MATRIX scores',
  'community.top50.speed': 'Top 50 — fastest PROMPT MATRIX clears',
  'community.back': '‹ Back to leaderboard',
  'community.level': 'level',
  'community.totalxp': 'total XP',
  'community.coins': 'coins',
  'community.achievements': 'achievements',
  'community.beststreak': 'best streak',
  'community.matrixbest': 'PROMPT MATRIX best',
  'community.fastestclear': 'fastest clear',
  'community.moodwall.loading': 'Loading the mood wall…',
  'community.moodwall.empty': 'No moods yet.<br>Open any prompt, pick an emoji under "Mood for this prompt" — it shows up here.',
  'community.moodwall.recent': 'Recent moods from the community',
  'community.mood.others': 'How others felt about this prompt',
  'community.mood.others.count': 'How others felt about this prompt — {n}',
  'community.mood.signin': 'Sign in with Firestore enabled to see community moods.',
  'community.mood.nobody': 'No one else has set a mood here yet — you could be the first.',
  'community.mood.couldnotload': 'Could not load community moods.',
  'community.offline': '{what} need Firebase Firestore turned on.<br>Owner: enable Firestore and publish the rules in <code>FIRESTORE-RULES.md</code>.',
  'community.felt': 'felt',
  'community.on': 'on',
  'community.you': '(you)',
  'community.member': 'Member',

  /* ---- Method names ---- */
  'method.password': 'Email & password',
  'method.google.com': 'Google',
  'method.github.com': 'GitHub',

  /* ---- Category names (these will be overridden by prompts data) ---- */
  'cat.all': 'All Prompts',

  /* ---- Data load error ---- */
  'data.loaderror': 'Could not load prompt data. Please check that all .js files are in the same folder as index.html, then refresh the page.',

  /* ---- Search Dropdown ---- */
  'search.placeholder': "Search 700,000+ prompts — try 'resume', 'cold email', 'trip plan'...",
  'search.categories': 'Categories',
  'search.prompts': 'Prompts',
  'search.nomatch': 'No matching categories or prompts found.',

  /* ---- Prompt Optimizer ---- */
  'optimizer.title': 'Prompt Optimizer',
  'optimizer.desc': 'Enter your prompt or idea below — we\'ll optimize it using our 700,000+ prompt library + optional local AI.',
  'optimizer.placeholder': "Paste your prompt or describe what you need — e.g. 'Write a cover letter for a software engineer role at Google'...",
  'optimizer.quickbtn': '⚡ Quick Optimize',
  'optimizer.aibtn': '🧠 AI Optimize',
  'optimizer.ainotice': '🧠 First-time use requires downloading a local AI model (~1GB). Runs entirely in your browser — no data leaves your device.',
  'optimizer.searching': 'Optimizing...',
  'optimizer.results': 'Related prompts:',
  'optimizer.results.none': 'No matches found',
  'optimizer.empty': 'Please enter a prompt or description to optimize.',
  'optimizer.nomatch': 'No relevant prompts found. Try different keywords or a longer description.',
  'optimizer.relevance': 'Relevance',
  'optimizer.outputlabel': '✨ Optimized Prompt',
  'optimizer.copy': '📋 Copy',
  'optimizer.send': '→ Send to AI',
  'optimizer.loading': 'Loading AI model...',
  'optimizer.loadstart': 'Initializing AI engine...',
  'optimizer.downloading': 'Downloading Qwen2.5-1.5B model...',
  'optimizer.running': 'AI optimizing...',
  'optimizer.nogpu': 'Your browser does not support WebGPU. Try Chrome 113+.',
  'optimizer.aierror': 'AI optimization failed. Falling back to quick optimize.',
  'optimizer.intent': 'Intent',
  'optimizer.keywords': 'Keywords',
  'optimizer.matched': 'Matched',
  'optimizer.prompts': 'prompts',
  'optimizer.ailoaded': 'AI model loaded! You can now use it across the site.',
  'optimizer.keywords.label': '🔍 Suggested Keywords (click to search)',
  'optimizer.refine.title': '🧠 Refine Your Prompt',
  'optimizer.refine.placeholder': 'Tell the AI how to adjust your prompt...',
  'optimizer.refine.send': 'Refine',

  /* ---- AI Selector Popup ---- */
  'aisel.title': 'Send to AI',
  'aisel.subtitle': 'Choose an AI service — your optimized prompt will be copied and sent:',

  /* ---- Consultation Chat ---- */
  'consult.title': 'PromptRunic Assistant',
  'consult.greeting': 'Hi! I\'m your PromptRunic assistant. Ask me anything about the website — how to use prompts, find categories, optimize your prompts, or navigate the site.',
  'consult.placeholder': 'Ask about PromptRunic...',
  'consult.send': 'Send',

  /* ---- Global AI Badge ---- */
  'badge.ai.ready': 'AI Ready',

  /* ---- Hero Chat Demo ---- */
  'demo.title': 'PromptRunic — sending a prompt to an AI',
  'demo.q1': 'Write a cold email to a potential client',
  'demo.a1': 'Subject: A quick idea for {Company}\n\nHi Alex — noticed your team just launched X. Here is one way to…',
  'demo.q2': 'Plan a 5-day trip to Japan on a budget',
  'demo.a2': 'Day 1 — Tokyo: Asakusa + street food. Day 2 — day trip to Nikko…\nRough budget: flights, stays, rail pass…',
  'demo.q3': 'Explain compound interest like I am new',
  'demo.a3': 'Picture a snowball rolling downhill — it grows faster the bigger it gets. Your money does the same…',
  'demo.q4': 'Make this resume line sound stronger',
  'demo.a4': '"Managed a team" becomes "Led a 6-person team to ship 3 products, cutting costs 20%."',
  'demo.q5': 'Write a product description for an eco water bottle',
  'demo.a5': 'Meet the bottle that gives back — 100% recycled stainless steel, keeps drinks cold 24h…',
  'demo.q6': 'Summarize this 3-page report in 5 bullet points',
  'demo.a6': '• Revenue up 12% YoY  • Customer churn dropped to 3.2%  • New market: Southeast Asia…',
  'demo.q7': 'Draft a follow-up email after a job interview',
  'demo.a7': 'Hi Sarah — thank you for the conversation today. I enjoyed learning about the team…',
  'demo.q8': 'Create a weekly meal plan for a vegetarian diet',
  'demo.a8': 'Monday: chickpea curry + brown rice. Tuesday: black-bean tacos with mango salsa…',
  'demo.q9': 'Turn these meeting notes into action items',
  'demo.a9': '1. @Alex: finalize API spec by Friday  2. @Mia: schedule user-testing session…',
  'demo.q10': 'Write a social media caption for a sunset photo',
  'demo.a10': 'Golden hour, golden vibes. Where the sky paints its own masterpiece…',
  'demo.q11': 'Explain blockchain to a 10-year-old',
  'demo.a11': 'Imagine a notebook that everyone can read but nobody can erase — every page is permanent…',
  'demo.q12': 'Write a Python function that sorts a list of dictionaries by a key',
  'demo.a12': 'def sort_by_key(items, key):\n  return sorted(items, key=lambda x: x[key])',
  'demo.q13': 'Draft an apology email for a delayed shipment',
  'demo.a13': 'Dear customer — your order is running 2 days late due to a logistics issue. We have…',
  'demo.q14': 'Brainstorm 10 name ideas for a pet-sitting app',
  'demo.a14': '1. PawStay  2. FidoWatch  3. PetNest  4. CritterCare  5. WhiskerKeep…',
  'demo.q15': 'Rewrite this paragraph in a professional tone',
  'demo.a15': 'Original: "The thing is kinda hard to use." → Revised: "The current interface presents…',
  'demo.q16': 'Create a workout plan for a beginner at home',
  'demo.a16': 'Week 1 — 3 days/week: 10 squats, 10 push-ups (knee OK), 30s plank, 15 lunges…',
  'demo.q17': 'Write a LinkedIn post about a career change into tech',
  'demo.a17': 'Six months ago I could not write a line of code. Today I shipped my first app…',
  'demo.q18': 'Compare GPT-4, Claude, and Gemini for coding tasks',
  'demo.a18': 'GPT-4: strong at complex reasoning, verbose. Claude: careful, great at refactoring…',
  'demo.q19': 'Translate "thank you for your patience" into 5 languages',
  'demo.a19': 'French: Merci pour votre patience  Spanish: Gracias por su paciencia…',
  'demo.q20': 'Write a short poem about the ocean at night',
  'demo.a20': 'The tide whispers secrets to the shore, moonlight dances on waves…',
  'demo.q21': 'Help me outline a 10-slide pitch deck for a startup',
  'demo.a21': 'Slide 1: Hook + vision  2: Problem  3: Solution  4: Demo  5: Market size…'
};

if(typeof window.PPI18n!=='undefined') window.PPI18n.registerDict('en', EN);
window._LANG_EN = EN;

})();
