/* =====================================================================
 * PromptRunic — lang-zh.js  (Chinese translations)
 * Register Chinese dictionary with the i18n engine.
 * ===================================================================== */
(function(){
'use strict';

var ZH = {
  /* ---- Header ---- */
  'header.prompts': '提示语',
  'header.guide': '新手指南',
  'header.activate': '激活码',
  'header.signin': '登录',
  'header.game': '游戏',
  'header.getpro': '获取专业版',
  'header.community': '社区',
  'header.friends': '好友',
  'header.optimizer': '优化器',

  /* ---- Hero ---- */
  'hero.h1.prefix': 'PromptRunic',
  'hero.h1.grad': '你的 AI 提示语生成器 & AI 助手',
  'hero.h1.suffix': '<br/>700,000+ AI 提示语，一键发送任一条。',
  'hero.p': '{freeN} 条提示语可免费使用 — 用专业版激活码解锁全部 {totalN} 条。PromptRunic 是你的 AI 伙伴，助你写作、编程、营销等。AI 新手？我们教你如何提问。',

  /* ---- CTA ---- */
  'cta.browse': '浏览提示语',
  'cta.unlock': '获取 Pro — 低至 $0.99',
  'cta.play': '🎮 玩游戏',

  /* ---- Stats ---- */
  'stat.prompts': '即用提示语',
  'stat.categories': '分类',
  'stat.styles': '回答风格',
  'stat.assistants': 'AI 助手',

  /* ---- Universe ---- */
  'universe.eyebrow': 'PromptRunic 宇宙',
  'universe.title': '提示语的银河。\n一个发射台。',
  'universe.sub': '700,000 条即用提示语，横跨 1,684 个分类 — 写作、编程、营销、学习、育儿、旅行等等。选一条，填空，发给你的 AI。',
  'universe.cta': '进入提示语库 ›',

  /* ---- Guide ---- */
  'guide.title': 'AI 新手？2 分钟掌握全部技巧。',
  'guide.sub': 'AI 的回答质量取决于你的提示语。这是每条 PromptRunic 提示语内置的配方 — 你只需填空。',
  'guide.step1': '1 · 角色',
  'guide.step1.desc': '告诉 AI 扮演谁 — "扮演一位资深职业教练…"',
  'guide.step2': '2 · 任务',
  'guide.step2.desc': '明确说出你想要什么。',
  'guide.step3': '3 · 上下文',
  'guide.step3.desc': '给出真实细节：姓名、数字、你的情况。',
  'guide.step4': '4 · 格式',
  'guide.step4.desc': '你想要什么样的回答 — 表格、5 条要点、一封邮件。',
  'guide.step5': '5 · 限制',
  'guide.step5.desc': '限制和语气 — "150 字以内，友好，不用术语。"',
  'guide.weak': '弱提示语',
  'guide.weak.example': '"写一份简历。"',
  'guide.strong': '强提示语',
  'guide.strong.example': '"扮演一位专业简历撰写师。将我作为营销经理的经历改写为 5 条可量化的成果要点。一页纸，自信但不浮夸。"',
  'guide.tip': '提示：打开下方的 <strong>AI 基础</strong> 分类 — 那些提示语是辅导工具，能把你粗糙的想法变成优秀的提示语。',

  /* ---- Search ---- */
  'search.placeholder': "搜索 700,000+ 提示语 — 试试 '简历'、'冷邮件'、'旅行计划'...",

  /* ---- Sidebar ---- */
  'sidebar.library': '提示语库',
  'sidebar.you': '个人',
  'sidebar.all': '全部提示语',
  'sidebar.favorites': '★ 收藏',

  /* ---- Grid ---- */
  'grid.locked': '🔒 专业版',
  'grid.free': '免费',
  'grid.noprompts': '这里还没有提示语。',
  'grid.noprompts.fav': ' 收藏一条提示语即可保存。',
  'grid.showmore': '显示更多',
  'grid.prompt.s': ' 条提示语',
  'grid.prompt': ' 条提示语',
  'grid.locked.count': ' 条锁定（激活专业版解锁）',
  'grid.showing': ' · 显示 ',

  /* ---- Prompt Modal ---- */
  'pm.tip': '💡 提示：在下方空格中填写越具体，回答越好。添加真实姓名、数字和上下文。',
  'pm.style.label': '回答风格 — 选择你想要的回复类型：',
  'pm.output.label': '你完成的提示语',
  'pm.copy': '复制提示语',
  'pm.fav.save': '☆ 收藏',
  'pm.fav.saved': '★ 已收藏',
  'pm.noblanks': '此提示语无需填空 — 直接复制或发送给 AI。',
  'pm.ai.label': '直接发送给 AI — 提示语已复制，AI 页面将打开：',
  'pm.ai.note': 'ChatGPT 和 Claude 会通过链接自动填入提示语。对于 Copilot、Gemini 和 DeepSeek，请按 <strong>Ctrl+V</strong> 粘贴 — 已在剪贴板中。所有 AI 的一键自动填入及两个内置本地 AI，在 PromptRunic 桌面应用中。',

  /* ---- Prompt History / Share ---- */
  'pm.history.title': '提示词历史记录',
  'pm.history.empty': '还没有浏览过的提示词。',
  'pm.share.copied': '分享链接已复制！专业版提示词需要登录 + Pro 才能查看。',
  'share.login.required': '这是一个专业版提示词，请登录后查看。',
  'share.pro.required': '这是一个专业版提示词，请激活 Pro 后查看。',

  /* ---- Avatar ---- */
  'avatar.title': '选择你的头像',
  'avatar.desc': '免费头像始终可用。Pro 头像需要 Pro。等级头像随等级解锁。金币头像可用金币购买。',

  /* ---- Friends ---- */
  'friends.title': '好友',
  'friends.add': '+ 添加',
  'friends.email.placeholder': '输入好友邮箱',
  'friends.sendrequest': '发送请求',
  'friends.chat.placeholder': '输入消息...',
  'pm.tts': '🔊 朗读',
  'pm.expand': '⬆️ 展开',
  'pm.collapse': '⬇️ 收起',

  /* ---- Variant groups ---- */
  'variant.depth': '深度',
  'variant.length': '长度',
  'variant.format': '格式',
  'variant.tone': '语气',
  'variant.perspective': '视角',
  'variant.recent': '最近使用',

  /* ---- 40 Variant style names ---- */
  'variant.v0': '标准',
  'variant.v1': '深入',
  'variant.v2': '快速',
  'variant.v3': '新手友好',
  'variant.v4': '专家审阅',
  'variant.v5': '3个方案',
  'variant.v6': '一句话',
  'variant.v7': '摘要+详述',
  'variant.v8': '全面',
  'variant.v9': '要点列表',
  'variant.v10': '编号步骤',
  'variant.v11': '表格',
  'variant.v12': '检查清单',
  'variant.v13': '问答格式',
  'variant.v14': '利弊分析',
  'variant.v15': '专业',
  'variant.v16': '友好随和',
  'variant.v17': '说服性',
  'variant.v18': '共情',
  'variant.v19': '风趣',
  'variant.v20': '魔鬼代言人',
  'variant.v21': '苏格拉底式',
  'variant.v22': '带示例',
  'variant.v23': '行动计划',
  'variant.v24': '五岁解释',
  'variant.v25': '展示推理',
  'variant.v26': '批评与改进',
  'variant.v27': '两行回答',
  'variant.v28': '穷尽深挖',
  'variant.v29': '思维导纲',
  'variant.v30': '邮件格式',
  'variant.v31': '对话/脚本',
  'variant.v32': '幻灯片大纲',
  'variant.v33': '注释示例',
  'variant.v34': '激励性',
  'variant.v35': '直截了当',
  'variant.v36': '学术',
  'variant.v37': '故事叙述',
  'variant.v38': '强化双方',
  'variant.v39': '未来自我建议',

  /* ---- 40 Variant wrapper prompts (Chinese) ---- */
  'vw.v1': '我想要一个深入、专家级别的回答。\n\n',
  'vw.v1.suffix': '\n\n请包含具体示例、需要避免的常见错误和边缘情况。简要解释你主要建议背后的推理。',
  'vw.v2': '给我一个快速、不含废话的回答——紧凑的要点，无需开场白或总结。\n\n',
  'vw.v3.pre': '我是新手，请保持简单和鼓励性的语气。\n\n',
  'vw.v3.suffix': '\n\n避免使用术语（或用通俗词语解释），最后给出最重要的一点需要记住的内容。',
  'vw.v4.pre': '扮演一位资深',
  'vw.v4.mid': '专家。\n\n',
  'vw.v4.suffix': '\n\n然后质疑我的思路：我遗漏了什么，顶尖专家会怎么做？',
  'vw.v5.suffix': '\n\n给我3个明显不同的版本或方法。标注每个版本，然后推荐哪个最适合并说明原因。',
  'vw.v6.suffix': '\n\n用一句话回答。',
  'vw.v7.suffix': '\n\n先给出一句摘要，然后在下方给出完整回答。',
  'vw.v8.pre': '给我一个全面、毫无遗漏的回答。\n\n',
  'vw.v8.suffix': '\n\n深入覆盖每个相关角度、子情况和注意事项。',
  'vw.v9.suffix': '\n\n将整个回答格式化为清晰的要点——不要长段落。',
  'vw.v10.suffix': '\n\n按顺序给出编号的操作步骤。',
  'vw.v11.suffix': '\n\n将回答组织为列名合理的清晰表格。',
  'vw.v12.suffix': '\n\n将回答作为可勾选的具体检查清单。',
  'vw.v13.suffix': '\n\n将回答组织为一系列可能的问题和清晰答案。',
  'vw.v14.suffix': '\n\n清楚列出利弊，然后给出最终结论和理由。',
  'vw.v15.pre': '使用专业、得体的语气。\n\n',
  'vw.v16.pre': '使用温暖、友好、对话式的语气，就像一位热心的朋友。\n\n',
  'vw.v17.pre': '使用自信、有说服力的语气，做出令人信服的论述。\n\n',
  'vw.v18.pre': '使用温暖、共情和支持性的语气。\n\n',
  'vw.v19.pre': '使用轻松、风趣的语气，带一点幽默——但保持真正有用。\n\n',
  'vw.v20.suffix': '\n\n然后反驳另一面：找出显而易见答案的漏洞，展示可能出错的地方。',
  'vw.v21.pre': '在回答之前，先问我需要的关键问题，以便给出最佳答案。等我的回复后再回答。\n\n',
  'vw.v22.suffix': '\n\n用具体、真实的例子说明每个关键点。',
  'vw.v23.suffix': '\n\n最后给出清晰的优先级行动计划：先做什么、接着做什么、之后做什么。',
  'vw.v24.pre': '用5岁小孩能理解的方式解释——非常简单的词语和有趣的类比。\n\n',
  'vw.v25.suffix': '\n\n在给出最终答案之前，展示你的逐步推理过程。',
  'vw.v26.suffix': '\n\n先给出回答，然后自我批评并提供改进版本。',
  'vw.v27.suffix': '\n\n不超过两行回答。',
  'vw.v28.pre': '给出一个穷尽式的专家级深度分析——不遗漏任何内容。\n\n',
  'vw.v29.suffix': '\n\n将回答组织为缩进式思维导图大纲。',
  'vw.v30.suffix': '\n\n将回答写成可发送的邮件，包含主题行。',
  'vw.v31.suffix': '\n\n将回答写成对话或脚本。',
  'vw.v32.suffix': '\n\n将回答组织为逐页幻灯片演示大纲。',
  'vw.v33.suffix': '\n\n给出一个完整的示例，并注释每个部分为什么有效。',
  'vw.v34.pre': '使用鼓励性、激励性的语气。\n\n',
  'vw.v35.pre': '直截了当——不含糊、不填充。\n\n',
  'vw.v36.pre': '使用精确的学术语气。\n\n',
  'vw.v37.pre': '通过短篇故事或叙述来回答。\n\n',
  'vw.v38.suffix': '\n\n在得出结论之前，先呈现双方最有力的论证。',
  'vw.v39.suffix': '\n\n以我更智慧的未来自我的身份给我建议。',

  /* ---- Activate Modal ---- */
  'activate.title': '激活 PromptRunic 专业版',
  'activate.desc': '输入激活码解锁全部 700,000+ 条提示语。支持所有专业版方案和金币包。',
  'activate.login.title': '需要登录账号',
  'activate.login.desc': '使用专业版必须注册账号或通过 Google/GitHub 登录。你的专业版会员与账号绑定，可在所有设备上同步。',
  'activate.login.btn': '登录 / 注册账号',
  'activate.login.required': '请先登录。专业版需要注册账号或通过 Google/GitHub 登录。',
  'activate.trial.removed': '免费 3 天试用已取消。请选择会员方案，最低 $0.99 可用 3 天。',
  'activate.code.label': '输入你的激活码',
  'activate.code.placeholder': '例如 8B7C-4FA2-9D11-...',
  'activate.redeem': '激活',
  'activate.buy': '查看会员方案',
  'activate.note': '每个激活码只能使用一次。专业版和金币与你的账号绑定，可在所有设备上同步。',
  'activate.entercode': '请输入你的激活码。',
  'activate.checking': '验证中…',
  'activate.notready': '激活功能尚未就绪，请稍后再试。',
  'activate.unlocked': '专业版已解锁，畅享完整提示语库！',
  'activate.coincode': '这是金币码 — 已添加 {n} 金币。专业版请使用专业版激活码。',
  'activate.notpro': '该激活码有效，但不是专业版激活码。',
  'activate.network': '无法连接激活服务器，请检查网络后重试。',
  'activate.invalid': '激活码无效。请检查 Lemon Squeezy 收据邮件中的激活码。',
  'activate.testmode': '测试模式解锁 — 客户请使用真实 Lemon Squeezy 激活码。',
  'activate.alreadypro': '你已拥有完整专业版权限 — 无需试用。',
  'activate.trialused': '你的免费试用已使用。',
  'activate.trialactive': '专业版已激活 — 畅享全部 {n} 条提示语！',
  'activate.pro.unlocked': 'PromptRunic 专业版已解锁！',
  'activate.trial.unlocked': '专业版已解锁！',
  'activate.unlocked.sub': '专业版已解锁 {d} 天，畅享完整提示语库！',
  'activate.promo.14d': '14天专业版已激活！畅享全部 700,000+ 条提示语。',
  'activate.promo.1m': '1个月专业版已激活！畅享全部 700,000+ 条提示语。',
  'activate.promo.5000c': '已添加 5,000 金币到你的账户！',
  'activate.promo.used': '此推广码已在该账号上使用过。',
  'activate.code.used': '此激活码已在你的账号上使用过。每个激活码只能激活一次。',
  'activate.code.used.other': '此激活码已经被使用激活。每个激活码只能使用一次。',
  'activate.limit': '此许可证密钥已达到激活上限。如果你已在其他设备上激活，请先在该设备上停用，或联系客服。',

  /* ---- Auth Modal ---- */
  'auth.signin.title': '登录 PromptRunic',
  'auth.register.title': '创建你的账户',
  'auth.signin.tab': '登录',
  'auth.register.tab': '创建账户',
  'auth.email': '邮箱',
  'auth.email.placeholder': 'you@example.com',
  'auth.password': '密码',
  'auth.password.placeholder': '至少 6 个字符',
  'auth.optin': '偶尔给我发送产品更新和新提示语包。',
  'auth.submit.signin': '登录',
  'auth.submit.register': '创建账户',
  'auth.divider': '或通过以下方式继续',
  'auth.google': '使用 Google 继续',
  'auth.github': '使用 GitHub 继续',
  'auth.reset': '发送重置邮件',
  'auth.forgot': '忘记密码？',
  'auth.entercredentials': '请输入邮箱和密码。',
  'auth.pleasewait': '请稍候…',
  'auth.account.created': '账户已创建 — 欢迎！',
  'auth.signedin': '已登录 — 欢迎回来！',
  'auth.signedout': '已退出登录',
  'auth.notsetup': '账户登录功能尚未配置。请参阅 FIREBASE-SETUP.md 启用。',
  'auth.resetplaceholder': '请先在上方输入邮箱，然后点击重置。',
  'auth.resetsent': '密码重置邮件已发送 — 请查收收件箱。',
  'auth.opening': '正在打开 {which}…',
  'auth.welcome': '已登录 — 欢迎！',

  /* ---- Auth errors ---- */
  'auth.err.email-in-use': '该邮箱已注册 — 请切换到"登录"。',
  'auth.err.invalid-email': '邮箱地址格式不正确。',
  'auth.err.weak-password': '密码太弱 — 请使用至少 6 个字符。',
  'auth.err.wrong-password': '密码错误，请重试或点击下方重置。',
  'auth.err.user-not-found': '该邮箱没有账户 — 请先创建账户。',
  'auth.err.invalid-credential': '邮箱或密码不正确。',
  'auth.err.missing-password': '请输入密码。',
  'auth.err.popup-closed': '登录窗口在完成前已关闭。',
  'auth.err.cancelled': '登录已取消。',
  'auth.err.popup-blocked': '浏览器阻止了弹窗 — 请允许此网站的弹窗后重试。',
  'auth.err.account-exists': '该邮箱已关联其他登录方式。',
  'auth.err.too-many': '尝试次数过多 — 请稍等片刻再试。',
  'auth.err.network': '网络错误 — 请检查网络连接后重试。',
  'auth.err.not-allowed': '此登录方式尚未在 Firebase 中启用。',
  'auth.err.default': '出了点问题，请重试。',

  /* ---- Account Modal ---- */
  'account.title': '你的账户',
  'account.desc': '你的收藏和专业版权限会在所有登录设备上自动同步。',
  'account.signedin': '登录身份',
  'account.method': '登录方式',
  'account.plan': '方案',
  'account.favs': '收藏数量',
  'account.profile': '个人资料设置',
  'account.displayname': '显示名称',
  'account.displayname.placeholder': '你的名字',
  'account.bio': '个人简介',
  'account.bio.placeholder': '一两句话介绍自己',
  'account.newpassword': '新密码（留空保持当前密码）',
  'account.save': '保存更改',
  'account.signout': '退出登录',
  'account.getpro': '获取专业版',
  'account.saving': '保存中…',
  'account.saved': '已保存。',
  'account.saved.pw': '已保存 - 你的密码已更新。',
  'account.pw.tooshort': '新密码至少需要 6 个字符。',
  'account.recentlogin': '如需更改密码，请先退出再重新登录，然后重试。',
  'account.saved.count': '{n} 已收藏',

  /* ---- Plan badge ---- */
  'plan.free': '免费版',
  'plan.pro': '专业版',
  'plan.pro.days': '专业版 · 剩 {d} 天',
  'plan.pro.trial': '专业版 · 剩 {d} 天',
  'plan.pro.full': '专业版 — 完整权限',
  'plan.pro.trial.label': '专业版 — 剩 {d} 天',

  /* ---- Upsell ---- */
  'upsell.title': '选择您的 Pro 方案',
  'upsell.desc': '解锁全部 700,000+ 条提示语，涵盖 1,684 个分类 — 写作、营销、销售、职业、编程、AI 基础、育儿、旅行等等。灵活方案，满足您的需求。',
  'upsell.feat1': '✓ 700,000+ 条提示语',
  'upsell.feat2': '✓ 1,684 个分类',
  'upsell.feat3': '✓ 40 种回答风格',
  'upsell.feat4': '✓ 所有 AI 助手',
  'upsell.buy': '获取 Pro 会员',
  'upsell.havecode': '我已有激活码',
  'upsell.note': '所有方案均包含 700,000+ 条提示语、40 种回答风格和所有 AI 助手的完整访问权限。订阅方案自动续费，可随时取消。终身买断为一次性付费，永久使用。',

  /* ---- Pricing Table ---- */
  'pricing.plan': '方案',
  'pricing.original': '原价',
  'pricing.sale': '优惠价',
  'pricing.permonth': '折合每月',
  'pricing.save': '节省',
  'pricing.month': '个月',
  'pricing.months': '个月',
  'pricing.days': '天',
  'pricing.billed.3d': '一次性支付 $0.99',
  'pricing.lifetime': '终身买断',
  'pricing.flexible': '灵活试用',
  'pricing.bestvalue': '最划算',
  'pricing.onetime': '一次性',
  'pricing.payonce': '一次付费，永久使用',
  'pricing.select': '选择',
  'pricing.permonth2': '/月',
  'pricing.forever': '永久',
  'pricing.billed.once': '一次性支付 $7.99',
  'pricing.billed.3m': '每3个月支付 $18',
  'pricing.billed.6m': '每6个月支付 $29',
  'pricing.billed.12m': '每年支付 $39',
  'pricing.feat.all': '完整访问 700,000+ 提示语',
  'pricing.feat.styles': '40 种回答风格',
  'pricing.feat.ai': '所有 AI 助手',
  'pricing.feat.priority': '优先客服支持',
  'pricing.feat.nosub': '无需订阅',

  /* ---- Footer ---- */
  'footer.tagline': 'PromptRunic — AI 提示词模板库',
  'footer.stats': '700,000+ 模板 · 1,600+ 分类',
  'footer.builtby': '由 Z. Xie 维护',
  'footer.privacy': '隐私政策',
  'footer.terms': '服务条款',
  'footer.disclaimer': '免责声明：PromptRunic 仅提供对第三方 AI 模型的访问，仅供参考。我们不拥有、运营或控制任何底层 AI 模型。所有 AI 生成的输出可能不准确、不完整或存在偏见。您需自行负责在依赖任何信息前进行验证。',
  'footer.affiliation': 'PromptRunic 与 OpenAI、Anthropic、Microsoft、Google、DeepSeek 或任何其他模型提供商无关。',
  'footer.accuracy': '数据准确性：提示词数量和分类数字为近似值，定期更新。实际数字可能略有差异。',
  'footer.misuse': '您同意不使用本网站生成：有害、非法或不道德的内容；侵犯第三方权利的内容；或虚假信息、骚扰或恶意代码。',
  'footer.rights': '保留所有权利。',

  /* ---- Toast messages ---- */
  'toast.copied': '提示语已复制到剪贴板',
  'toast.opening': '正在打开 {ai}，提示语已准备…',
  'toast.copypaste': '提示语已复制 — 请在 {ai} 中按 Ctrl+V 粘贴',
  'toast.trial.ended': '你的专业版权限已结束 — 激活专业版以继续使用完整权限',
  'toast.pro.ended': '你的专业版权限已结束 — 激活专业版以继续使用完整权限',

  /* ---- Fun.js / Gamification ---- */
  'game.levelup': '🎉 升级！等级 {lvl} — +{coins} 🪙',
  'game.achievement': '🏅 成就解锁：{name}  (+{xp} XP)',
  'game.daily.complete': '✅ 每日挑战完成！+{xp} XP',
  'game.streak': '🔥 连续 {n} 天签到 — 欢迎回来！+{xp} XP',
  'game.mood.locked': '🔒 还有 {n} 个表情随升级解锁',
  'game.mood.header': '此提示语的心情',

  /* ---- Backgrounds ---- */
  'bg.choose': '选择背景',
  'bg.title': '背景',
  'bg.desc.pro': '选择任意动画背景 — 你的选择会保存在此设备上。',
  'bg.desc.free': '5 个背景免费（PromptRunic AI、赛博网络、量子领域、星座和实时编码）。其他 9 个是专业版功能 — 激活专业版解锁。',
  'bg.pro.only': '该背景是专业版功能 — 激活专业版后可使用',
  'bg.set': '背景已设为 {name}',

  /* ---- Community / Social ---- */
  'community.title': '社区',
  'community.desc': '查看顶级玩家和成员在提示语上留下心情。点击任何玩家查看其资料。',
  'community.tab.level': '🏆 等级',
  'community.tab.coins': '🪙 金币',
  'community.tab.badges': '🏅 徽章',
  'community.tab.avatars': '🎭 头像',
  'community.tab.games': '🎮 游戏',
  'community.tab.moods': '心情墙',
  'community.tab.speed': '⏱️ 速度',
  'community.tab.mood': '😊 心情墙',
  'community.loading': '正在加载排行榜…',
  'community.empty': '排行榜上还没有玩家。<br>登录并使用 PromptRunic — 你的资料会自动出现在这里。',
  'community.top50.level': '前 50 名 — 最高等级和 XP',
  'community.top50.coins': '前 50 名 — 最多金币',
  'community.top50.badges': '🏅 前 50 名 — 最多徽章解锁',
  'community.top50.avatars': '🎭 前 50 名 — 头像解锁',
  'community.top50.games': '前 50 名 — 最佳 PROMPT MATRIX 得分',
  'community.top50.speed': '前 50 名 — 最快 PROMPT MATRIX 通关',
  'community.back': '‹ 返回排行榜',
  'community.level': '等级',
  'community.totalxp': '总 XP',
  'community.coins': '金币',
  'community.achievements': '成就',
  'community.beststreak': '最佳连续签到',
  'community.matrixbest': 'PROMPT MATRIX 最佳',
  'community.fastestclear': '最快通关',
  'community.moodwall.loading': '正在加载心情墙…',
  'community.moodwall.empty': '还没有心情。<br>打开任意提示语，在"此提示语的心情"下选择表情 — 就会出现在这里。',
  'community.moodwall.recent': '社区最近的心情',
  'community.mood.others': '其他人对这条提示语的心情',
  'community.mood.others.count': '其他人对这条提示语的心情 — {n}',
  'community.mood.signin': '启用 Firestore 登录后可查看社区心情。',
  'community.mood.nobody': '还没有其他人在这里设置心情 — 你可以是第一个。',
  'community.mood.couldnotload': '无法加载社区心情。',
  'community.offline': '{what} 需要启用 Firebase Firestore。<br>站长：请启用 Firestore 并发布 <code>FIRESTORE-RULES.md</code> 中的规则。',
  'community.felt': '感到',
  'community.on': '在',
  'community.you': '(你)',
  'community.member': '成员',

  /* ---- Method names ---- */
  'method.password': '邮箱和密码',
  'method.google.com': 'Google',
  'method.github.com': 'GitHub',

  /* ---- Category names ---- */
  'cat.all': '全部提示语',

  /* ---- Data load error ---- */
  'data.loaderror': '无法加载提示词数据，请确保所有 .js 文件和 index.html 在同一目录下，然后刷新页面。',

  /* ---- Search Dropdown ---- */
  'search.placeholder': "搜索 700,000+ 提示词 — 试试 '简历', '冷邮件', '旅行计划'...",
  'search.categories': '分类',
  'search.prompts': '提示词',
  'search.nomatch': '未找到匹配的分类或提示词。',

  /* ---- Prompt Optimizer ---- */
  'optimizer.title': '提示词优化器',
  'optimizer.desc': '在下方输入你的提示词或想法 — 我们会利用700,000+提示词库+可选本地AI来优化它。',
  'optimizer.placeholder': "粘贴你的提示词或描述你的需求 — 例如 '写一封谷歌软件工程师职位的求职信'...",
  'optimizer.quickbtn': '⚡ 快速优化',
  'optimizer.aibtn': '🧠 AI 优化',
  'optimizer.ainotice': '🧠 首次使用需要下载本地 AI 模型（约1GB）。完全在浏览器中运行 — 不会上传任何数据。',
  'optimizer.searching': '优化中...',
  'optimizer.results': '相关提示词：',
  'optimizer.results.none': '未找到匹配',
  'optimizer.empty': '请输入提示词或描述来进行优化。',
  'optimizer.nomatch': '未找到相关提示词。请尝试不同的关键词或更详细的描述。',
  'optimizer.relevance': '相关度',
  'optimizer.outputlabel': '✨ 优化后的提示词',
  'optimizer.copy': '📋 复制',
  'optimizer.send': '→ 发送给 AI',
  'optimizer.loading': '正在加载 AI 模型...',
  'optimizer.loadstart': '正在初始化 AI 引擎...',
  'optimizer.downloading': '正在下载 Qwen2.5-1.5B 模型...',
  'optimizer.running': 'AI 优化中...',
  'optimizer.nogpu': '您的浏览器不支持 WebGPU，请使用 Chrome 113+。',
  'optimizer.aierror': 'AI 优化失败，正在回退到快速优化。',
  'optimizer.intent': '意图',
  'optimizer.keywords': '关键词',
  'optimizer.matched': '匹配',
  'optimizer.prompts': '条提示词',
  'optimizer.ailoaded': 'AI模型已加载！您现在可以在全站使用AI功能。',
  'optimizer.keywords.label': '🔍 推荐关键词（点击可搜索）',
  'optimizer.refine.title': '🧠 优化您的提示词',
  'optimizer.refine.placeholder': '告诉AI如何调整您的提示词...',
  'optimizer.refine.send': '优化',

  /* ---- AI Selector Popup ---- */
  'aisel.title': '发送到 AI',
  'aisel.subtitle': '选择一个AI服务 — 您的优化提示词将被复制并发送：',

  /* ---- Consultation Chat ---- */
  'consult.title': 'PromptRunic 助手',
  'consult.greeting': '你好！我是你的PromptRunic助手。你可以问我任何关于网站的问题——如何使用提示词、查找分类、优化提示词或浏览网站。',
  'consult.placeholder': '询问关于PromptRunic...',
  'consult.send': '发送',

  /* ---- Global AI Badge ---- */
  'badge.ai.ready': 'AI 已就绪',

  /* ---- Hero Chat Demo ---- */
  'demo.title': 'PromptRunic — 发送提示词给 AI',
  'demo.q1': '写一封给潜在客户的冷邮件',
  'demo.a1': '主题：关于 {公司} 的一个想法\n\n你好 Alex — 注意到你们团队刚发布了 X。这里有一个方法…',
  'demo.q2': '规划一次5天日本预算旅行',
  'demo.a2': '第1天 — 东京：浅草寺 + 街头美食。第2天 — 日光一日游…\n大致预算：机票、住宿、铁路通票…',
  'demo.q3': '用简单的方式解释复利',
  'demo.a3': '想象一个雪球从山上滚下来 — 越大越快。你的钱也是这样…',
  'demo.q4': '让这条简历描述更有力',
  'demo.a4': '"管理团队" 变成 "带领6人团队交付3个产品，降低成本20%。"',
  'demo.q5': '为一款环保水杯写产品描述',
  'demo.a5': '认识这只会回馈的水杯 — 100%再生不锈钢，保冷24小时…',
  'demo.q6': '把这份3页报告总结为5个要点',
  'demo.a6': '• 收入同比增长12%  • 客户流失率降至3.2%  • 新市场：东南亚…',
  'demo.q7': '写一封面试后的跟进邮件',
  'demo.a7': '你好 Sarah — 感谢今天的交流。我很高兴了解团队的情况…',
  'demo.q8': '制定一周素食饮食计划',
  'demo.a8': '周一：鹰嘴豆咖喱 + 糙米。周二：黑豆玉米饼配芒果莎莎酱…',
  'demo.q9': '把会议纪要转为行动项',
  'demo.a9': '1. @Alex：周五前完成API规范  2. @Mia：安排用户测试…',
  'demo.q10': '给一张日落照片写社交媒体文案',
  'demo.a10': '金色时刻，金色心情。天空在绘制自己的杰作…',
  'demo.q11': '向一个10岁小孩解释区块链',
  'demo.a11': '想象一本所有人都能读但没人能擦掉的笔记本 — 每一页都是永久的…',
  'demo.q12': '写一个按键对字典列表排序的Python函数',
  'demo.a12': 'def sort_by_key(items, key):\n  return sorted(items, key=lambda x: x[key])',
  'demo.q13': '写一封发货延迟的道歉邮件',
  'demo.a13': '尊敬的客户 — 您的订单因物流问题延迟2天。我们已经…',
  'demo.q14': '为一个宠物寄养App想10个名字',
  'demo.a14': '1. 爪爪寄养  2. 汪汪看护  3. 宠窝  4. 毛孩管家  5. 喵星守护…',
  'demo.q15': '把这段话改成正式专业语气',
  'demo.a15': '原文："这东西有点难用。" → 修改后："当前界面在用户体验方面存在…',
  'demo.q16': '制定一份居家新手健身计划',
  'demo.a16': '第1周 — 每周3天：10个深蹲、10个俯卧撑（可跪姿）、30秒平板支撑…',
  'demo.q17': '写一篇关于转行做技术的LinkedIn帖子',
  'demo.a17': '半年前我不会写一行代码。今天我发布了第一个应用…',
  'demo.q18': '比较GPT-4、Claude和Gemini在编程任务上的表现',
  'demo.a18': 'GPT-4：复杂推理强，较啰嗦。Claude：谨慎，擅长重构代码…',
  'demo.q19': '把"感谢您的耐心"翻译成5种语言',
  'demo.a19': '法语：Merci pour votre patience  西语：Gracias por su paciencia…',
  'demo.q20': '写一首关于夜晚大海的短诗',
  'demo.a20': '潮汐向岸边低语秘密，月光在波浪上起舞…',
  'demo.q21': '帮我列一个创业公司10页路演PPT大纲',
  'demo.a21': '第1页：钩子 + 愿景  2：问题  3：解决方案  4：演示  5：市场规模…',

  /* ---- Friends / Chat panel ---- */
  'friends.no.requests': '暂无待处理请求',
  'friends.requests': '好友请求',
  'friends.load.error': '无法加载请求',
  'friends.accept': '接受',
  'friends.decline': '拒绝',
  'friends.withdraw': '撤回',
  'friends.sent': '已发送',
  'friends.load.error.list': '无法加载好友列表。<br>请稍后重试。',
  'friends.no.friends': '暂无好友。',
  'friends.no.friends.hint': '去发现页找好友并添加吧！',
  'friends.signin': '登录后查看好友',
  'friends.signin.chats': '登录后查看聊天',
  'friends.no.conversations': '暂无对话。',
  'friends.no.conversations.hint': '从联系人开始聊天吧！',
  'friends.conv.error': '无法加载对话',
  'friends.no.messages': '暂无消息，打个招呼吧！',
  'friends.loading.messages': '正在加载消息...',
  'friends.chat': '聊天',
  'friends.online': '在线',
  'friends.offline': '离线',
  'friends.discover': '发现',
  'friends.contacts': '联系人',
  'friends.chats': '聊天',
  'friends.no.suggestions': '暂无推荐',
  'friends.already.friends': '已是好友',
  'friends.request.received': '已收到请求',
  'friends.profile.error': '无法加载个人资料',
  'friends.send.error': '发送请求出错',
  'friends.request.sent': '好友请求已发送给',
  'friends.cannot.add.self': '不能添加自己',
  'friends.request.already.sent': '请求已发送',
  'friends.already.friends.short': '已是好友',
  'friends.reverse.request': '对方已向你发送请求',
  'friends.accept.error': '接受请求出错',
  'friends.now.friend': '已成为了你的好友！',
  'friends.withdrawn': '好友请求已撤回',
  'friends.messages': '消息',
  'friends.find': '🔍 查找好友',
  'friends.search.placeholder': '按用户名或邮箱搜索...',
  'friends.search': '搜索',
  'friends.suggested': '✨ 为你推荐',
  'friends.send': '发送',
  'friends.searching': '搜索中...',
  'friends.no.results': '未找到用户',
  'friends.search.error': '搜索出错，请重试。'
};

if(typeof window.PPI18n!=='undefined') window.PPI18n.registerDict('zh', ZH);
window._LANG_ZH = ZH;

})();
